### ISSUE TITLE
Fix coordinates array order [MODIS L1B LDAAC data].

### ISSUE THREAD

**Issue by mitkin** [pytroll/satpy#115]
SatPy failed to hash coordinates due to the array ordering, log below. Working with MODIS L1B LDAAC data and `hdfeos_l1b` reader, Python 3.6.3. Same results for develop and master branch. It is possible that the issue should be attributed to the `hdfeos_l1b` reader, not satpy.resample. Data processed comes from [NASA LADSWEB](ftp://ladsweb.nascom.nasa.gov/allData/61/MOD02QKM/2017/238)

```python
Traceback (most recent call last):
  File "/home/mikhail/.virtualenvs/def36/lib/python3.6/site-packages/satpy/resample.py", line 108, in hash_area
    area_hash = "".join((hashlib.sha1(json.dumps(area.proj_dict,
AttributeError: 'SwathDefinition' object has no attribute 'proj_dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/pycharm-community/39/helpers/pydev/pydevd.py", line 1683, in <module>
    main()
  File "/snap/pycharm-community/39/helpers/pydev/pydevd.py", line 1677, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/snap/pycharm-community/39/helpers/pydev/pydevd.py", line 1087, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/39/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/mikhail/Projects/PyTrollDemo/test_satpy.py", line 40, in <module>
    rescn = scn.resample(area_def)
  File "/home/mikhail/.virtualenvs/def36/lib/python3.6/site-packages/satpy/scene.py", line 558, in resample
    **resample_kwargs)
  File "/home/mikhail/.virtualenvs/def36/lib/python3.6/site-packages/satpy/dataset.py", line 572, in resample
    new_data = resample(source_area, data, destination_area, **kwargs)
  File "/home/mikhail/.virtualenvs/def36/lib/python3.6/site-packages/satpy/resample.py", line 524, in resample
    return resampler.resample(data, **kwargs)
  File "/home/mikhail/.virtualenvs/def36/lib/python3.6/site-packages/satpy/resample.py", line 176, in resample
    cache_id = self.precompute(cache_dir=cache_dir, **kwargs)
  File "/home/mikhail/.virtualenvs/def36/lib/python3.6/site-packages/satpy/resample.py", line 251, in precompute
    epsilon=epsilon)
  File "/home/mikhail/.virtualenvs/def36/lib/python3.6/site-packages/satpy/resample.py", line 141, in get_hash
    the_hash = "".join((self.hash_area(source_geo_def),
  File "/home/mikhail/.virtualenvs/def36/lib/python3.6/site-packages/satpy/resample.py", line 128, in hash_area
    hashlib.sha1(lons).hexdigest(),
ValueError: ndarray is not C-contiguous
```

**Comment by davidh-ssec** [comment]
What version of satpy are you using? Could you try the develop branch?

**Comment by mitkin** [comment]
Yep, I've tried current master (==0.7.4) and develop

**Comment by mitkin** [comment]
An update, it seems that the non contiguous arrays come from the grid downscaling by `geotiepoints` interpolator. This is happening when the 500 meters grid is computed from the 1000 meter grid in the `satpy.readers.HDFEOSBandReader`. It has nothing to do with the satpy's hashing methods.

Working on debugging it further.

Actually wondering if it could be machine specific. Exactly the same thing happened when I wrote the SAR-C reader geolocation part. 

Judging by the `pytroll-examples` @adybbroe is obviously using the `hdfeos_l1b reader`, so it must work for him....

**Comment by davidh-ssec** [comment]
@mitkin Could also be a version difference with geotiepoints or of numpy. If the interpolation for geolocation is returning a view rather than a copy at some stage in the calculations then I would expect to see this issue. Meaning if your array is strided in memory or something similar where numpy can use it non-contiguously then this error would happen. I highly doubt the "C" part of the error message is the important part as someone would have to go out of there way to make it fortran ordered.

**Comment by mitkin** [comment]
Spot on. It appears [this line](https://github.com/pytroll/python-geotiepoints/blob/0357eaa73e5f5843154f442ddbb4df693d280097/geotiepoints/interpolator.py#L255) is the trouble maker:
```
            self.new_data[num] = self.new_data[num].reshape(xpoints.shape).T
```
Changing it to:
```
            self.new_data[num] = self.new_data[num].reshape(xpoints.shape).T.copy(order='C')
```
Solves the problem.
Interstengly, the new_data arrays as returned by scipy's spline interpolator, are marked as both, C and F contiguous arrays. 

```
>>> self.new_data[num].flags
Out:
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
```
