### ISSUE TITLE
saving sentinel-2 image as jpg

### ISSUE THREAD

**Issue by Meresmata** [pytroll/satpy#1167]
**Describe the bug**
When saving the sentinel-2 image with: 
`_scn.save_dataset('true_color', filename, writer='simple_image')`

I get the error:
`OSError: cannot write mode RGBA as JPEG`

**To Reproduce**

```python
    files = find_files_and_readers(base_dir=path, reader='msi_safe')

    _scn = Scene(filenames=files)
    _scn.load(['true_color'])

    filename = os.path.join(path, 'RGB.jpg')
    _scn.save_dataset('true_color', filename, writer='simple_image')
    return _scn, filename

```

**Expected behavior**
I wanted the save the satellite image in rgb mode instead of rgba. I thought, in the documentation jpg is mentioned for the simple image writer. Therefore the simplest way should be, to save as jpg (although I would prefer png). 

**Actual results**

```Traceback (most recent call last):
  File "C:\Users\...\anaconda3\envs\Sentinel5\lib\site-packages\PIL\JpegImagePlugin.py", line 612, in _save
    rawmode = RAWMODE[im.mode]
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\...\anaconda3\envs\Sentinel5\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\...\anaconda3\envs\Sentinel5\lib\site-packages\dask\callbacks.py", line 100, in local_callbacks
    yield callbacks or ()
  File "C:\Users\...\anaconda3\envs\Sentinel5\lib\site-packages\dask\local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "C:\Users\...\anaconda3\envs\Sentinel5\lib\site-packages\dask\local.py", line 316, in reraise
    raise exc
  File "C:\Users\...\anaconda3\envs\Sentinel5\lib\site-packages\dask\local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "C:\Users\...\anaconda3\envs\Sentinel5\lib\site-packages\dask\core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "C:\Users\...\anaconda3\envs\Sentinel5\lib\site-packages\dask\utils.py", line 30, in apply
    return func(*args, **kwargs)
  File "C:\Users\...\anaconda3\envs\Sentinel5\lib\site-packages\dask\utils.py", line 880, in __call__
    return getattr(obj, self.method)(*args, **kwargs)
  File "C:\Users\...\anaconda3\envs\Sentinel5\lib\site-packages\PIL\Image.py", line 2134, in save
    save_handler(self, fp, filename)
  File "C:\Users\...\anaconda3\envs\Sentinel5\lib\site-packages\PIL\JpegImagePlugin.py", line 614, in _save
    raise OSError("cannot write mode %s as JPEG" % im.mode)
OSError: cannot write mode RGBA as JPEG
```

**Environment Info:**
 - OS: Windows 10
 - Satpy Version: 0.21.0
 - PyResample Version:1.15.0

**Comment by djhoese** [comment]
By default, Satpy/trollimage tries to use an Alpha band for transparency in the output image. The JPEG format does not support transparency. To get around this you can specify `fill_value=0` to mean "make all invalid values black (0, 0, 0)".

Although the error is a little unclear, it is accurate for the situation. Perhaps we should catch this error in trollimage and say something about `fill_value`. @mraspaud @pnuu thoughts?

**Comment by pnuu** [comment]
Yes, that would be great. This question is asked quite often, so some clarification would be nice.
