### ISSUE TITLE
Dimension name of time in time_bounds is duplicated with the time dimension name of variable

### ISSUE THREAD

**Issue by zxdawn** [pytroll/satpy#1242]
**Describe the bug**
This issue happens when using `save_datasets` with scene blended by time.

**To Reproduce**

```python
from glob import glob
from satpy import Scene, MultiScene
from satpy.multiscene import timeseries

filenames = glob('../data/himawari/**/HS_H08_20190725_05*_B13_*.DAT.bz2', recursive=True)
mscn = MultiScene.from_files(filenames, reader="ahi_hsd")
mscn.load(['B13'])
blended_scene = mscn.blend(blend_function=timeseries)
blended_scene.save_datasets(filename='H8_B13_20190725.nc')
```

**Expected behavior**
New name for time dimension of bounds.

**Actual results**
```
[INFO: 2020-06-25 19:21:48 : satpy.writers.cf_writer] Saving datasets to NetCDF4/CF.
Traceback (most recent call last):
  File "/home/xin/Documents/Github/tobac-tutorials/themes/tobac_v1/Example_OLR_Tracking_satellite/read_h8.py", line 14, in <module>
    blended_scene.save_datasets(filename='H8_B13_20190725.nc')
  File "/home/xin/Documents/Github/satpy_xin/satpy/scene.py", line 1361, in save_datasets
    return writer.save_datasets(datasets, compute=compute, **save_kwargs)
  File "/home/xin/Documents/Github/satpy_xin/satpy/writers/cf_writer.py", line 637, in save_datasets
    end_times)
  File "/home/xin/Software/miniconda3/envs/s5p/lib/python3.7/site-packages/xarray/core/dataset.py", line 1275, in __setitem__
    self.update({key: value})
  File "/home/xin/Software/miniconda3/envs/s5p/lib/python3.7/site-packages/xarray/core/dataset.py", line 3576, in update
    merge_result = dataset_update_method(self, other)
  File "/home/xin/Software/miniconda3/envs/s5p/lib/python3.7/site-packages/xarray/core/merge.py", line 864, in dataset_update_method
    return merge_core([dataset, other], priority_arg=1, indexes=dataset.indexes)
  File "/home/xin/Software/miniconda3/envs/s5p/lib/python3.7/site-packages/xarray/core/merge.py", line 550, in merge_core
    coerced, join=join, copy=False, indexes=indexes, fill_value=fill_value
  File "/home/xin/Software/miniconda3/envs/s5p/lib/python3.7/site-packages/xarray/core/alignment.py", line 409, in deep_align
    fill_value=fill_value,
  File "/home/xin/Software/miniconda3/envs/s5p/lib/python3.7/site-packages/xarray/core/alignment.py", line 317, in align
    % (dim, unlabeled_sizes, labeled_size)
ValueError: arguments without labels along dimension 'time' cannot be aligned because they have different dimension size(s) {1} than the size of the aligned dimension labels: 6
```

**Environment Info:**
 - OS: Linux
 - Satpy Version: 0.22.0

**Additional context**
Temporary solution:
Rename the `time` dimension to `bnds_time` in [`make_time_bounds`](https://github.com/pytroll/satpy/blob/4b92a3cfb828d3140e162a19924e13662f43fe5a/satpy/writers/cf_writer.py#L214):

```
def make_time_bounds(start_times, end_times):
    """Create time bounds for the current *dataarray*."""
    start_time = min(start_time for start_time in start_times
                     if start_time is not None)
    end_time = min(end_time for end_time in end_times
                   if end_time is not None)
    data = xr.DataArray([[np.datetime64(start_time), np.datetime64(end_time)]],
                        dims=['bnds_time', 'bnds_1d'])
    return data
```

This is the result of `ncdump -h H8_B13_20190725.nc` after the modification above:
```
netcdf H8_B13_20190725 {
dimensions:
	x = 5500 ;
	y = 5500 ;
	time = 6 ;
	bnds_time = 1 ;
	bnds_1d = 2 ;
variables:
	int64 FLDK ;
		FLDK:crs_wkt = "PROJCRS[\"unknown\",BASEGEOGCRS[\"unknown\",DATUM[\"unknown\",ELLIPSOID[\"unknown\",6378137,298.257024882273,LENGTHUNIT[\"metre\",1,ID[\"EPSG\",9001]]]],PRIMEM[\"Greenwich\",0,ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8901]]],CONVERSION[\"unknown\",METHOD[\"Geostationary Satellite (Sweep Y)\"],PARAMETER[\"Longitude of natural origin\",140.7,ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8802]],PARAMETER[\"Satellite Height\",35785863,LENGTHUNIT[\"metre\",1,ID[\"EPSG\",9001]]],PARAMETER[\"False easting\",0,LENGTHUNIT[\"metre\",1],ID[\"EPSG\",8806]],PARAMETER[\"False northing\",0,LENGTHUNIT[\"metre\",1],ID[\"EPSG\",8807]]],CS[Cartesian,2],AXIS[\"(E)\",east,ORDER[1],LENGTHUNIT[\"metre\",1,ID[\"EPSG\",9001]]],AXIS[\"(N)\",north,ORDER[2],LENGTHUNIT[\"metre\",1,ID[\"EPSG\",9001]]]]" ;
		FLDK:false_easting = 0. ;
		FLDK:false_northing = 0. ;
		FLDK:geographic_crs_name = "unknown" ;
		FLDK:grid_mapping_name = "geostationary" ;
		FLDK:horizontal_datum_name = "unknown" ;
		FLDK:inverse_flattening = 298.257024882273 ;
		FLDK:latitude_of_projection_origin = 0. ;
		FLDK:long_name = "FLDK" ;
		FLDK:longitude_of_prime_meridian = 0. ;
		FLDK:longitude_of_projection_origin = 140.7 ;
		FLDK:perspective_point_height = 35785863. ;
		FLDK:prime_meridian_name = "Greenwich" ;
		FLDK:projected_crs_name = "unknown" ;
		FLDK:reference_ellipsoid_name = "unknown" ;
		FLDK:semi_major_axis = 6378137. ;
		FLDK:semi_minor_axis = 6356752.3 ;
		FLDK:sweep_angle_axis = "y" ;
	double x(x) ;
		x:units = "m" ;
		x:standard_name = "projection_x_coordinate" ;
	double y(y) ;
		y:units = "m" ;
		y:standard_name = "projection_y_coordinate" ;
	double time(time) ;
		time:standard_name = "time" ;
		time:bounds = "time_bnds" ;
		time:units = "days since 2019-07-25T05:00:21.467927" ;
		time:calendar = "proleptic_gregorian" ;
	double longitude(y, x) ;
		longitude:_FillValue = NaN ;
		longitude:name = "longitude" ;
		longitude:standard_name = "longitude" ;
		longitude:units = "degrees_east" ;
	double latitude(y, x) ;
		latitude:_FillValue = NaN ;
		latitude:name = "latitude" ;
		latitude:standard_name = "latitude" ;
		latitude:units = "degrees_north" ;
	float B13(time, y, x) ;
		B13:_FillValue = NaNf ;
		B13:calibration = "brightness_temperature" ;
		B13:end_time = "2019-07-25 05:34:40.838569" ;
		B13:grid_mapping = "FLDK" ;
		B13:id = "[\"B13\", [10.2, 10.4, 10.6], 2000, null, \"brightness_temperature\", null, []]" ;
		B13:modifiers = "" ;
		B13:platform_name = "Himawari-8" ;
		B13:resolution = 2000LL ;
		B13:scheduled_time = "2019-07-25 05:25:00" ;
		B13:sensor = "ahi" ;
		B13:standard_name = "toa_brightness_temperature" ;
		B13:start_time = "2019-07-25 05:25:21.441533" ;
		B13:units = "K" ;
		B13:wavelength = 10.2, 10.4, 10.6 ;
		B13:coordinates = "longitude latitude" ;
	double time_bnds(bnds_time, bnds_1d) ;

// global attributes:
		:history = "Created by pytroll/satpy on 2020-06-25 11:27:11.038053" ;
		:Conventions = "CF-1.7" ;
```

If it looks fine, I can create a PR for this.

**Comment by sfinkens** [comment]
@zxdawn Thanks for reporting this! Time bounds should have coordinates (time, 2), so the naming is correct here. But we should add one bounds tuple (tstart, tend) for each timestamp instead of adding only one like it is done at the moment. That causes a conflict in the presence of multiple timestamps.

**Comment by sfinkens** [comment]
Something like this in `cf_writer.make_time_bounds`:
```python
data = xr.DataArray([[np.datetime64(start_time), np.datetime64(end_time)]
		      for start_time, end_time in zip(start_times, end_times)],
                      dims=['time', 'bnds_1d'])
```

**Comment by zxdawn** [comment]
@sfinkens Yes, the tuple is a better option. But, the time dimension name of `time_bnds` should be different from that (e.g. time) of variables, right? Otherwise, `xarray` can't update the dataset and save it.

**Comment by zxdawn** [comment]
This related to another issue: #1174.

As `timeseries` calculate the mean values of `start_time` and `end_time`, the time dimension of bounds is always 1.

So, should we assign a tuple to `start_time` and `end_time`?

**Comment by zxdawn** [comment]
I suppose `MultiScene` also wants to handle cases where data were observed at almost the same time but not exactly:
https://github.com/pytroll/satpy/blob/4b92a3cfb828d3140e162a19924e13662f43fe5a/satpy/dataset.py#L60-L69

Then saving tuple `start_time` and `end_time` isn't suitable.
Maybe, we need two kinds of datetime for `MultiScene`:
1. `start_time` and `end_time`
    `start_time` is the minimum of all `start_time`s while `end_time` is the maximum of all `end_time`s.
2. `start_times` and `end_times`
    Both are tuple saving all datetimes.

**Comment by sfinkens** [comment]
I had a quick look at your code sample and noticed that the result has a `time` variable. Maybe it would make sense to add a time bounds variable in `multiscene.timeseries` in a similar way. This variable could then be used by the CF writer.

**Comment by zxdawn** [comment]
So, should we use `time_bnds(bnds_time, bnds_1d)` which contains all `start_time` and `end_time`?

**Comment by sfinkens** [comment]
I think the `timeseries` method should be updated to keep track of the start/end times. Here's a draft:

```diff
diff --git a/satpy/multiscene.py b/satpy/multiscene.py
index d8ef823b..46d2039d 100644
--- a/satpy/multiscene.py
+++ b/satpy/multiscene.py
@@ -62,6 +62,8 @@ def timeseries(datasets):
         if 'time' not in ds.dims:
             tmp = ds.expand_dims("time")
             tmp.coords["time"] = pd.DatetimeIndex([ds.attrs["start_time"]])
+            tmp.coords['start_time'] = ('time', [ds.attrs["start_time"]])
+            tmp.coords['end_time'] = ('time', [ds.attrs["end_time"]])
         else:
             tmp = ds
         expanded_ds.append(tmp)
```

Those `start_time` and `end_time` coordinates are then available in the blended scene and the CF writer could merge them into one proper time bounds variable with dimension `(time, bnds_1d)`. Note that `tmp` here is a `DataArray`, not a `Dataset`, that's why you can't add the time bounds directly.

**Comment by zxdawn** [comment]
Thanks. This method save these times into coordinates.

But, I need to modify the time_bounds like this to successfully save the nc file:
```
diff --git a/satpy/writers/cf_writer.py b/satpy/writers/cf_writer.py
index 80e9bc74..271e4f1c 100644
--- a/satpy/writers/cf_writer.py
+++ b/satpy/writers/cf_writer.py
@@ -206,11 +206,7 @@ def area2cf(dataarray, strict=False):
 
 def make_time_bounds(start_times, end_times):
     """Create time bounds for the current *dataarray*."""
-    start_time = min(start_time for start_time in start_times
-                     if start_time is not None)
-    end_time = min(end_time for end_time in end_times
-                   if end_time is not None)
-    data = xr.DataArray([[np.datetime64(start_time), np.datetime64(end_time)]],
+    data = xr.DataArray([[start_time, end_time]],
                         dims=['time', 'bnds_1d'])
     return data
```

Then, the dimension is as same as `time`.

But, this maybe not the purpose of **bounds**? **bounds** should be the minimum start_time and maximum end_time ... Then, `'bnds_time', 'bnds_1d'` is a better solution:

```
diff --git a/satpy/writers/cf_writer.py b/satpy/writers/cf_writer.py
index 80e9bc74..e08ade7c 100644
--- a/satpy/writers/cf_writer.py
+++ b/satpy/writers/cf_writer.py
@@ -211,7 +211,7 @@ def make_time_bounds(start_times, end_times):
     end_time = min(end_time for end_time in end_times
                    if end_time is not None)
     data = xr.DataArray([[np.datetime64(start_time), np.datetime64(end_time)]],
-                        dims=['time', 'bnds_1d'])
+                         dims=['bnds_time', 'bnds_1d'])
     return data

```

**Comment by sfinkens** [comment]
No, that's fine. The time bounds should specify the time interval (tstart, tend) for each timestamp. See example 7.5 here: http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#cell-methods

**Comment by zxdawn** [comment]
Got it! Created the PR ;)
