### ISSUE TITLE
An error occurred while processing NPP VIIRS, coordinates of different sizes

### ISSUE THREAD

**Issue by DenisPolagaev** [pytroll/satpy#1256]
My code:

```
import satpy
from satpy.scene import Scene
from satpy import find_files_and_readers

print(satpy.__version__)

if __name__ == '__main__':
    my_files = find_files_and_readers(base_dir="E:\\test\\level1\\", reader='viirs_sdr')
    scene = Scene(filenames=my_files)
    print(scene.start_time)
    print(scene.end_time)
    print(scene.all_modifier_names())
    print(scene.available_dataset_ids())
    print(scene.available_dataset_names())
    scene.load(['night_fog'])
```

Output:

```
0.22.0
2020-07-09 07:36:46.961997
2020-07-09 07:49:32.982601
['viirs']
[DatasetID(name='DNB', wavelength=(0.5, 0.7, 0.9), resolution=743, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='I01', wavelength=(0.6, 0.64, 0.68), resolution=371, polarization=None, calibration='radiance', level=None, modifiers=('sunz_corrected_iband',)), DatasetID(name='I01', wavelength=(0.6, 0.64, 0.68), resolution=371, polarization=None, calibration='reflectance', level=None, modifiers=('sunz_corrected_iband',)), DatasetID(name='I02', wavelength=(0.845, 0.865, 0.884), resolution=371, polarization=None, calibration='radiance', level=None, modifiers=('sunz_corrected_iband',)), DatasetID(name='I02', wavelength=(0.845, 0.865, 0.884), resolution=371, polarization=None, calibration='reflectance', level=None, modifiers=('sunz_corrected_iband',)), DatasetID(name='I03', wavelength=(1.58, 1.61, 1.64), resolution=371, polarization=None, calibration='radiance', level=None, modifiers=('sunz_corrected_iband',)), DatasetID(name='I03', wavelength=(1.58, 1.61, 1.64), resolution=371, polarization=None, calibration='reflectance', level=None, modifiers=('sunz_corrected_iband',)), DatasetID(name='I04', wavelength=(3.58, 3.74, 3.9), resolution=371, polarization=None, calibration='brightness_temperature', level=None, modifiers=()), DatasetID(name='I04', wavelength=(3.58, 3.74, 3.9), resolution=371, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='I05', wavelength=(10.5, 11.45, 12.3), resolution=371, polarization=None, calibration='brightness_temperature', level=None, modifiers=()), DatasetID(name='I05', wavelength=(10.5, 11.45, 12.3), resolution=371, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='M01', wavelength=(0.402, 0.412, 0.422), resolution=742, polarization=None, calibration='radiance', level=None, modifiers=('sunz_corrected',)), DatasetID(name='M01', wavelength=(0.402, 0.412, 0.422), resolution=742, polarization=None, calibration='reflectance', level=None, modifiers=('sunz_corrected',)), DatasetID(name='M02', wavelength=(0.436, 0.445, 0.454), resolution=742, polarization=None, calibration='radiance', level=None, modifiers=('sunz_corrected',)), DatasetID(name='M02', wavelength=(0.436, 0.445, 0.454), resolution=742, polarization=None, calibration='reflectance', level=None, modifiers=('sunz_corrected',)), DatasetID(name='M03', wavelength=(0.478, 0.488, 0.498), resolution=742, polarization=None, calibration='radiance', level=None, modifiers=('sunz_corrected',)), DatasetID(name='M03', wavelength=(0.478, 0.488, 0.498), resolution=742, polarization=None, calibration='reflectance', level=None, modifiers=('sunz_corrected',)), DatasetID(name='M04', wavelength=(0.545, 0.555, 0.565), resolution=742, polarization=None, calibration='radiance', level=None, modifiers=('sunz_corrected',)), DatasetID(name='M04', wavelength=(0.545, 0.555, 0.565), resolution=742, polarization=None, calibration='reflectance', level=None, modifiers=('sunz_corrected',)), DatasetID(name='M05', wavelength=(0.662, 0.672, 0.682), resolution=742, polarization=None, calibration='radiance', level=None, modifiers=('sunz_corrected',)), DatasetID(name='M05', wavelength=(0.662, 0.672, 0.682), resolution=742, polarization=None, calibration='reflectance', level=None, modifiers=('sunz_corrected',)), DatasetID(name='M06', wavelength=(0.739, 0.746, 0.754), resolution=742, polarization=None, calibration='radiance', level=None, modifiers=('sunz_corrected',)), DatasetID(name='M06', wavelength=(0.739, 0.746, 0.754), resolution=742, polarization=None, calibration='reflectance', level=None, modifiers=('sunz_corrected',)), DatasetID(name='M07', wavelength=(0.846, 0.865, 0.885), resolution=742, polarization=None, calibration='radiance', level=None, modifiers=('sunz_corrected',)), DatasetID(name='M07', wavelength=(0.846, 0.865, 0.885), resolution=742, polarization=None, calibration='reflectance', level=None, modifiers=('sunz_corrected',)), DatasetID(name='M08', wavelength=(1.23, 1.24, 1.25), resolution=742, polarization=None, calibration='radiance', level=None, modifiers=('sunz_corrected',)), DatasetID(name='M08', wavelength=(1.23, 1.24, 1.25), resolution=742, polarization=None, calibration='reflectance', level=None, modifiers=('sunz_corrected',)), DatasetID(name='M09', wavelength=(1.371, 1.378, 1.386), resolution=742, polarization=None, calibration='radiance', level=None, modifiers=('sunz_corrected',)), DatasetID(name='M09', wavelength=(1.371, 1.378, 1.386), resolution=742, polarization=None, calibration='reflectance', level=None, modifiers=('sunz_corrected',)), DatasetID(name='M10', wavelength=(1.58, 1.61, 1.64), resolution=742, polarization=None, calibration='radiance', level=None, modifiers=('sunz_corrected',)), DatasetID(name='M10', wavelength=(1.58, 1.61, 1.64), resolution=742, polarization=None, calibration='reflectance', level=None, modifiers=('sunz_corrected',)), DatasetID(name='M11', wavelength=(2.225, 2.25, 2.275), resolution=742, polarization=None, calibration='radiance', level=None, modifiers=('sunz_corrected',)), DatasetID(name='M11', wavelength=(2.225, 2.25, 2.275), resolution=742, polarization=None, calibration='reflectance', level=None, modifiers=('sunz_corrected',)), DatasetID(name='M12', wavelength=(3.61, 3.7, 3.79), resolution=742, polarization=None, calibration='brightness_temperature', level=None, modifiers=()), DatasetID(name='M12', wavelength=(3.61, 3.7, 3.79), resolution=742, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='M13', wavelength=(3.973, 4.05, 4.128), resolution=742, polarization=None, calibration='brightness_temperature', level=None, modifiers=()), DatasetID(name='M13', wavelength=(3.973, 4.05, 4.128), resolution=742, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='M14', wavelength=(8.4, 8.55, 8.7), resolution=742, polarization=None, calibration='brightness_temperature', level=None, modifiers=()), DatasetID(name='M14', wavelength=(8.4, 8.55, 8.7), resolution=742, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='M15', wavelength=(10.263, 10.763, 11.263), resolution=742, polarization=None, calibration='brightness_temperature', level=None, modifiers=()), DatasetID(name='M15', wavelength=(10.263, 10.763, 11.263), resolution=742, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='M16', wavelength=(11.538, 12.013, 12.489), resolution=742, polarization=None, calibration='brightness_temperature', level=None, modifiers=()), DatasetID(name='M16', wavelength=(11.538, 12.013, 12.489), resolution=742, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='dnb_latitude', wavelength=None, resolution=743, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='dnb_longitude', wavelength=None, resolution=743, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='dnb_lunar_zenith_angle', wavelength=None, resolution=743, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='dnb_moon_illumination_fraction', wavelength=None, resolution=None, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='dnb_satellite_azimuth_angle', wavelength=None, resolution=743, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='dnb_satellite_zenith_angle', wavelength=None, resolution=743, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='dnb_solar_zenith_angle', wavelength=None, resolution=743, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='i_latitude', wavelength=None, resolution=371, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='i_longitude', wavelength=None, resolution=371, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='m_latitude', wavelength=None, resolution=742, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='m_longitude', wavelength=None, resolution=742, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='satellite_azimuth_angle', wavelength=None, resolution=371, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='satellite_azimuth_angle', wavelength=None, resolution=742, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='satellite_zenith_angle', wavelength=None, resolution=371, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='satellite_zenith_angle', wavelength=None, resolution=742, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='solar_azimuth_angle', wavelength=None, resolution=371, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='solar_azimuth_angle', wavelength=None, resolution=742, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='solar_zenith_angle', wavelength=None, resolution=371, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='solar_zenith_angle', wavelength=None, resolution=742, polarization=None, calibration=None, level=None, modifiers=())]
['DNB', 'I01', 'I02', 'I03', 'I04', 'I05', 'M01', 'M02', 'M03', 'M04', 'M05', 'M06', 'M07', 'M08', 'M09', 'M10', 'M11', 'M12', 'M13', 'M14', 'M15', 'M16', 'dnb_latitude', 'dnb_longitude', 'dnb_lunar_zenith_angle', 'dnb_moon_illumination_fraction', 'dnb_satellite_azimuth_angle', 'dnb_satellite_zenith_angle', 'dnb_solar_zenith_angle', 'i_latitude', 'i_longitude', 'm_latitude', 'm_longitude', 'satellite_azimuth_angle', 'satellite_zenith_angle', 'solar_azimuth_angle', 'solar_zenith_angle']
Could not load dataset 'DatasetID(name='M12', wavelength=(3.61, 3.7, 3.79), resolution=742, polarization=None, calibration='brightness_temperature', level=None, modifiers=())': arguments without labels along dimension 'y' cannot be aligned because they have different dimension sizes: {6896, 6894}
Traceback (most recent call last):
  File "C:\Users\polag\PycharmProjects\JPSS\venv\lib\site-packages\satpy\readers\yaml_reader.py", line 782, in _load_dataset_with_area
    ds = self._load_dataset_data(file_handlers, dsid, **kwargs)
  File "C:\Users\polag\PycharmProjects\JPSS\venv\lib\site-packages\satpy\readers\yaml_reader.py", line 667, in _load_dataset_data
    proj = self._load_dataset(dsid, ds_info, file_handlers, **kwargs)
  File "C:\Users\polag\PycharmProjects\JPSS\venv\lib\site-packages\satpy\readers\yaml_reader.py", line 643, in _load_dataset
    projectable = fh.get_dataset(dsid, ds_info)
  File "C:\Users\polag\PycharmProjects\JPSS\venv\lib\site-packages\satpy\readers\viirs_sdr.py", line 369, in get_dataset
    data = self.scale_swath_data(data, factors)
  File "C:\Users\polag\PycharmProjects\JPSS\venv\lib\site-packages\satpy\readers\viirs_sdr.py", line 247, in scale_swath_data
    data = data * factors[:, 0] + factors[:, 1]
  File "C:\Users\polag\PycharmProjects\JPSS\venv\lib\site-packages\xarray\core\dataarray.py", line 2593, in func
    self, other = align(self, other, join=align_type, copy=False)
  File "C:\Users\polag\PycharmProjects\JPSS\venv\lib\site-packages\xarray\core\alignment.py", line 327, in align
    % (dim, sizes)
ValueError: arguments without labels along dimension 'y' cannot be aligned because they have different dimension sizes: {6896, 6894}
Could not load dataset 'DatasetID(name='M15', wavelength=(10.263, 10.763, 11.263), resolution=742, polarization=None, calibration='brightness_temperature', level=None, modifiers=())': arguments without labels along dimension 'y' cannot be aligned because they have different dimension sizes: {6896, 6894}
Traceback (most recent call last):
  File "C:\Users\polag\PycharmProjects\JPSS\venv\lib\site-packages\satpy\readers\yaml_reader.py", line 782, in _load_dataset_with_area
    ds = self._load_dataset_data(file_handlers, dsid, **kwargs)
  File "C:\Users\polag\PycharmProjects\JPSS\venv\lib\site-packages\satpy\readers\yaml_reader.py", line 667, in _load_dataset_data
    proj = self._load_dataset(dsid, ds_info, file_handlers, **kwargs)
  File "C:\Users\polag\PycharmProjects\JPSS\venv\lib\site-packages\satpy\readers\yaml_reader.py", line 643, in _load_dataset
    projectable = fh.get_dataset(dsid, ds_info)
  File "C:\Users\polag\PycharmProjects\JPSS\venv\lib\site-packages\satpy\readers\viirs_sdr.py", line 369, in get_dataset
    data = self.scale_swath_data(data, factors)
  File "C:\Users\polag\PycharmProjects\JPSS\venv\lib\site-packages\satpy\readers\viirs_sdr.py", line 247, in scale_swath_data
    data = data * factors[:, 0] + factors[:, 1]
  File "C:\Users\polag\PycharmProjects\JPSS\venv\lib\site-packages\xarray\core\dataarray.py", line 2593, in func
    self, other = align(self, other, join=align_type, copy=False)
  File "C:\Users\polag\PycharmProjects\JPSS\venv\lib\site-packages\xarray\core\alignment.py", line 327, in align
    % (dim, sizes)
ValueError: arguments without labels along dimension 'y' cannot be aligned because they have different dimension sizes: {6896, 6894}
Could not load dataset 'DatasetID(name='M16', wavelength=(11.538, 12.013, 12.489), resolution=742, polarization=None, calibration='brightness_temperature', level=None, modifiers=())': arguments without labels along dimension 'y' cannot be aligned because they have different dimension sizes: {6896, 6894}
Traceback (most recent call last):
  File "C:\Users\polag\PycharmProjects\JPSS\venv\lib\site-packages\satpy\readers\yaml_reader.py", line 782, in _load_dataset_with_area
    ds = self._load_dataset_data(file_handlers, dsid, **kwargs)
  File "C:\Users\polag\PycharmProjects\JPSS\venv\lib\site-packages\satpy\readers\yaml_reader.py", line 667, in _load_dataset_data
    proj = self._load_dataset(dsid, ds_info, file_handlers, **kwargs)
  File "C:\Users\polag\PycharmProjects\JPSS\venv\lib\site-packages\satpy\readers\yaml_reader.py", line 643, in _load_dataset
    projectable = fh.get_dataset(dsid, ds_info)
  File "C:\Users\polag\PycharmProjects\JPSS\venv\lib\site-packages\satpy\readers\viirs_sdr.py", line 369, in get_dataset
    data = self.scale_swath_data(data, factors)
  File "C:\Users\polag\PycharmProjects\JPSS\venv\lib\site-packages\satpy\readers\viirs_sdr.py", line 247, in scale_swath_data
    data = data * factors[:, 0] + factors[:, 1]
  File "C:\Users\polag\PycharmProjects\JPSS\venv\lib\site-packages\xarray\core\dataarray.py", line 2593, in func
    self, other = align(self, other, join=align_type, copy=False)
  File "C:\Users\polag\PycharmProjects\JPSS\venv\lib\site-packages\xarray\core\alignment.py", line 327, in align
    % (dim, sizes)
ValueError: arguments without labels along dimension 'y' cannot be aligned because they have different dimension sizes: {6896, 6894}
The following datasets were not created and may require resampling to be generated: DatasetID(name='night_fog', wavelength=None, resolution=None, polarization=None, calibration=None, level=None, modifiers=None)

Process finished with exit code 0
```

The problem is most likely with different coordinate files. 
Processed the NPP with the IPOP program.
Maybe I did something wrong?

**Comment by djhoese** [comment]
Very interesting. The error seems to be suggestion that there are different number of rows (scan lines) in the `data` and `factors` variables (mentioned in the traceback). And only 2 rows different which is very odd. The only way I can see this happening is if your files somehow contain partial granules. Any idea if this could be the case?

The relevant code is:

https://github.com/pytroll/satpy/blob/3128bf5d4c736f3475fec6b3f6552b9e4b03de12/satpy/readers/viirs_sdr.py#L241-L248

@mraspaud was probably the last person to work on this. Let's see if he has any ideas.

@DenisPolagaev Any more info you can provide on your files would help. For example, if you do `h5dump -H your_M12_file.h5`, what do you see for the "*Factors" variables and the "Radiance" variable (at least I think those are the names).

**Comment by DenisPolagaev** [comment]
https://drive.google.com/drive/folders/10LIfQCollW_VhWvy47GizfwNS9CnyBaq?usp=sharing 
h5 test files

**Comment by djhoese** [comment]
Ok I think I figured some of this out. There seems to be an issue in the file with how many scans it says it has per-granule and the shape of the array where it is storing the data. If we open the file with h5py:

```
import h5py                                                                                                                                                                                                                                     
h = h5py.File("/home/davidh/Downloads/SVM12_npp_d20200709_t0736454_e0749336_b00001_c20200709070531949000_ipop_dev.h5")  
```

then look at some of the metadata:

```
h['All_Data/VIIRS-M12-SDR_All/BrightnessTemperature'].shape                                                                                                                                                                                     
# (6912, 3200)

h['Data_Products/VIIRS-M12-SDR/VIIRS-M12-SDR_Aggr'].attrs['AggregateNumberGranules']
# array([[9]], dtype=uint64)

[h[f'Data_Products/VIIRS-M12-SDR/VIIRS-M12-SDR_Gran_{x}'].attrs['N_Number_Of_Scans'] for x in range(9)]
# [array([[47]], dtype=int32),
 array([[48]], dtype=int32),
 array([[48]], dtype=int32),
 array([[48]], dtype=int32),
 array([[48]], dtype=int32),
 array([[48]], dtype=int32),
 array([[48]], dtype=int32),
 array([[48]], dtype=int32),
 array([[48]], dtype=int32)]

48 * 8 + 47
# 431
431 * 16
# 6896
```

So the array we are given has 6912 rows but the file is telling us that there should only be 6896 based on number of scans, number of granules, and number of rows per scan (16 for M bands). Due to the math in the scaling method I pointed out in my previous comment that gives us the numbers shown in the error:

```
6896 rows / 9 granules => 766 rows per granule (instead of expected 768)
766 rows per granule * 9 granules => 6894 rows
```

Note: The array in the scaling factor method is 6896 because of the granule size issue triggering this if statement when it shouldn't be (I think):

https://github.com/pytroll/satpy/blob/988020bc160eb17966506596d31d00e2135d5aaa/satpy/readers/viirs_sdr.py#L319-L323

@mraspaud Maybe you can sanity check this.

Regardless of the code and whether or not it should be able to handle these files, my opinion is that these files have invalid metadata (they are providing more data than scans they say they have).

**Comment by DenisPolagaev** [comment]
The problem was in viirs_reader for IPPOP version 3. Your library is really good, I used it to translate l15 to hdf5 Electro3. It would be nice if you have documentation or examples that demonstrate how to re-project to another projection. For example: 

```
For NPP, NOAA VIIRS - with WGS 84 in 'PROJCS["Lambert_Conformal_Conic",' 
		'GEOGCS["GCS_WGS_1984",' 
		'DATUM["WGS_1984",' 
		'SPHEROID["WGS_84",6378137.0,298.252223563]],' 
		'PRIMEM["Greenwich",0.0],' 
		'UNIT["Degree",0.0174532925199433]],' 
		'PROJECTION["Lambert_Conformal_Conic_2SP"],' 
		'PARAMETER["False_Easting",0.0],' 
		'PARAMETER["False_Northing",0.0],' 
		'PARAMETER["Central_Meridian",79.950619],' \
		'PARAMETER["Standard_Parallel_1",67.41206675],' 
		'PARAMETER["Standard_Parallel_2",43.58046825],' 
		'PARAMETER["Scale_Factor",1.0],' 
		'PARAMETER["Latitude_Of_Origin",55.4962675],' 
		'UNIT["Meter",1]]'
```
Also, can I use your library to generate multiband TIFF files?

**Comment by mraspaud** [comment]
@djhoese one thing that looks buggy though is the hardcoded value `48` when we very well know that sometimes the number of scans is different.

**Comment by djhoese** [comment]
> one thing that looks buggy though is the hardcoded value 48

Good point @mraspaud. I assume you have time to make a PR for it? :wink: 

>  if you have documentation or examples that demonstrate how to re-project to another projection

@DenisPolagaev Any example you see `.resample` being used this is what it is doing except for maybe the special case of using the `native` resampler where the projection is not changing. See https://satpy.readthedocs.io/en/latest/resample.html for more information on resampling and creating your own custom *area*. An AreaDefinition is what contains the projection and geometry information to resample the data to and is part of the pyresample package.

> Also, can I use your library to generate multiband TIFF files?

@DenisPolagaev Depends exactly what you mean by multiband. You can create RGB/RGBA geotiffs but we do not support different images in one geotiff. I'd recommend using GDAL to do this after generating the single bands with satpy.

**Comment by mraspaud** [comment]
> > one thing that looks buggy though is the hardcoded value 48
> 
> Good point @mraspaud. I assume you have time to make a PR for it? wink

Done in #1267

**Comment by TAlonglong** [comment]
Closing this as a PR shoudl fix this.
