### ISSUE TITLE
HRV channel in netCDF

### ISSUE THREAD

**Issue by Tsironisa** [pytroll/satpy#1359]
HRV channel in netCDF  from seviri wont load althought it is a availible dataset as you can see from the availible dataset id ()
[DatasetID(name='HRV', wavelength=(0.5, 0.7, 0.9), resolution=1000.134348869, polarization=None, calibration='counts', level=None, modifiers=()),

but when i try to load or use as compositor i get the 

Could not load dataset 'DatasetID(name='HRV', wavelength=(0.5, 0.7, 0.9), resolution=1000.134348869, polarization=None, calibration='reflectance', level=None, modifiers=())': conflicting sizes for dimension 'y': length 11136 on <this-array> and length 3712 on 'lat'
Traceback (most recent call last):
  File "C:\Users\Apostolis Tsironis\anaconda3\lib\site-packages\satpy\readers\yaml_reader.py", line 782, in _load_dataset_with_area
    ds = self._load_dataset_data(file_handlers, dsid, **kwargs)
  File "C:\Users\Apostolis Tsironis\anaconda3\lib\site-packages\satpy\readers\yaml_reader.py", line 667, in _load_dataset_data
    proj = self._load_dataset(dsid, ds_info, file_handlers, **kwargs)
  File "C:\Users\Apostolis Tsironis\anaconda3\lib\site-packages\satpy\readers\yaml_reader.py", line 643, in _load_dataset
    projectable = fh.get_dataset(dsid, ds_info)
  File "C:\Users\Apostolis Tsironis\anaconda3\lib\site-packages\satpy\readers\seviri_l1b_nc.py", line 116, in get_dataset
    dataset = dataset.sel(y=slice(None, None, -1))
  File "C:\Users\Apostolis Tsironis\anaconda3\lib\site-packages\xarray\core\dataarray.py", line 1149, in sel
    ds = self._to_temp_dataset().sel(
  File "C:\Users\Apostolis Tsironis\anaconda3\lib\site-packages\xarray\core\dataarray.py", line 422, in _to_temp_dataset
    return self._to_dataset_whole(name=_THIS_ARRAY, shallow_copy=False)
  File "C:\Users\Apostolis Tsironis\anaconda3\lib\site-packages\xarray\core\dataarray.py", line 474, in _to_dataset_whole
    dataset = Dataset._construct_direct(variables, coord_names, indexes=indexes)
  File "C:\Users\Apostolis Tsironis\anaconda3\lib\site-packages\xarray\core\dataset.py", line 872, in _construct_direct
    dims = calculate_dimensions(variables)
  File "C:\Users\Apostolis Tsironis\anaconda3\lib\site-packages\xarray\core\dataset.py", line 206, in calculate_dimensions
    raise ValueError(
ValueError: conflicting sizes for dimension 'y': length 11136 on <this-array> and length 3712 on 'lat'
The following datasets were not created and may require resampling to be generated: DatasetID(name='hrv_clouds', wavelength=None, resolution=None, polarization=None, calibration=None, level=None, modifiers=None)

**Comment by ameraner** [comment]
Hi @Tsironisa , thanks for reporting this and sorry for not reacting earlier. 
I can reproduce the issue. It is related to the HRV channel being assigned the `coords` of the other main channels when loaded within a composite. The coordinates have dimensions `(3712, 3712)` and don't fit the data array shape, causing the error. I will update this issue when this is fixed.

In any case, the image navigation for the HRV channel in the NetCDF reader is not implemented yet, hence any composite using the HRV channel (e.g. the `hrv_clouds` you're using) would be misregistrated and not usable anyway. This is on our to-do list as well, will also update the issue when it is done. 

As you can see, the SEVIRI L1.5 NetCDF reader is not very mature. If you have the possibility to switch data type, the Native and HRIT readers are mature and have been debugged much more precisely.
