### ISSUE TITLE
Loading unavailable dataset from resampled multiscene fails with `KeyError: 'abi_l1b'` (or other reader)

### ISSUE THREAD

**Issue by gerritholl** [pytroll/satpy#1444]
**Describe the bug**

Loading a dataset that isn't available normally leads to an error message such as `Required file type 'c08' not found or loaded for 'C08'`, after which satpy continues processing.  If the loading is done on a `MultiScene` and the `MultiScene` is resampled, an attempt to `.load(...)` this channel from a scene belonging to the resampled `MultiScene` triggers a `KeyError` not on the missing dataset, but on the reader.  This `KeyError` is not caught, causing Python to stop with a traceback.

**To Reproduce**

```python
import satpy
import pyresample

ms = satpy.MultiScene.from_files(
        ["/data/gholl/cache/ABI/OR_ABI-L1b-RadM1-M6C10_G16_s20201912350316_e20201912350385_c20201912350421.nc"],
        reader=["abi_l1b"])
ms.load([6.2, 7.3])
joint = pyresample.create_area_def("joint-area", {'ellps': 'GRS80', 'h': '35786023', 'lon_0': '-75', 'no_defs': 'None', 'proj': 'geos', 'sweep': 'x', 'type': 'crs', 'units': 'm', 'x_0': '0', 'y_0': '0'}, 500, 500, (-2565142.1286, 3406829.3896, -1563133.4846, 4408838.0336))
mr = ms.resample(joint, unload=False)

mr.scenes[0].load([6.2, 7.3])
```

**Expected behavior**

I expect that the second `.load(...)` has the same result as any other `.load(...)` asking for an unavailable dataset: give a friendly error message informing the user/developer that a dataset is unavailable and return control to the user.

**Actual results**

```
[DEBUG: 2020-11-17 15:45:15 : satpy.readers.yaml_reader] Reading ('/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/satpy/etc/readers/abi_l1b.yaml', '/home/gholl/checkouts/satpy/satpy/etc/readers/abi_l1b.yaml')
[DEBUG: 2020-11-17 15:45:15 : satpy.multiscene] Forcing iteration of generator-like object of Scenes
[DEBUG: 2020-11-17 15:45:15 : satpy.scene] Setting 'PPP_CONFIG_DIR' to '/home/gholl/checkouts/satpy/satpy/etc/'
[DEBUG: 2020-11-17 15:45:15 : satpy.readers.yaml_reader] Reading ('/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/satpy/etc/readers/abi_l1b.yaml', '/home/gholl/checkouts/satpy/satpy/etc/readers/abi_l1b.yaml')
[DEBUG: 2020-11-17 15:45:15 : satpy.readers.yaml_reader] Assigning to abi_l1b: ['/data/gholl/cache/ABI/OR_ABI-L1b-RadM1-M6C10_G16_s20201912350316_e20201912350385_c20201912350421.nc']
[DEBUG: 2020-11-17 15:45:15 : satpy.composites.config_loader] Looking for composites config file abi.yaml
[DEBUG: 2020-11-17 15:45:16 : satpy.composites.config_loader] Looking for composites config file visir.yaml
/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
[DEBUG: 2020-11-17 15:45:16 : satpy.readers.abi_l1b] Reading in get_dataset C10.
[DEBUG: 2020-11-17 15:45:16 : satpy.readers.abi_l1b] Calibrating to brightness temperatures
[WARNING: 2020-11-17 15:45:16 : satpy.readers.yaml_reader] Required file type 'c08' not found or loaded for 'C08'
[WARNING: 2020-11-17 15:45:16 : satpy.scene] The following datasets were not created and may require resampling to be generated: DataID(name='C08', wavelength=WavelengthRange(min=5.77, central=6.185, max=6.6, unit='µm'), resolution=2000, calibration=<calibration.brightness_temperature>, modifiers=())
[DEBUG: 2020-11-17 15:45:16 : satpy.scene] Setting 'PPP_CONFIG_DIR' to '/home/gholl/checkouts/satpy/satpy/etc/'
[DEBUG: 2020-11-17 15:45:16 : satpy.scene] Resampling DataID(name='C10', wavelength=WavelengthRange(min=7.24, central=7.34, max=7.44, unit='µm'), resolution=2000, calibration=<calibration.brightness_temperature>, modifiers=())
/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/pyresample/spherical.py:123: RuntimeWarning: invalid value encountered in true_divide
  self.cart /= np.sqrt(np.einsum('...i, ...i', self.cart, self.cart))
/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
[INFO: 2020-11-17 15:45:17 : satpy.resample] Using default KDTree resampler
[DEBUG: 2020-11-17 15:45:17 : satpy.resample] Check if ./resample_lut-eb53a9071b084fab6eecdc4bde3be213a6ddee58.npz exists
[DEBUG: 2020-11-17 15:45:17 : satpy.resample] Computing kd-tree parameters
[DEBUG: 2020-11-17 15:45:17 : satpy.resample] Resampling Rad
Traceback (most recent call last):
  File "mwe107.py", line 12, in <module>
    mr.scenes[0].load([6.2, 7.3])
  File "/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/satpy/scene.py", line 987, in load
    self._read(**kwargs)
  File "/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/satpy/scene.py", line 895, in _read
    return self._read_datasets(nodes, **kwargs)
  File "/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/satpy/scene.py", line 736, in _read_datasets
    reader_instance = self._readers[reader_name]
KeyError: 'abi_l1b'
```

**Environment Info:**
 - openSUSE 15.0
 - Satpy 0.24.0 (also tested with latest master)
 - pyresample 1.17.0

**Additional context**

This one took me a while to dig down to a MCVE...

**Comment by djhoese** [comment]
My initial gut reaction is that this:

```
mr.scenes[0].load([6.2, 7.3])
```

Shouldn't be a supported use of the MultiScene. Obviously it isn't explicitly prohibited, but it smells funny.

That said, I would expect it to get the error you are receiving either.

**Comment by djhoese** [comment]
Oh! You are loading from a resampled Scene. This behavior isn't allowed even with regular Scenes.

**Comment by gerritholl** [comment]
Why not?  `mr.scenes[0]` is just a `Scene` object.  Under the hood I'm looping through the scenes in my `MultiScene`, passing those scenes to another function, and that function takes a `Scene` object, loads some `DataQuery`s (just to be sure they're available), and operates on them.  The function where the `.load(...)` actually happens is agnostic about either that the scenes are coming from a `MultiScene` or that they've been resampled.

**Comment by djhoese** [comment]
I would like to consider `.scenes` as a private member of the MultiScene object. It just wasn't made `._scenes` because I wasn't sure what use cases might come up. In my eyes the MultiScene is an all-or-nothing kind of container; you have to operate on every Scene. That said, I'm not saying this has to be this way, just that that's how I've always envisioned it.

**Comment by gerritholl** [comment]
I can't operate on all or nothing, because my function needs the difference between two adjacent scenes.

**Comment by djhoese** [comment]
> I can't operate on all or nothing, because my function needs the difference between two adjacent scenes.

Then in the long run we should include this use case in the design of the MultiScene interfaces (similar to the `blend` function). Like a `reduce` function or something.

> why does it matter whether the scene resulted from resampling?

The Scene explicitly excludes readers from the resampled Scene when it is created. It does this because there is too much confusion about which products are which and how things should be loaded from the reader. If you want something loaded it needs to be in the pre-resampled Scene. At least that's how it is coded now. There may have been other reasons for this design decision. I'm not sure I can tell from your code snippet why the load can't happen before resampling.

**Comment by gerritholl** [comment]
I suppose I could first make a `.blend(timeseries)` and then work on that.  I'm not sure how that behaves when datasets are missing or have different areas, but I guess it could work.

I didn't know loading from a resampled scene was not supported.  Is this prohibition documented somewhere?  I don't see it mentioned in the documentation for `.load(...)` or `.resample(...)`.

**Comment by djhoese** [comment]
> I suppose I could first make a .blend(timeseries) and then work on that. I'm not sure how that behaves when datasets are missing or have different areas, but I guess it could work.

That's one of those "I'm not going to deal with that case for now because I'm not sure what the right answer is". I'm not sure if the person who added the timeseries stuff checked it either.

> I didn't know loading from a resampled scene was not supported. Is this prohibition documented somewhere? I don't see it mentioned in the documentation for .load(...) or .resample(...).

Possibly not documented. @mraspaud any idea?

**Comment by gerritholl** [comment]
IMO the right answer if you can't load from resampled scenes is that resampling should not return a `Scene` but a `ResampledScene`... when I write a function that takes a Scene can I even tell that it has been resampled?

**Comment by djhoese** [comment]
> when I write a function that takes a Scene can I even tell that it has been resampled?

No because depending on where the input data came from it could be gridded on an AreaDefinition or it could have even been resampled to a SwathDefinition again. This suggests that instead of a ResampledScene, we separate out the data loading to somewhere else and it produces a Scene that has no `.load` at all.

**Comment by gerritholl** [comment]
It's also somehow related to #1273, because the following produces neither warning nor error (note that C01 is not listed in `abi_files`):

```python
import satpy
import satpy.utils
satpy.utils.debug_on()
import glob
import sattools.log
import logging

abi_dir = "/data/gholl/cache/fogtools/abi/2020/04/13/"
abi_glob = f"00/C10/OR_ABI-L1b-RadC-M6C10_G16_s2020104*_e*_c*.nc"
abi_files = glob.glob(abi_dir + abi_glob)

ms = satpy.MultiScene.from_files(
        abi_files,
        reader="abi_l1b")
ms.load(["C01"])
```

I have to add the

```
ms.scenes
```

workaround (see #1273) before I get the warning message `Required file type 'c01' not found or loaded`.

**Comment by djhoese** [comment]
There's a reason MultiScene is experimental.

With the way this is implemented this is completely expected. Everything in the MultiScene is delayed or in a generator. It doesn't run until you actually do something. The `ms.scenes` "workaround" is executing/iterating through those generators, creating the Scenes, and loading the data you requested.

I think we need to decide what a user should be able to expect from the MultiScene and what types of behavior we want to allow. I vote for performance over expected log messages if we have to choose. We could always generate/load the first Scene as a "representative" of the rest of the Scenes and hope that that produces the initial log messages a user might want to see.

**Comment by gerritholl** [comment]
Do you mean the behaviour in this issue is expected or the behaviour in #1273 is expected or both?

I agree that if the interface and behaviour is clearly defined and documented then it's fine to prioritise optimisation over user-friendliness, and postponing actual work is quite standard throughout satpy so I don't see much of a contradiction there (although I would be surprised by an interface that declares #1273 as expected).

**Comment by djhoese** [comment]
I meant the issue in your last comment of not seeing the log message until you do .scenes.
