### ISSUE TITLE
Cannot slice timeseries-blended scene along time dimension when spatial dimension (area) varies

### ISSUE THREAD

**Issue by gerritholl** [pytroll/satpy#1451]
**Describe the bug**

When I have a scene with a time-dimension, such as resulting from calling `.blend(blend_function=timeseries)` on a multiscene, I cannot slice this scene along the time dimension if areas differ between different datasets, even when I'm not slicing along any spatial dimension.

**To Reproduce**

```python
# Your code here
# create a multiscene with differing areas
from datetime import datetime
from numpy import arange
from xarray import DataArray
from satpy import Scene, MultiScene
from satpy.multiscene import timeseries
from pyresample import create_area_def

scenes = []
for i in range(2):
    sc = Scene()
    sc["ds1"] = DataArray(
            arange(5*5).reshape(5, 5),
            dims=("y", "x"),
            attrs={"start_time": datetime(1900, 1, 1, 0, i),
                   "end_time": datetime(1900, 1, 1, 0, i+1),
                   "area": create_area_def(
                       "test-area",
                       {"proj": "eqc", "lat_ts": 0, "lat_0": 0, "lon_0": 0,
                        "x_0": 0, "y_0": 0, "ellps": "sphere", "units": "m",
                        "no_defs": None, "type": "crs"},
                       units="m",
                       shape=(5, 5),
                       resolution=1000,
                       center=(15, 15))})

    sc["ds2"] = DataArray(
            arange(6*6).reshape(6, 6),
            dims=("y", "x"),
            attrs={"start_time": datetime(1900, 1, 1, 0, i),
                   "end_time": datetime(1900, 1, 1, 0, i+1),
                   "area": create_area_def(
                       "test-area",
                       {"proj": "eqc", "lat_ts": 0, "lat_0": 0, "lon_0": 0,
                        "x_0": 0, "y_0": 0, "ellps": "sphere", "units": "m",
                        "no_defs": None, "type": "crs"},
                       units="m",
                       shape=(6, 6),
                       resolution=1000,
                       center=(16, 16))})
    scenes.append(sc)

ms = MultiScene(scenes)
sc3d = ms.blend(blend_function=timeseries)
print(sc3d["ds1"].shape, sc3d["ds2"].shape)
sc0 = sc3d[0, :, :]
```

**Expected behavior**

I expect that a scene should be able to slice along the time dimension even when areas differ between datasets.

**Actual results**

In reality satpy raises a `RuntimeError` stating that the scene cannot be meaningfully sliced.  That isn't true.

```
$ python mwe110.py 
/data/gholl/miniconda3/envs/py38b/lib/python3.8/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
(2, 5, 5) (2, 6, 6)
Traceback (most recent call last):
  File "mwe110.py", line 46, in <module>
    sc0 = sc3d[0, :, :]
  File "/home/gholl/checkouts/satpy/satpy/scene.py", line 705, in __getitem__
    return self.slice(key)
  File "/home/gholl/checkouts/satpy/satpy/scene.py", line 551, in slice
    raise RuntimeError("'Scene' has different areas and cannot "
RuntimeError: 'Scene' has different areas and cannot be usefully sliced.
```

**Environment Info:**
 - OS: openSuse 15.0
 - Satpy Version: 0.24
 - PyResample Version: 1.16.0

**Additional context**

**Comment by djhoese** [comment]
Scene's in general are not really time aware. They assume that slicing is being done on a spatial dimension (x, y, maybe z). The short term solution would be to convert your Scene to an xarray Dataset with Scene.to_xarray_dataset and do the slicing there. Otherwise, we'll need to have the slicing be smarter about what dimensions are being sliced and only complain when the dimension size differs between DataArrays. That would actually be pretty nice to have.
