### ISSUE TITLE
change sensing_time to start_time in hsaf_grib.yaml..?

### ISSUE THREAD

**Issue by peters77** [pytroll/satpy#1461]
I made a composite which combines h03B precipitation with an airmass/ir108_3d
![hsaf](https://user-images.githubusercontent.com/8840918/100720571-813d1980-33be-11eb-90eb-3dde86db8434.jpg)
 seviri hrit composite. I got a problems as seviri needs start_time to got the right time slot but hsaf looks for sensing_time and creation failed. I would like to replace sensing_time with start_time in hsaf_grib.yaml or a fallback to look even after sensing_time. 

**Actual results**
`Traceback (most recent call last):
  File "hsaf_airmass_test.py", line 79, in <module>
    scn = Scene(filenames={'seviri_l1b_hrit': msg_file, 'hsaf_grib': h03b_file})
  File "/home/cpeters/anaconda2/envs/satpy/lib/python3.7/site-packages/satpy/scene.py", line 159, in __init__
    self.attrs.update(self._compute_metadata_from_readers())
  File "/home/cpeters/anaconda2/envs/satpy/lib/python3.7/site-packages/satpy/scene.py", line 182, in _compute_metadata_from_readers
    for x in self._readers.values())
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.datetime' `

I changed to this to got it working:

```
reader:
  description: Reader for Hydrology SAF products
  name: hsaf_grib
  reader: !!python/name:satpy.readers.yaml_reader.FileYAMLReader
  sensors: [hsaf]

file_types:
  hsafgrib:
    file_reader: !!python/name:satpy.readers.hsaf_grib.HSAFFileHandler
#    file_patterns: ['h03_{sensing_time:%Y%m%d_%H%M}_{region:3s}.grb',
#                    'h05_{sensing_time:%Y%m%d_%H%M}_{accum_time:2s}_{region:3s}.grb',
#                    'h03B_{sensing_time:%Y%m%d_%H%M}_{region:3s}.grb',
#                    'S-HSAF-h03B_{sensing_time:%Y%m%d_%H%M}_{region:3s}.grb',
#                    'h05B_{sensing_time:%Y%m%d_%H%M}_{accum_time:2s}_{region:3s}.grb',
#                    'S-HSAF-h05B_{sensing_time:%Y%m%d_%H%M}_{accum_time:2s}_{region:3s}.grb']

    file_patterns: ['h03_{start_time:%Y%m%d_%H%M}_{region:3s}.grb',
                    'h05_{start_time:%Y%m%d_%H%M}_{accum_time:2s}_{region:3s}.grb',
                    'h03B_{start_time:%Y%m%d_%H%M}_{region:3s}.grb',
                    'S-HSAF-h03B_{start_time:%Y%m%d_%H%M}_{region:3s}.grb',
                    'h05B_{start_time:%Y%m%d_%H%M}_{accum_time:2s}_{region:3s}.grb',
                    'S-HSAF-h05B_{start_time:%Y%m%d_%H%M}_{accum_time:2s}_{region:3s}.grb']
```

**Environment Info:**
 - OS: Linux
 - Satpy Version: satpy-0.24.0

**Comment by djhoese** [comment]
I'm ok with the sensing -> start change, but this looks like it may also include a bug in the metadata combining that @gerritholl and @mraspaud worked on.

**Comment by peters77** [comment]
Ok, maybe its obsolete if they fixed the metadata bug.

**Comment by djhoese** [comment]
I don't remember if they worked on a fix, but they did refactor and add features that may have caused this issue.

**Comment by simonrp84** [comment]
Because of the way these products work, the time listed in the filename is not necessarily the start time but it's rather the listed observation time. So I'm a bit uncomfortable with changing this from `sensing_time` to `start_time`.
Tbh I doubt any users will care that much, but I believe we should try to follow the product user guide as closely as possible.

**Comment by peters77** [comment]
No problem and I understand. So maybe there could be a fallback if there is no start_time to look at a sensing_time!? I'm not familiar what's  going on but it would be nice to have a(n) (easy) solution to get it to work without changing the .yaml..!? :-)

**Comment by djhoese** [comment]
>  it's rather the listed observation time

@simonrp84 What does this mean? How does this differ from what `start_time` means in all the other readers? Usually, in my opinion/experience, `start_time` means the start of observation or in rare cases the start of a range of time that the observations are supposed to cover. What does `sensing_time` mean otherwise?

**Comment by simonrp84** [comment]
The H-SAF products are not observations with a given start/end time as such, but rather a longer-timeframe set of observations that are adjusted by a geostationary dataset with a given start/end time.
That means that the product for a particular time (the `sensing_time` will also contain observations from outside the 15 minute seviri timestep that's defined by the sensing time. I can't remember the exact value but I think it can include observations from even several hours earlier, hence why I don't think that `start_time` is appropriate here.

**Comment by peters77** [comment]
Hm...nevertheless the file are disseminated every 15min so there is a relation to a e.g. seviri timeslot. 
`/t1/comp/bas/saf/S-HSAF-h03B_20201201_1900_fdk.grb.gz
/t1/comp/bas/saf/S-HSAF-h03B_20201201_1915_fdk.grb.gz
/t1/comp/bas/saf/S-HSAF-h03B_20201201_1930_fdk.grb.gz
/t1/comp/bas/saf/S-HSAF-h03B_20201201_1945_fdk.grb.gz
/t1/comp/bas/saf/S-HSAF-h03B_20201201_2000_fdk.grb.gz
/t1/comp/bas/saf/S-HSAF-h03B_20201201_2015_fdk.grb.gz
/t1/comp/bas/saf/S-HSAF-h03B_20201201_2030_fdk.grb.gz
/t1/comp/bas/saf/S-HSAF-h03B_20201201_2045_fdk.grb.gz
/t1/comp/bas/saf/S-HSAF-h03B_20201201_2100_fdk.grb.gz`

No problem with sensing_time here....but whats the solution!? Copy sensing_time into a start_time attr?

**Comment by simonrp84** [comment]
Yes, the H-SAF products (at least the ones I'm familiar with) are adjusted based on a specific SEVIRI timeslot, so you are right that there's a relationship to SEVIRI :)

**Comment by djhoese** [comment]
I feel like the long term solution is maybe a smarter understanding of times in Satpy and utility methods to deal with it. Like a start_time -> sensing_time -> forecast_time preference order. I mention forecast_time and maybe a "model_time" for things like GRIB files with model output in them. Right now I think I have "model_time" as when the model was executed but start_time is used as the forecast_time (the time being represented by the data).

Perhaps we need a new/additional "observation_start_time" for this specific case we're talking about and "start_time" is a more generic "this is how you can distinguish this dataset from others" kind of metadata.

Short term: We need to fix the metadata handling.
