### ISSUE TITLE
Reading back satpy written netcdf cf fails for AVHRR; works for eg VIIRS

### ISSUE THREAD

**Issue by TAlonglong** [pytroll/satpy#1529]
**Describe the bug**
Netcdf cf files are generated with the satpy cf writer. When read back this fails for AVHRR, but works for VIIRS.
(Could be other isses with other instruments, but this is what I have tested)

The error message I get when reading back AVHRR netcdf cf is:
```
Traceback (most recent call last):
  File "readback-satpy-nc-cf.py", line 20, in <module>
    global_scene.load(['overview'])
  File "/home/trygveas/pytroll/satpy/satpy/scene.py", line 1130, in load
    self.generate_possible_composites(generate, unload)
  File "/home/trygveas/pytroll/satpy/satpy/scene.py", line 1187, in generate_possible_composites
    keepables = self._generate_composites_from_loaded_datasets()
  File "/home/trygveas/pytroll/satpy/satpy/scene.py", line 1199, in _generate_composites_from_loaded_datasets
    return self._generate_composites_nodes_from_loaded_datasets(nodes)
  File "/home/trygveas/pytroll/satpy/satpy/scene.py", line 1205, in _generate_composites_nodes_from_loaded_datasets
    self._generate_composite(node, keepables)
  File "/home/trygveas/pytroll/satpy/satpy/scene.py", line 1265, in _generate_composite
    **self.attrs)
  File "/home/trygveas/pytroll/satpy/satpy/modifiers/geometry.py", line 58, in __call__
    area_name = hash(vis.attrs['area'])
KeyError: 'area'
```
**To Reproduce**
It's difficult to reproduce the problem. You need a netcdf cf file written with newer versions of satpy (best is 0.25.1) because older versions might have other problems I have not figured out yet.
I could provide the netcdf cf files I have generated for others to test. This is the read back script I use:
```
#!/usr/bin/env python

from satpy.utils import debug_on
from satpy import Scene
debug_on()

filenames = ['/data/pytroll/thredds-netcdf/2020/03/09/platform_name-sensor-20200309121303-20200309122401.nc']
filenames = ['/data/pytroll/thredds-netcdf/platform-sensor-20190215093503-20190215094750.nc']
global_scene = Scene(reader='satpy_cf_nc', filenames=filenames)
global_scene.load(['overview'])

```
**What I think (or guessing...) is the problem**
What I think is the problem is that reading VIIRS coordinate data is done from already computed lat lon values for each pixel(this is how its done from VIIRS SDR data files at least). But for AVHRR, at least from avhrr_l1b_aapp, the lat lon values is interpolated from some tiepoints( and extrapolated at the end of the swath) from the avhrr_l1b_aapp. Then I'm guessing that the netcdf cf reader can not figure out how to get the coordinates from the AVHRR netcdf cf file where the lat lon values are stored already calculated.

What I'm basing my guess on is walking through the code in a debugger, and I see that here https://github.com/pytroll/satpy/blob/master/satpy/readers/yaml_reader.py#L756 reading from VIIRS netcdf cf get the coordinates right, but with AVHRR it does not.

I could not figure out how to make the netcdf cf reader read the AVHRR lat lon values stored in the netcdf cf file. So I need some hints to get this any further

**Environment Info:**
 - OS: Linux
 - Satpy Version: 0.25.1
 - python 3.7.6

**Comment by TAlonglong** [comment]
Closing this. Not relevant anymore.
