### ISSUE TITLE
Reading FSFile fails with TypeError

### ISSUE THREAD

**Issue by gerritholl** [pytroll/satpy#1605]
**Describe the bug**

Trying to pass `FSFile` objects to `satpy.Scene` results in a `TypeError`.

**To Reproduce**

```python
import satpy
from fsspec.implementations.local import LocalFileSystem

satpy.Scene(filenames=[satpy.readers.FSFile("dummy", fs=LocalFileSystem())])
```

**Expected behavior**

I expect satpy to process the files (in this case resulting in `FileNotFoundError` or a related warning message).

**Actual results**

```
Traceback (most recent call last):
  File "/home/gholl/checkouts/protocode/mwe/typeerror-fsfile.py", line 5, in <module>
    satpy.Scene(filenames=[satpy.readers.FSFile(["dummy"], fs=LocalFileSystem())])
  File "/data/gholl/miniconda3/envs/py39/lib/python3.9/site-packages/satpy/scene.py", line 108, in __init__
    self._readers = self._create_reader_instances(filenames=filenames,
  File "/data/gholl/miniconda3/envs/py39/lib/python3.9/site-packages/satpy/scene.py", line 157, in _create_reader_instances
    return load_readers(filenames=filenames,
  File "/data/gholl/miniconda3/envs/py39/lib/python3.9/site-packages/satpy/readers/__init__.py", line 460, in load_readers
    remaining_filenames = set(filenames or [])
TypeError: unhashable type: 'FSFile'
```

**Environment Info:**

 - Satpy Version: 0.26.0

**Additional context**

Is this bad enough to make a 0.26.1 release?

**Comment by djhoese** [comment]
I'm confused at how this doesn't work and isn't tested. Isn't this the intended usage?

**Comment by gerritholl** [comment]
The bug was introduced in dfeb0675664ce0cf6eab00918e37e07f485071d8 by @gerritholl.
