### ISSUE TITLE
UnicodeDecodeError and ValueError when passing local FSFile to abi_l1b

### ISSUE THREAD

**Issue by gerritholl** [pytroll/satpy#1641]
**Describe the bug**

When I pass an `FSFile` object using a file on the local filesystem to a `Scene` with the `abi_l1b` reader, Satpy triggers three tracebacks with exceptions UnicodeDecodeError and ValueError

**To Reproduce**

```python
import satpy.readers
from satpy.utils import debug_on; debug_on()
fsf = satpy.readers.FSFile("/media/nas/x21308/abi/ABI-L1B-RadC/2019/023/18/OR_ABI-L1b-RadC-M3C12_G16_s20190231817167_e20190231819545_c20190231819590.nc")
satpy.Scene([fsf], reader=["abi_l1b"])
```

**Expected behavior**

I expect the scene to be created as if I had passed the filename directly to `satpy.Scene`.

**Actual results**

```
[DEBUG: 2021-04-16 11:08:28 : satpy.readers.yaml_reader] Reading ('/home/gholl/checkouts/satpy/satpy/etc/readers/abi_l1b.yaml',)
[DEBUG: 2021-04-16 11:08:28 : satpy.readers.yaml_reader] Assigning to abi_l1b: [<FSFile "/media/nas/x21308/abi/ABI-L1B-RadC/2019/023/18/OR_ABI-L1b-RadC-M3C12_G16_s20190231817167_e20190231819545_c20190231819590.nc">]
Traceback (most recent call last):
  File "/home/gholl/checkouts/satpy/satpy/readers/abi_base.py", line 61, in nc
    nc = xr.open_dataset(f_obj,
  File "/data/gholl/miniconda3/envs/py39/lib/python3.9/site-packages/xarray/backends/api.py", line 539, in open_dataset
    engine = _autodetect_engine(filename_or_obj)
  File "/data/gholl/miniconda3/envs/py39/lib/python3.9/site-packages/xarray/backends/api.py", line 155, in _autodetect_engine
    engine = _get_engine_from_magic_number(filename_or_obj)
  File "/data/gholl/miniconda3/envs/py39/lib/python3.9/site-packages/xarray/backends/api.py", line 122, in _get_engine_from_magic_number
    magic_number = read_magic_number(filename_or_obj)
  File "/data/gholl/miniconda3/envs/py39/lib/python3.9/site-packages/xarray/core/utils.py", line 667, in read_magic_number
    magic_number = filename_or_obj.read(count)
  File "/data/gholl/miniconda3/envs/py39/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gholl/checkouts/protocode/mwe/pass-fsfile.py", line 4, in <module>
    satpy.Scene([fsf], reader=["abi_l1b"])
  File "/home/gholl/checkouts/satpy/satpy/scene.py", line 108, in __init__
    self._readers = self._create_reader_instances(filenames=filenames,
  File "/home/gholl/checkouts/satpy/satpy/scene.py", line 157, in _create_reader_instances
    return load_readers(filenames=filenames,
  File "/home/gholl/checkouts/satpy/satpy/readers/__init__.py", line 485, in load_readers
    reader_instance.create_filehandlers(
  File "/home/gholl/checkouts/satpy/satpy/readers/yaml_reader.py", line 606, in create_filehandlers
    filehandlers = self._new_filehandlers_for_filetype(filetype_info,
  File "/home/gholl/checkouts/satpy/satpy/readers/yaml_reader.py", line 594, in _new_filehandlers_for_filetype
    return list(filtered_iter)
  File "/home/gholl/checkouts/satpy/satpy/readers/yaml_reader.py", line 562, in filter_fh_by_metadata
    for filehandler in filehandlers:
  File "/home/gholl/checkouts/satpy/satpy/readers/yaml_reader.py", line 503, in _new_filehandler_instances
    yield filetype_cls(filename, filename_info, filetype_info, *req_fh, **fh_kwargs)
  File "/home/gholl/checkouts/satpy/satpy/readers/abi_base.py", line 51, in __init__
    self.nlines = self.nc['y'].size
  File "/data/gholl/miniconda3/envs/py39/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/home/gholl/checkouts/satpy/satpy/readers/abi_base.py", line 66, in nc
    nc = xr.open_dataset(f_obj,
  File "/data/gholl/miniconda3/envs/py39/lib/python3.9/site-packages/xarray/backends/api.py", line 539, in open_dataset
    engine = _autodetect_engine(filename_or_obj)
  File "/data/gholl/miniconda3/envs/py39/lib/python3.9/site-packages/xarray/backends/api.py", line 155, in _autodetect_engine
    engine = _get_engine_from_magic_number(filename_or_obj)
  File "/data/gholl/miniconda3/envs/py39/lib/python3.9/site-packages/xarray/backends/api.py", line 122, in _get_engine_from_magic_number
    magic_number = read_magic_number(filename_or_obj)
  File "/data/gholl/miniconda3/envs/py39/lib/python3.9/site-packages/xarray/core/utils.py", line 662, in read_magic_number
    raise ValueError(
ValueError: cannot guess the engine, file-like object read/write pointer not at the start of the file, please close and reopen, or use a context manager
Exception ignored in: <function NC_ABI_BASE.__del__ at 0x7f7f02932160>
Traceback (most recent call last):
  File "/home/gholl/checkouts/satpy/satpy/readers/abi_base.py", line 291, in __del__
    self.nc.close()
  File "/data/gholl/miniconda3/envs/py39/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/home/gholl/checkouts/satpy/satpy/readers/abi_base.py", line 66, in nc
    nc = xr.open_dataset(f_obj,
  File "/data/gholl/miniconda3/envs/py39/lib/python3.9/site-packages/xarray/backends/api.py", line 539, in open_dataset
    engine = _autodetect_engine(filename_or_obj)
  File "/data/gholl/miniconda3/envs/py39/lib/python3.9/site-packages/xarray/backends/api.py", line 155, in _autodetect_engine
    engine = _get_engine_from_magic_number(filename_or_obj)
  File "/data/gholl/miniconda3/envs/py39/lib/python3.9/site-packages/xarray/backends/api.py", line 122, in _get_engine_from_magic_number
    magic_number = read_magic_number(filename_or_obj)
  File "/data/gholl/miniconda3/envs/py39/lib/python3.9/site-packages/xarray/core/utils.py", line 662, in read_magic_number
    raise ValueError(
ValueError: cannot guess the engine, file-like object read/write pointer not at the start of the file, please close and reopen, or use a context manager
```

**Environment Info:**
 - OS: openSUSE 15.0
 - Satpy Version: v0.27.0-13-g95ec89ac

**Additional context**

The problem appears to be due to line 587 in `reader.__init__.py`, where the file is opened using the default string mode:

https://github.com/pytroll/satpy/blob/95ec89aca35a0da3fabb112f72605fab7f4dc27c/satpy/readers/__init__.py#L578-L586

But `xarray.open_dataset`, when passed a file object, probably needs it to be opened in byte mode (I don't see it written, but that would make sense for sure).

When the file is empty, Scene creation fails with `TypeError: cannot read the magic number form <class 'fsspec.implementations.local.LocalFileOpener'>` (passing a filename directly causes instead a `OSError`, which is better).

**Comment by gerritholl** [comment]
Ultimately, the problem here is because `fsspec.implementations.local.LocalFileSystem.open` returns a `fsspec.implementations.local.LocalFileOpener`, which is not an instance of `io.IOBase`, unlike `s3fs.core.S3File` (as returned by `s3fs.s3FileSystem.open`),

```
In [8]: issubclass(s3fs.S3File, io.IOBase)
Out[8]: True

In [12]: issubclass(fsspec.implementations.local.LocalFileOpener, io.IOBase)
Out[12]: False
```

but xarray relies on this classification:

https://github.com/pydata/xarray/blob/2896a80aaf1fb9ab5197e2c42c731369a2748c42/xarray/core/utils.py#L655-L670

```
def read_magic_number(filename_or_obj, count=8):
    # check byte header to determine file type
    if isinstance(filename_or_obj, bytes):
        magic_number = filename_or_obj[:count]
    elif isinstance(filename_or_obj, io.IOBase):
        if filename_or_obj.tell() != 0:
            raise ValueError(
                "cannot guess the engine, "
                "file-like object read/write pointer not at the start of the file, "
                "please close and reopen, or use a context manager"
            )
        magic_number = filename_or_obj.read(count)
        filename_or_obj.seek(0)
    else:
        raise TypeError(f"cannot read the magic number form {type(filename_or_obj)}")
    return magic_number
```

so resolving this required either (1) a fix in fsspec to make `LocalFileOpener` a subclass of `io.IOBase`, (2) a change in xarray's `read_magic_number` to rely on implementation rather than `isinstance`, (3) a workaround in satpy, or (4) something I didn't think of.

**Comment by gerritholl** [comment]
This actually works with released versions of dependencies.   The failure may not be in Satpy, but be upstream.  Checking.

**Comment by gerritholl** [comment]
Problem in xarray and fsspec, that has been solved with fsspec master. See https://github.com/pydata/xarray/issues/5070 and https://github.com/intake/filesystem_spec/pull/589.
