### ISSUE TITLE
Clean up the utils/ directory

### ISSUE THREAD

**Issue by gerritholl** [pytroll/satpy#1725]
**Describe the bug**

There are scripts in the `satpy/utils` directory that are poorly maintained.  They should be either maintained, documented, and covered by tests, or they should be removed.  Currently, these area:

- [`convert_to_ninjotiff.py`](https://github.com/pytroll/satpy/blob/main/utils/convert_to_ninjotiff.py) — doesn't work, relies on obsolete mpop package
- [`coord2area_def.py`](https://github.com/pytroll/satpy/blob/main/utils/coord2area_def.py) — appears to work, but not very clean, functionality could be moved into satpy or pyresample with a script as a entry point
- [`fetch_avhrr_calcoeffs.py`](https://github.com/pytroll/satpy/blob/main/utils/fetch_avhrr_calcoeffs.py — doesn't work, Python 2 only, uses urllib2 module which no longer exists

**To Reproduce**

```bash
$ python convert_to_ninjotiff.py ...
$ python coord2area_def.py france stere 42.0 51.5 -5.5 8.0 1.5
$ python fetch_avhrr_calcoeffs.py ...
```

**Expected behavior**

I expect any code to ship with Satpy to run.

**Actual results**

`convert_to_ninjotiff.py`:

```
Traceback (most recent call last):
  File "/home/gholl/checkouts/satpy/utils/convert_to_ninjotiff.py", line 36, in <module>
    from mpop.projector import get_area_def
ModuleNotFoundError: No module named 'mpop'
```

`coord2area_def.py`: works, but poor code

`fetch_avhrr_calcoeffs.py`:

```
Traceback (most recent call last):
  File "/home/gholl/checkouts/satpy/utils/fetch_avhrr_calcoeffs.py", line 19, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'
```

**Environment Info:**
 - Satpy Version: main branch

**Comment by djhoese** [comment]
Note https://github.com/pytroll/satpy/pull/324 was started by @loreclem to fix the ninjo script, but it never got finished and when I renamed the master branch to main GitHub detected that his fork or branch no longer existed and closed the PR.
