### ISSUE TITLE
IOError and ValueError raises when using bilinear for GEOS projection

### ISSUE THREAD

**Issue by yukaribbba** [pytroll/satpy#1736]
**Describe the bug**
Trying to reproject an image to GEOS, got errors under bilinear mode.#1731 
No problem with nearest.
File for test: [https://drive.google.com/file/d/1BV92SKKOZQWzDGqx-88XZXKYDYQ-BBjl/view?usp=sharing](url)

**To Reproduce**

```python
from satpy import Scene, find_files_and_readers

files = find_files_and_readers(base_dir="/mnt/hgfs/Downloads/Sat/BlueMarble/test",
                               reader='generic_image')
scn = Scene(filenames=files)
scn.load(['image'])

from pyresample import create_area_def
area_id = 'euro_geos'
proj_string = '+proj=geos +lon_0=0 +h=35785864 +datum=WGS84 +ellps=WGS84 +units=m'
center = (0,0)
radius = (5570248.686685662, 5567248.28340708)
area_def = create_area_def(area_id, proj_string, center=center, radius=radius, resolution=5000)
new_scn = scn.resample(area_def, resampler='bilinear')
new_scn.save_dataset('image', filename='eu.tif', writer='geotiff', base_dir="/mnt/hgfs/Downloads/Sat/BlueMarble/test/", num_threads=8, compress=None, enhance=False, fill_value=0)

```
**Result:**
```
/home/ll/anaconda3/envs/env/lib/python3.9/site-packages/pyproj/crs/crs.py:68: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  return _prepare_from_string(" ".join(pjargs))
/home/ll/anaconda3/envs/env/lib/python3.9/site-packages/pyproj/crs/crs.py:1216: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  return self._crs.to_proj4(version=version)
Traceback (most recent call last):
  File "/home/ll/anaconda3/envs/env/lib/python3.9/site-packages/satpy/resample.py", line 861, in precompute
    self.load_bil_info(cache_dir, **kwargs)
  File "/home/ll/anaconda3/envs/env/lib/python3.9/site-packages/satpy/resample.py", line 882, in load_bil_info
    raise IOError
OSError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ll/Downloads/reproj.py", line 15, in <module>
    new_scn = scn.resample(area_def, resampler='bilinear')
  File "/home/ll/anaconda3/envs/env/lib/python3.9/site-packages/satpy/scene.py", line 812, in resample
    self._resampled_scene(new_scn, destination, resampler=resampler,
  File "/home/ll/anaconda3/envs/env/lib/python3.9/site-packages/satpy/scene.py", line 773, in _resampled_scene
    res = resample_dataset(dataset, destination_area, **kwargs)
  File "/home/ll/anaconda3/envs/env/lib/python3.9/site-packages/satpy/resample.py", line 1382, in resample_dataset
    new_data = resample(source_area, dataset, destination_area, fill_value=fill_value, **kwargs)
  File "/home/ll/anaconda3/envs/env/lib/python3.9/site-packages/satpy/resample.py", line 1345, in resample
    res = resampler_instance.resample(data, **kwargs)
  File "/home/ll/anaconda3/envs/env/lib/python3.9/site-packages/satpy/resample.py", line 432, in resample
    cache_id = self.precompute(cache_dir=cache_dir, **kwargs)
  File "/home/ll/anaconda3/envs/env/lib/python3.9/site-packages/satpy/resample.py", line 865, in precompute
    self.resampler.get_bil_info()
  File "/home/ll/anaconda3/envs/env/lib/python3.9/site-packages/pyresample/bilinear/_base.py", line 116, in get_bil_info
    self._get_fractional_distances()
  File "/home/ll/anaconda3/envs/env/lib/python3.9/site-packages/pyresample/bilinear/_base.py", line 164, in _get_fractional_distances
    _get_four_closest_corners(*self._get_input_xy(),
  File "/home/ll/anaconda3/envs/env/lib/python3.9/site-packages/pyresample/bilinear/_base.py", line 317, in _get_four_closest_corners
    stride, valid_corners = _get_stride_and_valid_corner_indices(
  File "/home/ll/anaconda3/envs/env/lib/python3.9/site-packages/pyresample/bilinear/_base.py", line 519, in _get_stride_and_valid_corner_indices
    x_diff = out_x_tile - in_x
ValueError: operands could not be broadcast together with shapes (4946176,32) (3702080,32) 
```

**Environment Info:**
 - OS: Ubuntu 20.04 64bit
 - Satpy Version: 0.29.0
 - PyResample Version: 1.20.0
 - Readers and writers dependencies (when relevant): [run `from satpy.utils import check_satpy; check_satpy()`]

**Comment by djhoese** [comment]
I think the error you have here isn't specific to the GEOS projection. @pnuu would know more.

The geostationary projection is just a weird one for most resampling algorithms in my opinion. You have to tweak the parameters to get something that looks good.

**Comment by pnuu** [comment]
I can reproduce this by trying to resample to the built-in area `EastEurope`. I'll see if I can find some time to have a closer look before the summer holidays.

**Comment by yukaribbba** [comment]
@djhoese @pnuu Thanks!😁

**Comment by pnuu** [comment]
And resampling to e.g. `euro4` (`proj: stere`) works, so at least it's not something bigger that is broken. My guess is that the failure is something to do with handling of the space pixels.

**Comment by yukaribbba** [comment]
@pnuu Yeah..I also have the same thought.

**Comment by yukaribbba** [comment]
@pnuu OK. I'll just use gdalwarp for alternative temporarily.
