### ISSUE TITLE
Using local FSFile with ABI reader fails with ValueError

### ISSUE THREAD

**Issue by gerritholl** [pytroll/satpy#1741]
**Describe the bug**

For the ABI L1b reader, I can pass a `FSFile` instance if this is associated with an `S3FileSystem` object.  The scene will be created successfully, and I can read data.  However, if I pass an `FSFile` instance with a `LocalFileSystem` object, scene creation fails with `ValueError`.

**To Reproduce**

```python
import satpy.readers
import s3fs
from fsspec.implementations.local import LocalFileSystem
s3_path = "noaa-goes16/ABI-L1b-RadC/2019/023/18/OR_ABI-L1b-RadC-M3C12_G16_s20190231817167_e20190231819545_c20190231819590.nc"
local_path = "/media/nas/x21308/abi/ABI-L1B-RadC/2019/023/18/OR_ABI-L1b-RadC-M3C12_G16_s20190231817167_e20190231819545_c20190231819590.nc"
lfs = LocalFileSystem()
s3fs = s3fs.S3FileSystem(anon=True)
fsf_s3 = satpy.readers.FSFile(s3_path, fs=s3fs)
fsf_local = satpy.readers.FSFile(local_path, fs=lfs)
satpy.Scene([fsf_s3], reader=["abi_l1b"])  # works
satpy.Scene([fsf_local], reader=["abi_l1b"])  # fails
```

There is an additional ValueError when the `FileHandler` tries to close the NetCDF file.  Somehow, trying to close it leads to opening it instead.

**Expected behaviour**

I expect that scene creation (and data reading) works with any `FSFile` instance.  I expect that no exceptions occur when deleting the file handler.

**Actual results**

(refrained from debug due to the verbosity of botocore and others)

```
Traceback (most recent call last):
  File "/home/gholl/checkouts/satpy/satpy/readers/abi_base.py", line 61, in nc
    nc = xr.open_dataset(f_obj,
  File "/data/gholl/miniconda3/envs/py39/lib/python3.9/site-packages/xarray/backends/api.py", line 496, in open_dataset
    backend_ds = backend.open_dataset(
  File "/data/gholl/miniconda3/envs/py39/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 549, in open_dataset
    store = NetCDF4DataStore.open(
  File "/data/gholl/miniconda3/envs/py39/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 353, in open
    raise ValueError(
ValueError: can only read bytes or file-like objects with engine='scipy' or 'h5netcdf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gholl/checkouts/protocode/mwe/pass-fsfile.py", line 11, in <module>
    satpy.Scene([fsf_local], reader=["abi_l1b"])  # fails
  File "/home/gholl/checkouts/satpy/satpy/scene.py", line 108, in __init__
    self._readers = self._create_reader_instances(filenames=filenames,
  File "/home/gholl/checkouts/satpy/satpy/scene.py", line 157, in _create_reader_instances
    return load_readers(filenames=filenames,
  File "/home/gholl/checkouts/satpy/satpy/readers/__init__.py", line 495, in load_readers
    reader_instance.create_filehandlers(
  File "/home/gholl/checkouts/satpy/satpy/readers/yaml_reader.py", line 606, in create_filehandlers
    filehandlers = self._new_filehandlers_for_filetype(filetype_info,
  File "/home/gholl/checkouts/satpy/satpy/readers/yaml_reader.py", line 594, in _new_filehandlers_for_filetype
    return list(filtered_iter)
  File "/home/gholl/checkouts/satpy/satpy/readers/yaml_reader.py", line 562, in filter_fh_by_metadata
    for filehandler in filehandlers:
  File "/home/gholl/checkouts/satpy/satpy/readers/yaml_reader.py", line 503, in _new_filehandler_instances
    yield filetype_cls(filename, filename_info, filetype_info, *req_fh, **fh_kwargs)
  File "/home/gholl/checkouts/satpy/satpy/readers/abi_base.py", line 51, in __init__
    self.nlines = self.nc['y'].size
  File "/data/gholl/miniconda3/envs/py39/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/home/gholl/checkouts/satpy/satpy/readers/abi_base.py", line 66, in nc
    nc = xr.open_dataset(f_obj,
  File "/data/gholl/miniconda3/envs/py39/lib/python3.9/site-packages/xarray/backends/api.py", line 496, in open_dataset
    backend_ds = backend.open_dataset(
  File "/data/gholl/miniconda3/envs/py39/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 549, in open_dataset
    store = NetCDF4DataStore.open(
  File "/data/gholl/miniconda3/envs/py39/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 353, in open
    raise ValueError(
ValueError: can only read bytes or file-like objects with engine='scipy' or 'h5netcdf'
Exception ignored in: <function NC_ABI_BASE.__del__ at 0x7f6e056fe160>
Traceback (most recent call last):
  File "/home/gholl/checkouts/satpy/satpy/readers/abi_base.py", line 291, in __del__
    self.nc.close()
  File "/data/gholl/miniconda3/envs/py39/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/home/gholl/checkouts/satpy/satpy/readers/abi_base.py", line 66, in nc
    nc = xr.open_dataset(f_obj,
  File "/data/gholl/miniconda3/envs/py39/lib/python3.9/site-packages/xarray/backends/api.py", line 496, in open_dataset
    backend_ds = backend.open_dataset(
  File "/data/gholl/miniconda3/envs/py39/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 549, in open_dataset
    store = NetCDF4DataStore.open(
  File "/data/gholl/miniconda3/envs/py39/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 353, in open
    raise ValueError(
ValueError: can only read bytes or file-like objects with engine='scipy' or 'h5netcdf'
```

**Environment Info:**
 - Satpy Version: v0.29.0-56-g700ddc73

**Additional context**

One might ask: why use FSFile for local files?  Answer: for reasons of abstraction. I ran into this when, for the purpose of testing, I was swapping a remote filesystem for a local one, but still passing an FSFile instance.  When this doesn't work, I can pass the file as a string rather than as an FSFile instance, but this involves additional complexity upstream.

**Comment by djhoese** [comment]
Hhhhmmm what is the S3-backed FSFile providing to xarray.open_dataset? Shouldn't it be a file-like object too just like the local file system?

**Comment by gerritholl** [comment]
If I pass a `LocalFileSystem()`, `xarray.open_dataset` is getting a `fsspec.implementations.local.LocalFileOpener`.  If I pass a s3 filesystem, it's getting a `fs3fs.core.S3File`.

(Incidentally, the `ValueError` is initially captured, which is why the exception occurs twice:

https://github.com/pytroll/satpy/blob/f736315178ebeb26a15a48302251cf39534ed143/satpy/readers/abi_base.py#L60-L69
)

**Comment by djhoese** [comment]
Ok so this try/except is for the different types of ABI files (l1b versus l2), but the two types of objects must be treated by xarray differently...weird.
