### ISSUE TITLE
Seviri L2 BUFR reader fails to read RSS Regional Instability Index and Atmospheric Motion Vectors

### ISSUE THREAD

**Issue by jacobbieker** [pytroll/satpy#1768]
**Describe the bug**
When loading a scene, giving SEVIRI BUFR filenames should work with the seviri_l2_bufr loader. Instead, it returns that it does not know how to load Regional Instability Index and Atmospheric Motion Vector BUFR files. 

**To Reproduce**

```python
from satpy import Scene
filenames = {}
filenames["seviri_l2_bufr"] = ["MSG3-SEVI-MSGRIIE-0101-0101-20200103134000.000000000Z-20200103134553-4732122.bfr", "MSG3-SEVI-MSGAMVE-0100-0100-20200101181500.000000000Z-20200101182035-4732126.bfr"]
scene = Scene(filenames=filenames)

```

**Expected behavior**
The BUFR files are loaded and can be interacted with, the same as the cloud mask product or other seviri files.

**Actual results**
Text output of actual results or error messages including full tracebacks if applicable.
```
[DEBUG: 2021-07-19 15:33:59 : satpy.readers.yaml_reader] Reading ('/home/jacob/anaconda3/envs/sat/lib/python3.9/site-packages/satpy/etc/readers/seviri_l2_bufr.yaml',)
[INFO: 2021-07-19 15:34:00 : gribapi.bindings] ecCodes library found using name 'eccodes'.
[WARNING: 2021-07-19 15:34:00 : satpy.readers.yaml_reader] No filenames found for reader: seviri_l2_bufr
[WARNING: 2021-07-19 15:34:00 : satpy.readers] Don't know how to open the following files: {'/run/media/jacob/T7/EUMETSAT/MSG3-SEVI-MSGAMVE-0100-0100-20200101181500.000000000Z-20200101182035-4732126.bfr', '/run/media/jacob/T7/EUMETSAT/MSG3-SEVI-MSGRIIE-0101-0101-20200103134000.000000000Z-20200103134553-4732122.bfr'}
Traceback (most recent call last):
  File "/home/jacob/Development/satflow/satflow/examples/derived_products.py", line 13, in <module>
    scene = Scene(filenames=filenames)
  File "/home/jacob/anaconda3/envs/sat/lib/python3.9/site-packages/satpy/scene.py", line 108, in __init__
    self._readers = self._create_reader_instances(filenames=filenames,
  File "/home/jacob/anaconda3/envs/sat/lib/python3.9/site-packages/satpy/scene.py", line 157, in _create_reader_instances
    return load_readers(filenames=filenames,
  File "/home/jacob/anaconda3/envs/sat/lib/python3.9/site-packages/satpy/readers/__init__.py", line 506, in load_readers
    raise ValueError("No supported files found")
ValueError: No supported files found
```

**Screenshots**

**Environment Info:**
 - OS: Linux - Manjaro
 - Satpy Version: 0.29.0
 - PyResample Version: 1.20.0
 - Readers and writers dependencies (when relevant):
```
Readers
=======
INFO:gribapi.bindings:ecCodes library found using name 'eccodes'.
abi_l1b:  ok
abi_l1b_scmi:  ok
abi_l2_nc:  ok
acspo:  cannot find module 'satpy.readers.acspo' (No module named 'netCDF4')
agri_l1:  cannot find module 'satpy.readers.agri_l1' (No module named 'h5py')
ahi_hrit:  ok
ahi_hsd:  ok
ahi_l1b_gridded_bin:  ok
ami_l1b:  cannot find module 'satpy.readers.ami_l1b' (No module named 'pyspectral')
amsr2_l1b:  cannot find module 'satpy.readers.amsr2_l1b' (No module named 'h5py')
amsr2_l2:  cannot find module 'satpy.readers.amsr2_l2' (No module named 'h5py')
amsr2_l2_gaasp:  ok
ascat_l2_soilmoisture_bufr:  ok
avhrr_l1b_aapp:  ok
avhrr_l1b_eps:  ok
avhrr_l1b_gaclac:  cannot find module 'satpy.readers.avhrr_l1b_gaclac' (No module named 'pygac')
avhrr_l1b_hrpt:  cannot find module 'satpy.readers.hrpt' (No module named 'geotiepoints')
avhrr_l1c_eum_gac_fdr_nc:  ok
caliop_l2_cloud:  cannot find module 'satpy.readers.caliop_l2_cloud' (No module named 'pyhdf')
clavrx:  cannot find module 'satpy.readers.clavrx' (No module named 'netCDF4')
cmsaf-claas2_l2_nc:  cannot find module 'satpy.readers.cmsaf_claas2' (No module named 'netCDF4')
electrol_hrit:  ok
fci_l1c_nc:  cannot find module 'satpy.readers.fci_l1c_nc' (No module named 'netCDF4')
fci_l2_nc:  ok
generic_image:  cannot find module 'satpy.readers.generic_image' (No module named 'rasterio')
geocat:  cannot find module 'satpy.readers.geocat' (No module named 'netCDF4')
ghrsst_l3c_sst:  cannot find module 'satpy.readers.ghrsst_l3c_sst' (cannot import name 'Dataset' from 'satpy.dataset' (/home/jacob/anaconda3/envs/sat/lib/python3.9/site-packages/satpy/dataset/__init__.py))
glm_l2:  ok
goes-imager_hrit:  ok
goes-imager_nc:  ok
gpm_imerg:  cannot find module 'satpy.readers.gpm_imerg' (No module named 'h5py')
grib:  cannot find module 'satpy.readers.grib' (No module named 'pygrib')
hsaf_grib:  cannot find module 'satpy.readers.hsaf_grib' (No module named 'pygrib')
hy2_scat_l2b_h5:  cannot find module 'satpy.readers.hy2_scat_l2b_h5' (No module named 'h5py')
iasi_l2:  cannot find module 'satpy.readers.iasi_l2' (No module named 'h5py')
iasi_l2_so2_bufr:  ok
jami_hrit:  ok
li_l2:  cannot find module 'satpy.readers.li_l2' (No module named 'h5netcdf')
maia:  cannot find module 'satpy.readers.maia' (No module named 'h5py')
mersi2_l1b:  cannot find module 'satpy.readers.mersi2_l1b' (No module named 'h5py')
mimicTPW2_comp:  cannot find module 'satpy.readers.mimic_TPW2_nc' (No module named 'netCDF4')
mirs:  ok
modis_l1b:  cannot find module 'satpy.readers.modis_l1b' (No module named 'pyhdf')
modis_l2:  cannot find module 'satpy.readers.modis_l2' (No module named 'pyhdf')
msi_safe:  cannot find module 'satpy.readers.msi_safe' (No module named 'glymur')
mtsat2-imager_hrit:  ok
mviri_l1b_fiduceo_nc:  ok
nucaps:  cannot find module 'satpy.readers.nucaps' (No module named 'netCDF4')
nwcsaf-geo:  ok
nwcsaf-msg2013-hdf5:  cannot find module 'satpy.readers.nwcsaf_msg2013_hdf5' (No module named 'h5py')
nwcsaf-pps_nc:  ok
olci_l1b:  ok
olci_l2:  ok
omps_edr:  cannot find module 'satpy.readers.omps_edr' (No module named 'h5py')
safe_sar_l2_ocn:  ok
sar-c_safe:  cannot find module 'satpy.readers.sar_c_safe' (No module named 'rasterio')
satpy_cf_nc:  ok
scatsat1_l2b:  cannot find module 'satpy.readers.scatsat1_l2b' (No module named 'h5py')
seviri_l1b_hrit:  ok
seviri_l1b_icare:  cannot find module 'satpy.readers.seviri_l1b_icare' (No module named 'pyhdf')
seviri_l1b_native:  ok
seviri_l1b_nc:  ok
seviri_l2_bufr:  ok
seviri_l2_grib:  ok
slstr_l1b:  ok
slstr_l2:  ok
smos_l2_wind:  cannot find module 'satpy.readers.smos_l2_wind' (No module named 'netCDF4')
tropomi_l2:  cannot find module 'satpy.readers.tropomi_l2' (No module named 'netCDF4')
vaisala_gld360:  ok
vii_l1b_nc:  cannot find module 'satpy.readers.vii_l1b_nc' (No module named 'netCDF4')
vii_l2_nc:  cannot find module 'satpy.readers.vii_l2_nc' (No module named 'netCDF4')
viirs_compact:  cannot find module 'satpy.readers.viirs_compact' (No module named 'h5py')
viirs_edr_active_fires:  cannot find module 'satpy.readers.viirs_edr_active_fires' (No module named 'netCDF4')
viirs_edr_flood:  cannot find module 'satpy.readers.viirs_edr_flood' (No module named 'pyhdf')
viirs_l1b:  cannot find module 'satpy.readers.viirs_l1b' (No module named 'netCDF4')
viirs_sdr:  cannot find module 'satpy.readers.viirs_sdr' (No module named 'h5py')
virr_l1b:  cannot find module 'satpy.readers.virr_l1b' (No module named 'h5py')

Writers
=======
awips_tiled:  ok
cf:  ok
geotiff:  cannot find module 'satpy.writers.geotiff' (No module named 'rasterio')
mitiff:  ok
ninjotiff:  cannot find module 'satpy.writers.ninjotiff' (No module named 'pyninjotiff')
simple_image:  ok

Extras
======
cartopy:  No module named 'cartopy'
geoviews:  No module named 'geoviews'
```

**Additional context**
I did this in a fresh conda environment with just satpy and eccodes installed.

**Comment by jacobbieker** [comment]
From poking around, it seems that possibly the Regional Instability Index files could be added with just a change to here? https://github.com/sfinkens/satpy/blob/e62eb9d60add9e5c1bb4ee1074bf189b5dcd099b/satpy/etc/readers/seviri_l2_bufr.yaml#L29-L34

**Comment by mraspaud** [comment]
Hi @jacobbieker , thanks for reporting this issue. Let me ping the people who know about this stuff, they will probably have better answers than me.

@ColinDuff @strandgren

**Comment by ColinDuff** [comment]
Hi @jacobbieker . The reader hasnt been configured to read AMV Bufr  and RII products yet. 
Our AMV product specialist has been looking into this already
RII we can have a look at. 

Colin

**Comment by jacobbieker** [comment]
Okay, thanks!

**Comment by matzech** [comment]
Hi! 

Is there an update how to read AMV with satpy?

**Comment by sjoro** [comment]
hi, @matzech 
@manucarran just opened a pull request for AMV L2 support https://github.com/pytroll/satpy/pull/2207
