### ISSUE TITLE
If satpy config path set multiple times, scene creation fails with ValueError: Satpy config option 'config_path' must be a list, not '<class 'str'>'

### ISSUE THREAD

**Issue by gerritholl** [pytroll/satpy#1836]
**Describe the bug**

When the environment variable `SATPY_CONFIG_PATH` is set multiple times with case differences, scene creation fails with `ValueError: Satpy config option 'config_path' must be a list, not '<class 'str'>'`

**To Reproduce**

```python
from satpy import Scene
sc_polar = Scene(filenames=[...], reader=["avhrr_l1b_aapp"])
```

Run like:

```bash
export SATPY_CONFIG_PATH=a:b
export SATPY_CONFIG_PATh=a:b
python mwe.py
```

**Expected behavior**

It should create the scene (or fail because it can't find the indicated file).

**Actual results**

```
Traceback (most recent call last):
  File "/data/gholl/checkouts/protocode/mwe/satpy-valueerror.py", line 2, in <module>
    sc_polar = Scene(filenames=[...], reader=["avhrr_l1b_aapp"])
  File "/data/gholl/checkouts/satpy/satpy/scene.py", line 108, in __init__
    self._readers = self._create_reader_instances(filenames=filenames,
  File "/data/gholl/checkouts/satpy/satpy/scene.py", line 157, in _create_reader_instances
    return load_readers(filenames=filenames,
  File "/data/gholl/checkouts/satpy/satpy/readers/__init__.py", line 475, in load_readers
    for idx, reader_configs in enumerate(configs_for_reader(reader)):
  File "/data/gholl/checkouts/satpy/satpy/readers/__init__.py", line 268, in configs_for_reader
    reader_configs = config_search_paths(
  File "/data/gholl/checkouts/satpy/satpy/_config.py", line 122, in config_search_paths
    search_dirs = get_config_path_safe()[::-1]
  File "/data/gholl/checkouts/satpy/satpy/_config.py", line 101, in get_config_path_safe
    raise ValueError("Satpy config option 'config_path' must be a "
ValueError: Satpy config option 'config_path' must be a list, not '<class 'str'>'
```

**Environment Info:**
 - OS: openSUSE 15.0
 - Satpy Version: 0.30.1.dev3+g12878178

**Additional context**

Ran into this accidentally, but somewhat surprised by the bug still.

**Comment by djhoese** [comment]
Slightly simpler use case (no need for filenames).

```python
from satpy.utils import check_satpy
check_satpy(readers='avhrr_l1b_aapp')
```

Are there any standards for case sensitivity for environment variables?

**Comment by djhoese** [comment]
Ok, this is caused due to the way `donfig` goes through all environment variables...

https://github.com/pytroll/donfig/blob/50874c1d9cc3f81845943170c6af14012eb1ff4f/donfig/config_obj.py#L203

It converts environment variable names to in-python/config names by just doing `lower()` on the name. So these two env vars in this test case are meant to be applied to the same config parameter. Although... :thinking: that still doesn't make sense why it would fail.

**Comment by djhoese** [comment]
Ah ok, so satpy manipulates the uppercase version of the environ dict directly:

https://github.com/pytroll/satpy/blob/12878178aeaccb85e0414f24f93ccefe06a6a03b/satpy/_config.py#L74-L86

Then checks the environment variables in donfig. So donfig sees the uppercase env var and parses it as a python literal just fine. Then it gets to the mixed case version, sees `a:b`, and just assumes it is a string. Because that mixed case version was found after the uppercase version, it overwrites the uppercase value and that's what gets passed on to satpy. Later on when Satpy is looking at the config path it says "wait, that's not right, this should be a list".

I'm not sure there is an easy way to fix this except to make donfig understand `:` separated lists...or make satpy do the `:` splitting logic for all environment variables that it understands. Perhaps a waste of time.

**Comment by djhoese** [comment]
I think I'm going to close this as a won't fix. I'm not sure how we can resolve this. If someone comes up with an idea then feel free to comment here or make a pull request with a fix.
