### ISSUE TITLE
Cannot save mode LA image storing scale and offset tags

### ISSUE THREAD

**Issue by gerritholl** [pytroll/satpy#1851]
**Describe the bug**

Saving a mode LA image while storing scale and offset tags fails with `ValueError`.

**To Reproduce**

```python
"""Test saving LA image with scale/offset tags."""

import xarray as xr
import numpy as np
from satpy import Scene
from satpy.utils import debug_on; debug_on()

arr = xr.DataArray(
    np.zeros((20, 10, 2), dtype="uint8"),
    dims=("y", "x", "bands"),
    coords={"bands": ["L", "A"]})
sc = Scene()
sc["foo"] = arr
sc.save_dataset("foo", filename="/tmp/test.tif", include_scale_offset=True, writer="geotiff")
#sc.save_dataset("foo", filename="/tmp/test.tif", scale_offset_tags=("scale", "offset"), writer="geotiff")
```

(NB: the two versions of `save_dataset` are to accommodate for https://github.com/pytroll/trollimage/pull/85)

**Expected behavior**

I expect an LA image to be written with scale and offset written in the metadata.  @mraspaud has reported that this works (source: personal communication on pytroll slack).

**Actual results**

```
[DEBUG: 2021-10-12 14:09:38 : satpy.writers] Reading ['/data/gholl/checkouts/satpy/satpy/etc/writers/geotiff.yaml']
[DEBUG: 2021-10-12 14:09:38 : trollimage.xrimage] Convert image data to dask array
[DEBUG: 2021-10-12 14:09:38 : satpy.writers] Enhancement configuration options: [{'name': 'stretch', 'method': <function stretch at 0x7fd380fb0a60>, 'kwargs': {'stretch': 'linear'}}]
[DEBUG: 2021-10-12 14:09:38 : trollimage.xrimage] Applying stretch linear with parameters {}
[DEBUG: 2021-10-12 14:09:38 : trollimage.xrimage] Perform a linear contrast stretch.
[DEBUG: 2021-10-12 14:09:38 : trollimage.xrimage] Calculate the histogram quantiles: 
[DEBUG: 2021-10-12 14:09:38 : trollimage.xrimage] Left and right quantiles: 0.005 0.005
/data/gholl/checkouts/trollimage/trollimage/xrimage.py:485: DeprecationWarning: include_scale_offset_tags is deprecated, please use scale_offset_tags to indicate tag labels
  warnings.warn(
[INFO: 2021-10-12 14:09:38 : trollimage.xrimage] Couldn't create geotransform
[DEBUG: 2021-10-12 14:09:38 : rasterio.env] Entering env context: <rasterio.env.Env object at 0x7fd380e58a60>
[DEBUG: 2021-10-12 14:09:38 : rasterio.env] Starting outermost env
[DEBUG: 2021-10-12 14:09:38 : rasterio.env] No GDAL environment exists
[DEBUG: 2021-10-12 14:09:38 : rasterio.env] New GDAL environment <rasterio._env.GDALEnv object at 0x7fd380e883d0> created
[DEBUG: 2021-10-12 14:09:38 : rasterio._env] GDAL_DATA found in environment.
[DEBUG: 2021-10-12 14:09:38 : rasterio._env] PROJ_LIB found in environment.
[DEBUG: 2021-10-12 14:09:38 : rasterio._env] Started GDALEnv: self=<rasterio._env.GDALEnv object at 0x7fd380e883d0>.
[DEBUG: 2021-10-12 14:09:38 : rasterio.env] Entered env context: <rasterio.env.Env object at 0x7fd380e58a60>
[DEBUG: 2021-10-12 14:09:38 : rasterio._io] Path: UnparsedPath(path='/tmp/test.tif'), mode: w, driver: GTiff
[DEBUG: 2021-10-12 14:09:38 : rasterio._io] Option: ('COMPRESS', b'DEFLATE')
[DEBUG: 2021-10-12 14:09:38 : rasterio._io] Option: ('ZLEVEL', b'6')
/data/gholl/mambaforge/envs/py39/lib/python3.9/site-packages/rasterio/__init__.py:230: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix be returned.
  s = writer(path, mode, driver=driver,
[DEBUG: 2021-10-12 14:09:38 : rasterio._base] Nodata success: 0, Nodata value: -10000000000.000000
[DEBUG: 2021-10-12 14:09:38 : rasterio._base] Nodata success: 0, Nodata value: -10000000000.000000
[DEBUG: 2021-10-12 14:09:38 : rasterio.env] Exiting env context: <rasterio.env.Env object at 0x7fd380e58a60>
[DEBUG: 2021-10-12 14:09:38 : rasterio.env] Cleared existing <rasterio._env.GDALEnv object at 0x7fd380e883d0> options
[DEBUG: 2021-10-12 14:09:38 : rasterio._env] Stopped GDALEnv <rasterio._env.GDALEnv object at 0x7fd380e883d0>.
[DEBUG: 2021-10-12 14:09:38 : rasterio.env] Exiting outermost env
[DEBUG: 2021-10-12 14:09:38 : rasterio.env] Exited env context: <rasterio.env.Env object at 0x7fd380e58a60>
[DEBUG: 2021-10-12 14:09:39 : trollimage.xrimage] Interval: left=<xarray.DataArray (bands: 2)>
array([0., 0.])
Coordinates:
    quantile  float64 0.005
Dimensions without coordinates: bands, right=<xarray.DataArray (bands: 2)>
array([0., 0.])
Coordinates:
    quantile  float64 0.995
Dimensions without coordinates: bands
/data/gholl/mambaforge/envs/py39/lib/python3.9/site-packages/dask/core.py:121: RuntimeWarning: divide by zero encountered in true_divide
  return func(*(_execute_task(a, cache) for a in args))
/data/gholl/mambaforge/envs/py39/lib/python3.9/site-packages/dask/core.py:121: RuntimeWarning: invalid value encountered in multiply
  return func(*(_execute_task(a, cache) for a in args))
Traceback (most recent call last):
  File "/data/gholl/checkouts/protocode/save-la-tags.py", line 14, in <module>
    sc.save_dataset("foo", filename="/tmp/test.tif", include_scale_offset=True, writer="geotiff")
  File "/data/gholl/checkouts/satpy/satpy/scene.py", line 1037, in save_dataset
    return writer.save_dataset(self[dataset_id],
  File "/data/gholl/checkouts/satpy/satpy/writers/__init__.py", line 809, in save_dataset
    return self.save_image(img, filename=filename, compute=compute, fill_value=fill_value, **kwargs)
  File "/data/gholl/checkouts/satpy/satpy/writers/geotiff.py", line 222, in save_image
    return img.save(filename, fformat='tif', fill_value=fill_value,
  File "/data/gholl/checkouts/trollimage/trollimage/xrimage.py", line 419, in save
    return self.rio_save(filename, fformat=fformat,
  File "/data/gholl/checkouts/trollimage/trollimage/xrimage.py", line 590, in rio_save
    res = da.store(*to_store)
  File "/data/gholl/mambaforge/envs/py39/lib/python3.9/site-packages/dask/array/core.py", line 1043, in store
    compute_as_if_collection(Array, store_dsk, store_keys, **kwargs)
  File "/data/gholl/mambaforge/envs/py39/lib/python3.9/site-packages/dask/base.py", line 315, in compute_as_if_collection
    return schedule(dsk2, keys, **kwargs)
  File "/data/gholl/mambaforge/envs/py39/lib/python3.9/site-packages/dask/threaded.py", line 79, in get
    results = get_async(
  File "/data/gholl/mambaforge/envs/py39/lib/python3.9/site-packages/dask/local.py", line 517, in get_async
    raise_exception(exc, tb)
  File "/data/gholl/mambaforge/envs/py39/lib/python3.9/site-packages/dask/local.py", line 325, in reraise
    raise exc
  File "/data/gholl/mambaforge/envs/py39/lib/python3.9/site-packages/dask/local.py", line 223, in execute_task
    result = _execute_task(task, data)
  File "/data/gholl/mambaforge/envs/py39/lib/python3.9/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/data/gholl/mambaforge/envs/py39/lib/python3.9/site-packages/dask/array/core.py", line 4021, in store_chunk
    return load_store_chunk(x, out, index, lock, return_stored, False)
  File "/data/gholl/mambaforge/envs/py39/lib/python3.9/site-packages/dask/array/core.py", line 4008, in load_store_chunk
    out[index] = x
  File "/data/gholl/checkouts/trollimage/trollimage/xrimage.py", line 162, in __setitem__
    kwargs = {self.name: item.item()}
ValueError: can only convert an array of size 1 to a Python scalar
```

**Environment Info:**
 - OS: openSUSE 15.3
 - Satpy Version: `v0.30.1-3-g47fb3bc3`
 - trollimage Version: `v1.15.1-9-g7246882`

**Additional context**

I wouldn't actually expect it to work.  The scale and offset are only normally meaningful for the L-band, but the tags are global.  The writer encounters two scales and offsets, for the L and the A band, tries to write those two values as a scalar, and fails.  I'm curious to see why it works in Martins case.

**Comment by gerritholl** [comment]
Yes, RGB/A images also fail.  However, I think the problem is more pressing for LA images, because, as for L images, it's reasonable to map the pixel values to a physical interpretation.  I have a hard time imagining that people would want to map the pixel values of an RGB/A image to a physical interpretation, however; and if they don't, then I don't know why they would need a scale factor and offset interpretation.

**Comment by djhoese** [comment]
ok so the two things (as far as I can tell from this discussion) that need to be fixed are:

1. Don't let stretch be applied to Alpha unless the stretch parameters have multiple values (`min_stretch=[0, 0]` for an LA dataset).
2. Produce a warning when including factor/offset tags if they have multiple values and say that the tags can't be saved. Optionally switch to per-band factor/offset and also produce a warning, but this may be a bit too magical.
