### ISSUE TITLE
Computing FCI datasets on resampled scene may fail if original scene gone

### ISSUE THREAD

**Issue by gerritholl** [pytroll/satpy#1861]
**Describe the bug**

Computing datasets from a resampled FCI scene normally fails with a `RuntimeError: NetCDF: Not a valid ID` if the original scene is no longer available.

**To Reproduce**

```python
import satpy
from satpy.utils import debug_on; debug_on()

def get_resampled_scene():
    sc = satpy.Scene(
            filenames=["/data/gholl/cache/satpy-demo-data/fci/test_data/UNCOMPRESSED/NOMINAL/W_XX-EUMETSAT-Darmstadt,IMG+SAT,MTI1+FCI-1C-RRAD-FDHSI-FD--CHK-BODY---NC4E_C_EUMT_20130804120515_GTT_DEV_20130804120000_20130804120015_N__T_0073_0001.nc"],
            reader="fci_l1c_nc")
    sc.load(["ir_87"])
    ls = sc.resample("mtg_fci_fdss_2km")
    return ls

ls = get_resampled_scene()
ls["ir_87"].compute()
```
If we retain the scene object (such as by returning it), the sample works:

```python
import satpy
from satpy.utils import debug_on; debug_on()

def get_resampled_scene():
    sc = satpy.Scene(
            filenames=["/data/gholl/cache/satpy-demo-data/fci/test_data/UNCOMPRESSED/NOMINAL/W_XX-EUMETSAT-Darmstadt,IMG+SAT,MTI1+FCI-1C-RRAD-FDHSI-FD--CHK-BODY---NC4E_C_EUMT_20130804120515_GTT_DEV_20130804120000_20130804120015_N__T_0073_0001.nc"],
            reader="fci_l1c_nc")
    sc.load(["ir_87"])
    ls = sc.resample("eurol")
    return (sc, ls)

(sc, ls) = get_resampled_scene()
ls["ir_87"].compute()
```

**Expected behavior**

I expect computation to be completed without errors.

**Actual results**

For the version failing with RuntimeError, the full output including traceback is:

```
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Reading ('/data/gholl/checkouts/satpy/satpy/etc/readers/fci_l1c_nc.yaml',)
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Assigning to fci_l1c_nc: ['/data/gholl/cache/satpy-demo-data/fci/test_data/UNCOMPRESSED/NOMINAL/W_XX-EUMETSAT-Darmstadt,IMG+SAT,MTI1+FCI-1C-RRAD-FDHSI-FD--CHK-BODY---NC4E_C_EUMT_20130804120515_GTT_DEV_20130804120000_20130804120015_N__T_0073_0001.nc']
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.fci_l1c_nc] Reading: /data/gholl/cache/satpy-demo-data/fci/test_data/UNCOMPRESSED/NOMINAL/W_XX-EUMETSAT-Darmstadt,IMG+SAT,MTI1+FCI-1C-RRAD-FDHSI-FD--CHK-BODY---NC4E_C_EUMT_20130804120515_GTT_DEV_20130804120000_20130804120015_N__T_0073_0001.nc
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.fci_l1c_nc] Start: 2013-08-04 12:00:00
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.fci_l1c_nc] End: 2013-08-04 12:00:15
[DEBUG: 2021-10-22 16:33:18 : satpy.composites.config_loader] Looking for composites config file fci.yaml
[DEBUG: 2021-10-22 16:33:18 : satpy.composites.config_loader] Looking for composites config file visir.yaml
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.fci_l1c_nc] Reading ir_87 from /data/gholl/cache/satpy-demo-data/fci/test_data/UNCOMPRESSED/NOMINAL/W_XX-EUMETSAT-Darmstadt,IMG+SAT,MTI1+FCI-1C-RRAD-FDHSI-FD--CHK-BODY---NC4E_C_EUMT_20130804120515_GTT_DEV_20130804120000_20130804120015_N__T_0073_0001.nc
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.fci_l1c_nc] Channel ir_87 resolution: 5568
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.fci_l1c_nc] Row/Cols: 139 / 5568
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.fci_l1c_nc] Calculated area extent: (-5567999.994200589, -5289999.994489993, 5567999.994206558, -5567999.994200589)
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 2
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 3
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 4
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 5
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 6
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 7
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 8
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 9
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 10
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 11
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 12
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 13
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 14
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 15
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 16
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 17
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 18
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 19
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 20
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 21
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 22
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 23
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 24
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 25
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 26
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 27
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 28
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 29
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 30
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 31
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 32
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 33
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 34
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 35
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 36
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 37
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 38
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 39
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 40
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Requested orientation for Dataset ir_87 is 'native' (default). No flipping is applied.
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.fci_l1c_nc] Reading ir_87_pixel_quality from /data/gholl/cache/satpy-demo-data/fci/test_data/UNCOMPRESSED/NOMINAL/W_XX-EUMETSAT-Darmstadt,IMG+SAT,MTI1+FCI-1C-RRAD-FDHSI-FD--CHK-BODY---NC4E_C_EUMT_20130804120515_GTT_DEV_20130804120000_20130804120015_N__T_0073_0001.nc
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 2
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 3
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 4
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 5
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 6
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 7
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 8
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 9
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 10
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 11
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 12
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 13
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 14
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 15
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 16
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 17
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 18
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 19
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 20
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 21
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 22
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 23
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 24
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 25
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 26
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 27
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 28
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 29
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 30
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 31
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 32
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 33
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 34
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 35
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 36
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 37
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 38
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 39
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Padding to full disk with segment nr. 40
[DEBUG: 2021-10-22 16:33:18 : satpy.readers.yaml_reader] Requested orientation for Dataset None is 'native' (default). No flipping is applied.
[DEBUG: 2021-10-22 16:33:19 : satpy.scene] Resampling DataID(name='ir_87', wavelength=WavelengthRange(min=8.3, central=8.7, max=9.1, unit='µm'), resolution=2000, calibration=<calibration.brightness_temperature>, modifiers=())
[DEBUG: 2021-10-22 16:33:19 : pyresample.geometry] Cannot determine appropriate slicing. Data and projection area do not overlap.
[INFO: 2021-10-22 16:33:19 : satpy.scene] Not reducing data before resampling.
[INFO: 2021-10-22 16:33:19 : satpy.resample] Using default KDTree resampler
/data/gholl/mambaforge/envs/py39/lib/python3.9/site-packages/numpy/lib/function_base.py:1281: RuntimeWarning: invalid value encountered in subtract
  a = op(a[slice1], a[slice2])
/data/gholl/mambaforge/envs/py39/lib/python3.9/site-packages/numpy/lib/function_base.py:1281: RuntimeWarning: invalid value encountered in subtract
  a = op(a[slice1], a[slice2])
[DEBUG: 2021-10-22 16:33:19 : satpy.resample] Check if ./resample_lut-64f14211c3b0e156f5b1eb6e5b612e402d6820f9.npz exists
[DEBUG: 2021-10-22 16:33:19 : satpy.resample] Computing kd-tree parameters
/data/gholl/checkouts/pyresample/pyresample/kd_tree.py:968: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  radius=self.radius_of_influence, dtype=np.int,
[DEBUG: 2021-10-22 16:33:20 : satpy.resample] Resampling None
[DEBUG: 2021-10-22 16:33:20 : satpy.scene] Resampling DataID(name='ir_87_pixel_quality', resolution=2000, modifiers=())
[DEBUG: 2021-10-22 16:33:20 : pyresample.geometry] Cannot determine appropriate slicing. Data and projection area do not overlap.
[INFO: 2021-10-22 16:33:20 : satpy.scene] Not reducing data before resampling.
/data/gholl/mambaforge/envs/py39/lib/python3.9/site-packages/pyproj/crs/crs.py:1256: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  return self._crs.to_proj4(version=version)
[DEBUG: 2021-10-22 16:33:20 : satpy.resample] Check if ./resample_lut-64f14211c3b0e156f5b1eb6e5b612e402d6820f9.npz exists
[DEBUG: 2021-10-22 16:33:20 : satpy.resample] Computing kd-tree parameters
/data/gholl/checkouts/pyresample/pyresample/kd_tree.py:968: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  radius=self.radius_of_influence, dtype=np.int,
[DEBUG: 2021-10-22 16:33:20 : satpy.resample] Resampling pixel_quality
Traceback (most recent call last):
  File "/data/gholl/checkouts/protocode/mwe/gc-sc-does-no-compute.py", line 16, in <module>
    ls["ir_87"].compute()
  File "/data/gholl/mambaforge/envs/py39/lib/python3.9/site-packages/xarray/core/dataarray.py", line 955, in compute
    return new.load(**kwargs)
  File "/data/gholl/mambaforge/envs/py39/lib/python3.9/site-packages/xarray/core/dataarray.py", line 929, in load
    ds = self._to_temp_dataset().load(**kwargs)
  File "/data/gholl/mambaforge/envs/py39/lib/python3.9/site-packages/xarray/core/dataset.py", line 865, in load
    evaluated_data = da.compute(*lazy_data.values(), **kwargs)
  File "/data/gholl/mambaforge/envs/py39/lib/python3.9/site-packages/dask/base.py", line 570, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/data/gholl/mambaforge/envs/py39/lib/python3.9/site-packages/dask/threaded.py", line 79, in get
    results = get_async(
  File "/data/gholl/mambaforge/envs/py39/lib/python3.9/site-packages/dask/local.py", line 517, in get_async
    raise_exception(exc, tb)
  File "/data/gholl/mambaforge/envs/py39/lib/python3.9/site-packages/dask/local.py", line 325, in reraise
    raise exc
  File "/data/gholl/mambaforge/envs/py39/lib/python3.9/site-packages/dask/local.py", line 223, in execute_task
    result = _execute_task(task, data)
  File "/data/gholl/mambaforge/envs/py39/lib/python3.9/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/data/gholl/mambaforge/envs/py39/lib/python3.9/site-packages/dask/core.py", line 121, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/data/gholl/mambaforge/envs/py39/lib/python3.9/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/data/gholl/mambaforge/envs/py39/lib/python3.9/site-packages/dask/core.py", line 121, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/data/gholl/mambaforge/envs/py39/lib/python3.9/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/data/gholl/mambaforge/envs/py39/lib/python3.9/site-packages/dask/array/core.py", line 100, in getter
    c = a[b]
  File "src/netCDF4/_netCDF4.pyx", line 4382, in netCDF4._netCDF4.Variable.__getitem__
  File "src/netCDF4/_netCDF4.pyx", line 4070, in netCDF4._netCDF4.Variable.shape.__get__
  File "src/netCDF4/_netCDF4.pyx", line 4018, in netCDF4._netCDF4.Variable._getdims
  File "src/netCDF4/_netCDF4.pyx", line 1927, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: Not a valid ID
```

**Environment Info:**
 - OS: openSUSE Leap 15.3
 - Satpy Version: v0.30.1-47-ga067057d
 - PyResample Version: v1.21.1-96-gae3e7f8

**Additional context**

An earlier version of this issue stated that loading works if `pad_data=True`, but this was only the case if resampling to an area not covered by the loaded files.

I found this when working on #1764, which is affected by this bug.

There was previously an issue in which the `NetCDF4FileHandler` was potentially causing issues with closed file handles, see https://github.com/pytroll/satpy/issues/758.

**Comment by gerritholl** [comment]
The problem appears hard to reproduce with recent versions of satpy:

* v0.43: fails always
* v0.44: fails or succeeds
* v0.45: fails or succeeds
* v0.46 onward: succeeds always?

I can't figure out when it changed between v0.43 and v0.44.  There was no work done on the FCI reader or the `NetCDF4BaseHandler` between those versions.  Between v0.45 and v0.46 there was work done only on FCI L2.  Maybe it's due to a dependency.

**Comment by guidocioni** [comment]
I still have this error, probably because as @ameraner I'm doing this

```python
def plot_function(data):
    ....
    scn = scn.resample(area)
    ....
```

However I only get this error when I call `plot_function` in a parallelized way, i.e. 

```python
process_map(plot_data, it, max_workers=2, chunksize=1, disable=True)
```

If I call the function directly on every chunk of the iterator `it` I don't get the issue...

What is the best workaround currently? BTW I'm on Satpy 0.51.0

**Comment by guidocioni** [comment]
The following awful workaround seems to work...

```python
readers = scn._readers
scn = scn.resample(area)
scn._readers = readers
```

**Comment by djhoese** [comment]
@guidocioni Why not assign the resampled Scene to a new variable name? Something simple like `scn2 = scn.resample` should work, right? Are you using the FCI reader?

**Comment by guidocioni** [comment]
> @guidocioni Why not assign the resampled Scene to a new variable name? Something simple like `scn2 = scn.resample` should work, right? Are you using the FCI reader?

Because in my function I have different use cases and not having scn change name is easier (sometimes I resample, sometimes I don't).

**Comment by strandgren** [comment]
You can do something like this:
```
scn_org = scn
scn = scn.resample()
```
also not very beautiful, but it lets you keep the name. We use this as a work-around in some of our tools.

**Comment by guidocioni** [comment]
Be aware that this is happening also on the latest satpy version and not necessarily using FCI data. 

This code

```python
goes16_scene = Scene(reader="abi_l1b", filenames=sorted(glob("/tmp/noaa-goes16/ABI-L1b-RadF/2025/088/10/*.nc")))
goes16_scene.load(["natural_color"])
print(goes16_scene.available_composite_names())
scn_goes_r = goes16_scene.resample('worldeqc30km', radius_of_influence=5e4, reduce_data=False)
print(scn_goes_r.available_composite_names())
```

outputs

```
['24h_microphysics', ..., 'water_vapors2']
[]
```

while this code

```python
goes16_scene = Scene(reader="abi_l1b", filenames=sorted(glob("/tmp/noaa-goes16/ABI-L1b-RadF/2025/088/10/*.nc")))
goes16_scene.load(["natural_color"])
print(goes16_scene.available_composite_names())
scn_goes_r = goes16_scene.resample('worldeqc30km', radius_of_influence=5e4, reduce_data=False)
scn_goes_r._readers = goes16_scene._readers
print(scn_goes_r.available_composite_names())
```

correctly outputs 

```
['24h_microphysics', ..., 'water_vapors2']
['24h_microphysics', ..., 'water_vapors2']
```

Is this expected even when not overwriting the original scene??

**Comment by djhoese** [comment]
Yes. The readers are no longer available after resampling by design. Doing a load of reader datasets (and composites based on them) from a resampled scene does not make sense as the areas would not match what is in the scene already.

**Comment by djhoese** [comment]
Do you have an issue specific to this ABI natural color case? After resampling you should be able to save the composite or access it with bracket syntax (`resamp_scn["natural_color"]`).

**Comment by guidocioni** [comment]
> Do you have an issue specific to this ABI natural color case? After resampling you should be able to save the composite or access it with bracket syntax (`resamp_scn["natural_color"]`).

You're right, I think I mixed up the issues. I can indeed access the composite in bracket syntax after resampling, even without copying the readers, and it seems to also export the composite in SEVIRI. In GOES I never managed to get to the end probably because it's just too much data :)
