### ISSUE TITLE
Loading composites without file handlers fails with KeyError

### ISSUE THREAD

**Issue by gerritholl** [pytroll/satpy#1898]
**Describe the bug**

Trying to load a composite without the KeyError present fails with `KeyError`.  This is essentially identical to #1747, but that one was a feature request that I thought had been fixed by #1747 and indeed I thought I had tested it at the time.  Considering that GitHub claims that the feature request #1747 was closed by #1797, I'm now filing this as a bug report.  Using current satpy main, I (still) cannot load composites when the file handlers aren't available.

**To Reproduce**

```python
from satpy import Scene, MultiScene
from satpy.utils import debug_on; debug_on()

base = "/media/nas/x21308/scratch/prob-glm-abi/"

abi_file = base + "OR_ABI-L1b-RadF-M6C14_G16_s19000010000000_e19000010005000_c20403662359590.nc"
glm_file = base + "OR_GLM-L2-GLMF-M3_G16_s19000010000000_e19000010001000_c20403662359590.nc"

sc_abi = Scene(filenames=[abi_file], reader="abi_l1b")
sc_abi.load(["C14"])
sc_glm = Scene(filenames=[glm_file], reader="glm_l2")
sc_glm.load(["flash_extent_density"])
sc_both = Scene()
sc_both["C14"] = sc_abi["C14"]
sc_both["flash_extent_density"] = sc_glm["flash_extent_density"]
sc_both.load(["C14_flash_extent_density"])
```

These are synthetic test files, but loading the individual datasets works, so the necessary data are there.  I will test with real data tomorrow.

**Expected behaviour**

I expect to load the composite `C14_flash_extent_density`.  All prerequisites are present.

**Actual results**

Loading the composite fails with `KeyError: "Unknown datasets: {DataQuery(name='C14_flash_extent_density')}"`.  Before that, there are various warning messages `No composite config found called l.yaml`, `No composite config found called i.yaml`, `No composite config found called g.yaml`, which corresponds to the letters of `abi` and `glm` interpreted as if a string is interpreted as a list.

```
[DEBUG: 2021-11-24 18:42:01 : satpy.readers.yaml_reader] Reading ('/data/gholl/checkouts/satpy/satpy/etc/readers/abi_l1b.yaml',)
[DEBUG: 2021-11-24 18:42:01 : satpy.readers.yaml_reader] Assigning to abi_l1b: ['/media/nas/x21308/scratch/prob-glm-abi/OR_ABI-L1b-RadF-M6C14_G16_s19000010000000_e19000010005000_c20403662359590.nc']
[DEBUG: 2021-11-24 18:42:01 : satpy.composites.config_loader] Looking for composites config file abi.yaml
[DEBUG: 2021-11-24 18:42:01 : satpy.composites.config_loader] Looking for composites config file visir.yaml
[DEBUG: 2021-11-24 18:42:01 : satpy.readers.abi_l1b] Reading in get_dataset C14.
[DEBUG: 2021-11-24 18:42:01 : satpy.readers.yaml_reader] Reading ('/data/gholl/checkouts/satpy/satpy/etc/readers/glm_l2.yaml',)
[DEBUG: 2021-11-24 18:42:01 : satpy.readers.yaml_reader] Assigning to glm_l2: ['/media/nas/x21308/scratch/prob-glm-abi/OR_GLM-L2-GLMF-M3_G16_s19000010000000_e19000010001000_c20403662359590.nc']
[DEBUG: 2021-11-24 18:42:01 : satpy.composites.config_loader] Looking for composites config file glm.yaml
[DEBUG: 2021-11-24 18:42:01 : satpy.composites.config_loader] Looking for composites config file visir.yaml
[DEBUG: 2021-11-24 18:42:01 : satpy.readers.glm_l2] Reading in get_dataset flash_extent_density.
[DEBUG: 2021-11-24 18:42:01 : satpy.composites.config_loader] Looking for composites config file l.yaml
[DEBUG: 2021-11-24 18:42:01 : satpy.composites.config_loader] No composite config found called l.yaml
[DEBUG: 2021-11-24 18:42:01 : satpy.composites.config_loader] Looking for composites config file i.yaml
[DEBUG: 2021-11-24 18:42:01 : satpy.composites.config_loader] No composite config found called i.yaml
[DEBUG: 2021-11-24 18:42:01 : satpy.composites.config_loader] Looking for composites config file m.yaml
[DEBUG: 2021-11-24 18:42:01 : satpy.composites.config_loader] No composite config found called m.yaml
[DEBUG: 2021-11-24 18:42:01 : satpy.composites.config_loader] Looking for composites config file g.yaml
[DEBUG: 2021-11-24 18:42:01 : satpy.composites.config_loader] No composite config found called g.yaml
[DEBUG: 2021-11-24 18:42:01 : satpy.composites.config_loader] Looking for composites config file b.yaml
[DEBUG: 2021-11-24 18:42:01 : satpy.composites.config_loader] No composite config found called b.yaml
[DEBUG: 2021-11-24 18:42:01 : satpy.composites.config_loader] Looking for composites config file a.yaml
[DEBUG: 2021-11-24 18:42:01 : satpy.composites.config_loader] No composite config found called a.yaml
Traceback (most recent call last):
  File "/data/gholl/checkouts/satpy/satpy/scene.py", line 1247, in _update_dependency_tree
    self._dependency_tree.populate_with_keys(needed_datasets, query)
  File "/data/gholl/checkouts/satpy/satpy/dependency_tree.py", line 256, in populate_with_keys
    raise MissingDependencies(unknown_datasets, "Unknown datasets:")
satpy.node.MissingDependencies: Unknown datasets: {DataQuery(name='C14_flash_extent_density')}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/gholl/checkouts/protocode/multiscene-multisensor-woes.py", line 16, in <module>
    sc_both.load(["C14_flash_extent_density"])
  File "/data/gholl/checkouts/satpy/satpy/scene.py", line 1235, in load
    self._update_dependency_tree(needed_datasets, query)
  File "/data/gholl/checkouts/satpy/satpy/scene.py", line 1249, in _update_dependency_tree
    raise KeyError(str(err))
KeyError: "Unknown datasets: {DataQuery(name='C14_flash_extent_density')}"
```

**Environment Info:**
 - Satpy Version: satpy-0.31.1.dev54+gef301b09

**Additional context**

I will try with real data and possibly fix my synthetic test data, but the composite-searching for single-letter files looks suspicious.

**Comment by djhoese** [comment]
Wow, this is bad that our tests didn't catch this.

**Comment by djhoese** [comment]
Right before the final load call can you do `print(sc_both.sensor_names)`?

**Comment by gerritholl** [comment]
`print(sc_both.sensor_names)` gives `{'g', 'm', 'i', 'a', 'b', 'l'}`

**Comment by gerritholl** [comment]
Just to confirm it's not due to some oddity in my test data, I tried with real data, and the result is the same.

Code:

```python
from satpy import Scene, MultiScene
from satpy.utils import debug_on; debug_on()

glm_file = "/media/nas/x21308/GLM-processed/C/1min/2021/06/02/00/OR_GLM-L2-GLMC-M3_G16_s20211530000200_e20211530001200_c20211932137440.nc"
abi_file = "/media/nas/x21308/abi/G16_ABI_CONUS_2021153/00/OR_ABI-L1b-RadC-M6C14_G16_s20211530001159_e20211530003532_c20211530003595.nc"

sc_abi = Scene(filenames=[abi_file], reader="abi_l1b")
sc_abi.load(["C14"])
sc_glm = Scene(filenames=[glm_file], reader="glm_l2")
sc_glm.load(["flash_extent_density"])
sc_both = Scene()
sc_both["C14"] = sc_abi["C14"]
sc_both["flash_extent_density"] = sc_glm["flash_extent_density"]
print(sc_both.sensor_names)
sc_both.load(["C14_flash_extent_density"])
```

Result:

```
[DEBUG: 2021-11-25 16:58:39 : satpy.readers.yaml_reader] Reading ('/data/gholl/checkouts/satpy/satpy/etc/readers/abi_l1b.yaml',)
[DEBUG: 2021-11-25 16:58:39 : satpy.readers.yaml_reader] Assigning to abi_l1b: ['/media/nas/x21308/abi/G16_ABI_CONUS_2021153/00/OR_ABI-L1b-RadC-M6C14_G16_s20211530001159_e20211530003532_c20211530003595.nc']
[DEBUG: 2021-11-25 16:58:39 : satpy.composites.config_loader] Looking for composites config file abi.yaml
[DEBUG: 2021-11-25 16:58:39 : satpy.composites.config_loader] Looking for composites config file visir.yaml
[DEBUG: 2021-11-25 16:58:39 : satpy.readers.abi_l1b] Reading in get_dataset C14.
[DEBUG: 2021-11-25 16:58:39 : satpy.readers.yaml_reader] Reading ('/data/gholl/checkouts/satpy/satpy/etc/readers/glm_l2.yaml',)
[DEBUG: 2021-11-25 16:58:39 : satpy.readers.yaml_reader] Assigning to glm_l2: ['/media/nas/x21308/GLM-processed/C/1min/2021/06/02/00/OR_GLM-L2-GLMC-M3_G16_s20211530000200_e20211530001200_c20211932137440.nc']
[DEBUG: 2021-11-25 16:58:39 : satpy.composites.config_loader] Looking for composites config file glm.yaml
[DEBUG: 2021-11-25 16:58:39 : satpy.composites.config_loader] Looking for composites config file visir.yaml
[DEBUG: 2021-11-25 16:58:39 : satpy.readers.glm_l2] Reading in get_dataset flash_extent_density.
{'g', 'b', 'a', 'm', 'i', 'l'}
[DEBUG: 2021-11-25 16:58:39 : satpy.composites.config_loader] Looking for composites config file g.yaml
[DEBUG: 2021-11-25 16:58:39 : satpy.composites.config_loader] No composite config found called g.yaml
[DEBUG: 2021-11-25 16:58:39 : satpy.composites.config_loader] Looking for composites config file b.yaml
[DEBUG: 2021-11-25 16:58:39 : satpy.composites.config_loader] No composite config found called b.yaml
[DEBUG: 2021-11-25 16:58:39 : satpy.composites.config_loader] Looking for composites config file a.yaml
[DEBUG: 2021-11-25 16:58:39 : satpy.composites.config_loader] No composite config found called a.yaml
[DEBUG: 2021-11-25 16:58:39 : satpy.composites.config_loader] Looking for composites config file m.yaml
[DEBUG: 2021-11-25 16:58:39 : satpy.composites.config_loader] No composite config found called m.yaml
[DEBUG: 2021-11-25 16:58:39 : satpy.composites.config_loader] Looking for composites config file i.yaml
[DEBUG: 2021-11-25 16:58:39 : satpy.composites.config_loader] No composite config found called i.yaml
[DEBUG: 2021-11-25 16:58:39 : satpy.composites.config_loader] Looking for composites config file l.yaml
[DEBUG: 2021-11-25 16:58:39 : satpy.composites.config_loader] No composite config found called l.yaml
Traceback (most recent call last):
  File "/data/gholl/checkouts/satpy/satpy/scene.py", line 1247, in _update_dependency_tree
    self._dependency_tree.populate_with_keys(needed_datasets, query)
  File "/data/gholl/checkouts/satpy/satpy/dependency_tree.py", line 256, in populate_with_keys
    raise MissingDependencies(unknown_datasets, "Unknown datasets:")
satpy.node.MissingDependencies: Unknown datasets: {DataQuery(name='C14_flash_extent_density')}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/gholl/checkouts/protocode/multiscene-multisensor-woes.py", line 15, in <module>
    sc_both.load(["C14_flash_extent_density"])
  File "/data/gholl/checkouts/satpy/satpy/scene.py", line 1235, in load
    self._update_dependency_tree(needed_datasets, query)
  File "/data/gholl/checkouts/satpy/satpy/scene.py", line 1249, in _update_dependency_tree
    raise KeyError(str(err))
KeyError: "Unknown datasets: {DataQuery(name='C14_flash_extent_density')}"
```

**Comment by gerritholl** [comment]
Maybe the problem happens specifically due to the composite depending on multiple sensors?

**Comment by gerritholl** [comment]
Still a problem after this PR, not covered by any unit tests so far:

```python
sc_abi = Scene(filenames=[abi_file], reader="abi_l1b")
sc_abi.load(["C14"])
sc_both = Scene(filenames={"abi_l1b": [abi_file], "glm_l2": [glm_file]})
print(sc_both.sensor_names)  # both
sc_both["C14"] = sc_abi["C14"]
print(sc_both.sensor_names)  # only ABI
```

gives

```
{'glm', 'abi'}
{'abi'}
```
