### ISSUE TITLE
Multiscene multiprocessing - getting stuck

### ISSUE THREAD

**Issue by roshgor** [pytroll/satpy#1990]
**Describe the bug**
It is seen that while multiprocessing a function that involves multiscene, some erros are encountered:
- If a scene or multiscene is loaded in the mainthread, before starting the pool. 

**To Reproduce**

```python
import warnings
warnings.filterwarnings("ignore")

from glob import glob
from satpy import Scene, MultiScene
from satpy.multiscene import timeseries
from multiprocessing import Pool

# from satpy.utils import debug_on; debug_on()

filenames = sorted(glob("/home/ubuntu/Roshan/test/data/*.nat"))
bands = ['VIS008']

def process_chunk(filenames_chunk):

    mscn = MultiScene.from_files(filenames_chunk, reader='seviri_l1b_native')
    mscn.load(bands, upper_right_corner='NE')
    blended_scene = mscn.blend(blend_function=timeseries)
    print(blended_scene[bands[0]].values.shape)
    

if __name__ == '__main__':

    filenames_chunks = [filenames]

    process_chunk(filenames_chunks[0])
    
    p = Pool(processes=1)
    results = p.map(process_chunk, filenames_chunks)
    p.close()
    p.join()
    print('out_mp')

```

**Expected behavior**
Initially, the process_chunk function is called from the main thread, and output is printed. 
When the same function is being called through p.map, it gets stuck. 
If the function call from the main thread is commented out, multiprocessing of the function works seamlessly. 

**Actual results**
[DEBUG: 2022-01-24 08:56:27 : satpy.readers.yaml_reader] Reading ('/home/ubuntu/.pyenv/versions/3.9.9/envs/CCNC/lib/python3.9/site-packages/satpy/etc/readers/seviri_l1b_native.yaml',)
[DEBUG: 2022-01-24 08:56:27 : satpy.multiscene] Forcing iteration of generator-like object of Scenes
[DEBUG: 2022-01-24 08:56:27 : satpy.readers.yaml_reader] Reading ('/home/ubuntu/.pyenv/versions/3.9.9/envs/CCNC/lib/python3.9/site-packages/satpy/etc/readers/seviri_l1b_native.yaml',)
[DEBUG: 2022-01-24 08:56:27 : satpy.readers.yaml_reader] Assigning to seviri_l1b_native: ['/home/ubuntu/Roshan/test/data/MSG1-SEVI-MSG15-0100-NA-20211201002742.800000000Z-NA.subset.nat']
[DEBUG: 2022-01-24 08:56:27 : satpy.composites.config_loader] Looking for composites config file seviri.yaml
[DEBUG: 2022-01-24 08:56:27 : satpy.composites.config_loader] Looking for composites config file visir.yaml
[DEBUG: 2022-01-24 08:56:28 : native_msg] Calibration time 0:00:00.009442
[INFO: 2022-01-24 08:56:28 : satpy.readers.yaml_reader] Flipping Dataset unknown_name upsidedown.
[INFO: 2022-01-24 08:56:28 : satpy.readers.yaml_reader] Flipping Dataset unknown_name leftright.
[DEBUG: 2022-01-24 08:56:28 : satpy.readers.yaml_reader] Reading ('/home/ubuntu/.pyenv/versions/3.9.9/envs/CCNC/lib/python3.9/site-packages/satpy/etc/readers/seviri_l1b_native.yaml',)
[DEBUG: 2022-01-24 08:56:28 : satpy.readers.yaml_reader] Assigning to seviri_l1b_native: ['/home/ubuntu/Roshan/test/data/MSG1-SEVI-MSG15-0100-NA-20211201004242.910000000Z-NA.subset.nat']
[DEBUG: 2022-01-24 08:56:28 : native_msg] Calibration time 0:00:00.009081
[INFO: 2022-01-24 08:56:28 : satpy.readers.yaml_reader] Flipping Dataset unknown_name upsidedown.
[INFO: 2022-01-24 08:56:28 : satpy.readers.yaml_reader] Flipping Dataset unknown_name leftright.
[DEBUG: 2022-01-24 08:56:28 : satpy.readers.yaml_reader] Reading ('/home/ubuntu/.pyenv/versions/3.9.9/envs/CCNC/lib/python3.9/site-packages/satpy/etc/readers/seviri_l1b_native.yaml',)
[DEBUG: 2022-01-24 08:56:28 : satpy.readers.yaml_reader] Assigning to seviri_l1b_native: ['/home/ubuntu/Roshan/test/data/MSG1-SEVI-MSG15-0100-NA-20211201005743.020000000Z-NA.subset.nat']
[DEBUG: 2022-01-24 08:56:28 : native_msg] Calibration time 0:00:00.009205
[INFO: 2022-01-24 08:56:28 : satpy.readers.yaml_reader] Flipping Dataset unknown_name upsidedown.
[INFO: 2022-01-24 08:56:28 : satpy.readers.yaml_reader] Flipping Dataset unknown_name leftright.
(3, 1113, 872)
[DEBUG: 2022-01-24 08:56:28 : satpy.readers.yaml_reader] Reading ('/home/ubuntu/.pyenv/versions/3.9.9/envs/CCNC/lib/python3.9/site-packages/satpy/etc/readers/seviri_l1b_native.yaml',)
[DEBUG: 2022-01-24 08:56:28 : satpy.multiscene] Forcing iteration of generator-like object of Scenes
[DEBUG: 2022-01-24 08:56:28 : satpy.readers.yaml_reader] Reading ('/home/ubuntu/.pyenv/versions/3.9.9/envs/CCNC/lib/python3.9/site-packages/satpy/etc/readers/seviri_l1b_native.yaml',)
[DEBUG: 2022-01-24 08:56:28 : satpy.readers.yaml_reader] Assigning to seviri_l1b_native: ['/home/ubuntu/Roshan/test/data/MSG1-SEVI-MSG15-0100-NA-20211201002742.800000000Z-NA.subset.nat']
[DEBUG: 2022-01-24 08:56:28 : native_msg] Calibration time 0:00:00.009677

**Screenshots**

**Environment Info:**
 - OS: Linux
 - Satpy Version: '0.32.0'
 - PyResample Version: '1.22.2'

**Additional context**

**Comment by djhoese** [comment]
If you use a regular Scene instead of a MultiScene inside that function does it work (just a simple load and then `.values` would probably work)? Satpy and therefore the Scene and MultiScene objects use dask under the hood. Dask itself uses multiple threads by default, but can also use multiple processes if configured appropriately. I'm pretty sure usage like this is not supported, but I'd have to do more research.

**Comment by roshgor** [comment]
I tried changing the function to the following. Still not working. 
So its not just with multiscenes I guess. 
'''
def process_chunk(filenames_chunk):

    scn = Scene(filenames_chunk, reader='seviri_l1b_native')
    scn.load(bands, upper_right_corner='NE')
    print(scn[bands[0]].values.shape)
'''

I need to find index of a lon lat of interest and store it, and then pass it as one of the parameters to my multiprocessed function, which will be extracting the value from hundreds of files. 
Since this was getting stuck, as a work around, I am using multiprocessing pool, with one process and one parameter, to get my lon lat of interest, before starting the main multiprocess pool; and this works without any issues.

**Comment by djhoese** [comment]
My guess is if you changed the function do not use satpy at all, but only dask that it would still hang:

```python
import dask.array as da
def process_chunk(filenames_chunk):
    a = da.random.normal(size=(10000, 10000))
    b = da.random.normal(size=(10000, 10000))
    (a ** 2 + b ** 2).compute()

```

**Comment by djhoese** [comment]
Oh and I meant to add: I'm not sure I understand why you had to use multiprocessing at all. Can you perform what you are trying to do with dask only? Perhaps some simple for loops or even getting fancy with dask futures?

**Comment by roshgor** [comment]
> My guess is if you changed the function do not use satpy at all, but only dask that it would still hang:

Oh yea. It did hang.

**Comment by roshgor** [comment]
I had not explored dask. Thanks. I will try that out and update.

**Comment by djhoese** [comment]
Ok. Even though that's bad, that's still good because we proved that this is a dask thing and not a satpy thing. So as I said, dask does its own thing with pools and parallel processing. I think if you describe your problem more I might be able to help you get something that works without using multiprocessing pools. *Otherwise*, you could try running a separate script for each of your individual executions (you could call them with python's subprocess maybe) then that *might* work but that is a hack overall.

**Comment by roshgor** [comment]
Lets say i have 100 files (25x25 pixels) with 1 channel data. (25x25x1)

I want to group them into buckets of 3 to get a numpy array of 
(3x25x25x1) using files 1,2,3
(3x25x25x1) using files 2,3,4
(3x25x25x1) using files 3,4,5 and so on. 
and at the end stack them altogether to get a numpy array of shape (90somethingx3x25x25x1)

**Comment by roshgor** [comment]
> Ok. Even though that's bad, that's still good because we proved that this is a dask thing and not a satpy thing. 

Yes. That is great. :) Thanks

**Comment by djhoese** [comment]
:thinking: Hhhhmmm so I think I would do the following:

1. Construct a list of lists of files in the groups of 3. Unless there is some other property about these groups that could be defined in the `MultiScene.from_files` call (like they are groups of 30 minutes of data).
2. Create a list of lists of Scenes from the file list. You could use a MultiScene here, but I'm not sure how much it benefits you. So each MultiScene would be given three Scenes. Or you could use MultiScene.from_files with the 3 file groups.
3. Call the `timeseries` function with the lists of Scenes (or the MultiScenes if you go that route).
4. Extract the DataArrays from the Scene objects returned by `timeseries` by doing `single_scn['VIS008']`.
5. Then use xarray's `concat` to join the groups: https://xarray.pydata.org/en/stable/generated/xarray.concat.html. Something like `xr.concat(list_of_data_arrs, dim="groups")` should work.
6. Then call `.compute()` on that final result and wait forever to get the result :wink: or do some other calculations on the dask array and then compute.

For the groups of 3 files in step 1 you can probably do something like:

```python
all_files = sorted(glob("/home/ubuntu/Roshan/test/data/*.nat"))
all_files_groups = [all_files[idx:idx+3] for idx in range(0, len(all_files), 3)]
```

I think that should work. Then the rest of the steps could just be a couple more list comprehensions.

```python
multiscenes = [MultiScene.from_files(group_files, reader="seviri_l1b_native") for group_files in all_files_groups)]
... and so on ...
```

**Comment by roshgor** [comment]
Thanks.
Okay. So. No computation is actually done at the end. 
Let me explain, my use of multiprocessing pool. 

The place where I need parallelization is when I am creating the list of data arrays. In actuality, I have 1000s of files. 
If a single process runs through groups of threes, extracting each 100mb file, cropping it to region of interest, blending them on timeseries for the group, then extract the data from it and store, and move on like that, it was taking forever. Hence my usage of multiprocessing, so the preprocessing of data is happening much much faster at the moment using multiprocessing for that .

**Comment by djhoese** [comment]
When you say "where the preprocessing of data is happening much much faster", does "preprocessing" mean this entire process of making the (N, 3, 25, 25) array? Or are we just talking about creating the list of Scenes?

What you're talking about is something I've been worried about with MultiScene for a long time. At the end of the day it comes down to the speed of the readers and how they open/parse files. The SEVIRI readers are probably the worst for this (this is just a guess, but an educated one) as most of them are custom binary formats that involve a little more parsing than some files like NetCDF. Again this is just a guess. Right now Satpy doesn't have a good way of sharing previous parsed/discovered information between instances of a single reader. A couple things I should note:

1. Make sure you are using the latest version of satpy. I made updates recently that made it so composite YAML parsing only happens once and doesn't happen on Scene creation. This should have sped up MultiScene creation, but I haven't explicitly profiled it.
2. If you actually have closer to 1000 files then I would at least make a generator for step 1 and 2. If you create the Scenes for a group "on the fly" and then pass that generator to the MultiScene and that MultiScene creation itself is created in a generator then you might be able to avoid some of the annoyances with some of this.
3. Your multiprocessing pool should actually work in theory as long as you don't do the computation inside the function. However, you may get overall better performance if you did the work with threading instead of multiple processes since your work isn't CPU bound but probably I/O bound. One option if you use threads would be to generate the Scene objects in a pool of threads and then give them back to the main thread.
4. Make sure you aren't computing any of the dask arrays (or generators in my note 2 above) until you actually need to.

### Experimental

One thing I've always wanted to try but I'm not sure it would work would be to write a function like your multiprocessing callback, but wrap it in dask's delayed functionality. Then map your list (or generator) of files to this function using dask's Client and get Scenes back. This should do the same as my 3 above but be a little neater as it is still using dask. You could also have the function produce the individual DataArrays. As long as you don't compute inside the function it might work. I'm not sure how dask's delayed functions feel about returned dask arrays. That may determine if the function returns a Scene (no dask arrays created yet) or a DataArray (which has a dask array underneath).

**Comment by djhoese** [comment]
First test on experimental thing I talked about:

```python
In [12]: from satpy import Scene; from glob import glob

In [13]: def create_scene(filenames, reader, product):
    ...:     scn = Scene(reader=reader, filenames=[filenames])
    ...:     scn.load([product])
    ...:     return scn[product]
    ...:

In [14]: delayed_create_scene = dask.delayed(create_scene, pure=True)

In [15]: all_files = glob("/data/satellite/abi/20180911_florence_100/*C01*.nc")

In [16]: len(all_files)
Out[16]: 100

In [17]: all_delayed_data_arrs = [delayed_create_scene(one_file, "abi_l1b", "C01") for one_file in all_files]

In [18]: all_data_arrs = da.compute(*all_delayed_data_arrs)

In [19]: all_data_arrs[0].data
Out[19]: dask.array<mul, shape=(1000, 1000), dtype=float64, chunksize=(1000, 1000), chunktype=numpy.ndarray>
```

So a delayed function can return a dask array. You might have to be careful if you go this route as:

1. The `da.compute` still takes a while. It may be faster if you use a different interface (I still have to test using `client.map`).
2. If you use the default dask scheduler then this all happens in threads which may be more friendly to open-files in the readers. Doing multiple processes (what creating a dask Client will use) may do some weird things that aren't allowed with the open file objects.

**Comment by djhoese** [comment]
This works! ...at least it seems to. Same function definition as above and same `all_files`:

```python
from dask.distributed import Client
client = Client()

res = client.map(create_scene, all_files, reader="abi_l1b", product="C01")
all_data_arrs = client.gather(res)
all_data_arrs[0]  # a single DataArray backed by a dask array
```

Note how I use the regular function in the `.map` call, not the delayed version of the function.

**Comment by roshgor** [comment]
> When you say "where the preprocessing of data is happening much much faster", does "preprocessing" mean this entire process of making the (N, 3, 25, 25) array? Or are we just talking about creating the list of Scenes?
By preprocessing I am referring to making the entire (N, 3, 25, 25) array.  I'm making a list of N, (3, 25, 25) arrays and just stacking them at the end.

**Comment by roshgor** [comment]
> This works! .

Awesome. Let me check this out.

**Comment by roshgor** [comment]
```
client.map
```
Oof. Working so well. :smiley:

**Comment by djhoese** [comment]
I've been trying to use this `.map` logic in a real world use case with the `abi_l1b` reader and eventually hit:

```
  File "/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages/distributed/protocol/serialize.py", line 180, in serialization_error_loads
    raise TypeError(msg)
TypeError: Could not serialize object of type DataArray.
Traceback (most recent call last):
  File "/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages/distributed/protocol/pickle.py", line 49, in dumps
    result = pickle.dumps(x, **dump_kwargs)
  File "/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages/h5py/_hl/base.py", line 368, in __getnewargs__
    raise TypeError("h5py objects cannot be pickled")
TypeError: h5py objects cannot be pickled

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages/distributed/protocol/serialize.py", line 340, in serialize
    header, frames = dumps(x, context=context) if wants_context else dumps(x)
  File "/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages/distributed/protocol/serialize.py", line 63, in pickle_dumps
    frames[0] = pickle.dumps(
  File "/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages/distributed/protocol/pickle.py", line 60, in dumps
    result = cloudpickle.dumps(x, **dump_kwargs)
  File "/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages/cloudpickle/cloudpickle_fast.py", line 602, in dump
    return Pickler.dump(self, obj)
  File "/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages/h5py/_hl/base.py", line 368, in __getnewargs__
    raise TypeError("h5py objects cannot be pickled")
TypeError: h5py objects cannot be pickled
```

I'm not sure there is an easy way around it.

**Comment by roshgor** [comment]
Hmmm. Im dealing with more basic problems. 
Initially I had the problem where I create an instance object outside main, and then i stumbled across your issue on dask github, and that got solved. 
Now Im dealing with:
```
distributed.worker - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be released to the OS; see https://distributed.dask.org/en/latest/worker.html#memtrim for more information. -- Unmanaged memory: 7.11 GiB -- Worker memory limit: 7.73 GiB
```
and
```
distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
distributed.nanny - WARNING - Restarting worker
```
My function is taking chunks of 100 files, creating a multi scene, extracting pixel vals of bands of interest for a single lat lon, creating a dataframe, returning it. 

After my map function. I am concatenating the dataframes. 

I'll see if unloading a scene at the end of the function will help.

**Comment by djhoese** [comment]
Hhhmmm weird. You're also using a different reader than I am. The SEVIRI native reader uses memory maps so I could see that playing a part:

https://github.com/pytroll/satpy/blob/3e94d59bad6f89306b19306f2e46b73df0e21d7b/satpy/readers/seviri_l1b_native.py#L184-L186

The memory isn't actually used but the address space is allocated so depending on what metric dask is using for that warning maybe it isn't actually being used...but this is a wild guess.

**Comment by djhoese** [comment]
So I found out the main issue for me, at least as far as h5py goes, is because the rayleigh correction used in pyspectral was loading HDF5 files with h5py in a non-distributed friendly way. A small patch to pyspectral should fix that part of it. Loading a composite that doesn't use rayleigh correction also worked fine.
