### ISSUE TITLE
Resampling from SwathDefinition to AreaDefinition fails with OSError and AssertionError

### ISSUE THREAD

**Issue by gerritholl** [pytroll/satpy#1997]
**Describe the bug**

I have some synthetic data to which I have assigned a SwathDefinition.  I'm trying to resample it to an AreaDefinition.  This fails, initially with an OSError, then, during handling of that exception, with an AssertionError.

**To Reproduce**

```python
from satpy.resample import resample_dataset
from pyresample import create_area_def
from pyresample.geometry import SwathDefinition
import xarray as xr
import numpy as np
test_areadef = create_area_def(
        "test", 4087,
        area_extent=[0, 0, 500_000, 500_000],
        resolution=100_000)
test_swathdef = SwathDefinition(
        xr.DataArray(np.array([
            [0.4, 1.3, 2.2, 3.1, 4. ],
            [0.4, 1.3, 2.2, 3.1, 4. ],
            [0.4, 1.3, 2.2, 3.1, 4. ],
            [0.4, 1.3, 2.2, 3.1, 4. ],
            [0.4, 1.3, 2.2, 3.1, 4. ]])),
        xr.DataArray(np.array([
            [4. , 4. , 4. , 4. , 4. ],
            [3.1, 3.1, 3.1, 3.1, 3.1],
            [2.2, 2.2, 2.2, 2.2, 2.2],
            [1.3, 1.3, 1.3, 1.3, 1.3],
            [0.4, 0.4, 0.4, 0.4, 0.4]])))
ds = xr.DataArray(
        np.full((5, 5), 250),
        dims=("y", "x"),
        attrs={"area": test_swathdef})
new = resample_dataset(ds, test_areadef)
```

**Expected behavior**

I expect a resampled dataset.

**Actual results**

```python-traceback
[INFO: 2022-01-28 10:35:17 : satpy.resample] Using default KDTree resampler
/data/gholl/mambaforge/envs/py310/lib/python3.10/site-packages/xarray/core/pycompat.py:22: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  duck_array_version = LooseVersion(duck_array_module.__version__)
/data/gholl/checkouts/pyresample/pyresample/geometry.py:617: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  xyz = np.stack(transform(src, dst, lons, lats, alt), axis=1)
[DEBUG: 2022-01-28 10:35:17 : satpy.resample] Computing kd-tree parameters
Traceback (most recent call last):
  File "/data/gholl/checkouts/satpy/satpy/resample.py", line 507, in precompute
    self.load_neighbour_info(cache_dir, mask=mask, **kwargs)
  File "/data/gholl/checkouts/satpy/satpy/resample.py", line 591, in load_neighbour_info
    raise IOError
OSError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/gholl/checkouts/protocode/resample-with-swathdef.py", line 28, in <module>
    new = resample_dataset(ds, test_areadef)
  File "/data/gholl/checkouts/satpy/satpy/resample.py", line 1395, in resample_dataset
    new_data = resample(source_area, dataset, destination_area, fill_value=fill_value, **kwargs)
  File "/data/gholl/checkouts/satpy/satpy/resample.py", line 1358, in resample
    res = resampler_instance.resample(data, **kwargs)
  File "/data/gholl/checkouts/satpy/satpy/resample.py", line 438, in resample
    cache_id = self.precompute(cache_dir=cache_dir, **kwargs)
  File "/data/gholl/checkouts/satpy/satpy/resample.py", line 511, in precompute
    self.resampler.get_neighbour_info(mask=mask)
  File "/data/gholl/checkouts/pyresample/pyresample/kd_tree.py", line 997, in get_neighbour_info
    assert (mask.shape == self.source_geo_def.shape), \
AssertionError: 'mask' must be the same shape as the source geo definition
```

**Environment Info:**
 - OS: openSUSE Leap 15.3
 - Satpy Version: v0.33.1-46-g3e94d59b
 - PyResample Version: v1.22.3-4-g565966f

**Additional context**

When I define the lon/lats as ndarray rather than xarray.dataarray, it fails with https://github.com/pytroll/satpy/issues/1434#issuecomment-1024038194

**Comment by gerritholl** [comment]
If I add `mask=False` to the `resample_dataset` call, it fails with:

```
[INFO: 2022-01-28 10:54:20 : satpy.resample] Using default KDTree resampler
/data/gholl/checkouts/pyresample/pyresample/geometry.py:617: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  xyz = np.stack(transform(src, dst, lons, lats, alt), axis=1)
[DEBUG: 2022-01-28 10:54:20 : satpy.resample] Computing kd-tree parameters
[DEBUG: 2022-01-28 10:54:20 : satpy.resample] Resampling None
Traceback (most recent call last):
  File "/data/gholl/checkouts/protocode/resample-with-swathdef.py", line 28, in <module>
    new = resample_dataset(ds, test_areadef, mask_area=False)
  File "/data/gholl/checkouts/satpy/satpy/resample.py", line 1395, in resample_dataset
    new_data = resample(source_area, dataset, destination_area, fill_value=fill_value, **kwargs)
  File "/data/gholl/checkouts/satpy/satpy/resample.py", line 1358, in resample
    res = resampler_instance.resample(data, **kwargs)
  File "/data/gholl/checkouts/satpy/satpy/resample.py", line 439, in resample
    return self.compute(data, cache_id=cache_id, **kwargs)
  File "/data/gholl/checkouts/satpy/satpy/resample.py", line 627, in compute
    res = self.resampler.get_sample_from_neighbour_info(data, fill_value)
  File "/data/gholl/checkouts/pyresample/pyresample/kd_tree.py", line 1064, in get_sample_from_neighbour_info
    assert (data_geo_dims == src_geo_dims), \
AssertionError: Data dimensions do not match source area dimensions
```

It looks like the lon/lat must have dimension names.  The following works:

```
from satpy.resample import resample_dataset
from pyresample import create_area_def
from pyresample.geometry import SwathDefinition
import xarray as xr
import numpy as np
from satpy.utils import debug_on; debug_on()
test_areadef = create_area_def(
        "test", 4087,
        area_extent=[0, 0, 500_000, 500_000],
        resolution=100_000)
test_swathdef = SwathDefinition(
        xr.DataArray(np.array([
            [0.4, 1.3, 2.2, 3.1, 4. ],
            [0.4, 1.3, 2.2, 3.1, 4. ],
            [0.4, 1.3, 2.2, 3.1, 4. ],
            [0.4, 1.3, 2.2, 3.1, 4. ],
            [0.4, 1.3, 2.2, 3.1, 4. ]]),
            dims=("y", "x")),
        xr.DataArray(np.array([
            [4. , 4. , 4. , 4. , 4. ],
            [3.1, 3.1, 3.1, 3.1, 3.1],
            [2.2, 2.2, 2.2, 2.2, 2.2],
            [1.3, 1.3, 1.3, 1.3, 1.3],
            [0.4, 0.4, 0.4, 0.4, 0.4]]),
            dims=("y", "x")))
ds = xr.DataArray(
        np.full((5, 5), 250.0),
        dims=("y", "x"),
        attrs={"area": test_swathdef})
new = resample_dataset(ds, test_areadef)
```

**Comment by djhoese** [comment]
Although not documented (very well probably), resampling to/from a SwathDefinition that doesn't consist of lon/lats of type DataArray[dask] is not really supported. It may be more likely supported when pyresample 2.0 resamplers are made more flexible with alternate data types. Additionally, we should probably add a `_` to `resample_dataset`. That's not really supposed to be a user-facing interface.

**Comment by gerritholl** [comment]
I don't know when this changed, but it works with current satpy.
