### ISSUE TITLE
Reading bzipped Seviri HRIT segment crashes when reading the data from disk

### ISSUE THREAD

**Issue by mraspaud** [pytroll/satpy#2183]
**Describe the bug**
Reading bzipped Seviri HRIT segment crashes when reading the data from disk. It looks like the unzipped file is removed before the data can actually be read

**To Reproduce**

```python
from satpy import Scene
import os
from satpy.utils import debug_on
debug_on()
datadir = "/somedir/"

filenames = [os.path.join(datadir, "H-000-MSG4__-MSG4________-_________-PRO______-201802281500-__"),
             os.path.join(datadir, "H-000-MSG4__-MSG4________-VIS006___-000008___-201802281500-__.bz2"),
             os.path.join(datadir, "H-000-MSG4__-MSG4________-_________-EPI______-201802281500-__")]

scn = Scene(filenames=filenames,
            reader='seviri_l1b_hrit',
            )
composite = "VIS006"
scn.load([composite])
scn[composite].compute()

```

**Expected behavior**
I expect the computed array to be returned

**Actual results**
Instead, I get a crash with the following output:
```python
Traceback (most recent call last):
  File "/home/a001673/usr/src/spy-test/test_hrit_seviri.py", line 41, in <module>
    scn.load([composite])
  File "/home/a001673/usr/src/satpy/satpy/scene.py", line 1350, in load
    self._read_datasets_from_storage(**kwargs)
  File "/home/a001673/usr/src/satpy/satpy/scene.py", line 1373, in _read_datasets_from_storage
    return self._read_dataset_nodes_from_storage(nodes, **kwargs)
  File "/home/a001673/usr/src/satpy/satpy/scene.py", line 1379, in _read_dataset_nodes_from_storage
    loaded_datasets = self._load_datasets_by_readers(reader_datasets, **kwargs)
  File "/home/a001673/usr/src/satpy/satpy/scene.py", line 1404, in _load_datasets_by_readers
    new_datasets = reader_instance.load(ds_ids, **kwargs)
  File "/home/a001673/usr/src/satpy/satpy/readers/yaml_reader.py", line 965, in load
    ds = self._load_dataset_with_area(dsid, coords, **kwargs)
  File "/home/a001673/usr/src/satpy/satpy/readers/yaml_reader.py", line 1134, in _load_dataset_with_area
    ds = super(GEOFlippableFileYAMLReader, self)._load_dataset_with_area(dsid, coords, **kwargs)
  File "/home/a001673/usr/src/satpy/satpy/readers/yaml_reader.py", line 853, in _load_dataset_with_area
    ds = self._load_dataset_data(file_handlers, dsid, **kwargs)
  File "/home/a001673/usr/src/satpy/satpy/readers/yaml_reader.py", line 725, in _load_dataset_data
    proj = self._load_dataset(dsid, ds_info, file_handlers, **kwargs)
  File "/home/a001673/usr/src/satpy/satpy/readers/yaml_reader.py", line 1185, in _load_dataset
    _find_missing_segments(file_handlers, ds_info, dsid)
  File "/home/a001673/usr/src/satpy/satpy/readers/yaml_reader.py", line 1339, in _find_missing_segments
    projectable = fh.get_dataset(dsid, ds_info)
  File "/home/a001673/usr/src/satpy/satpy/readers/seviri_l1b_hrit.py", line 627, in get_dataset
    res = super(HRITMSGFileHandler, self).get_dataset(key, info)
  File "/home/a001673/usr/src/satpy/satpy/readers/hrit_base.py", line 247, in get_dataset
    data = self.read_band(key, info)
  File "/home/a001673/usr/src/satpy/satpy/readers/hrit_base.py", line 358, in read_band
    data = da.from_array(data, chunks=shape[0])
  File "/home/a001673/mambaforge/envs/satpy/lib/python3.10/site-packages/dask/array/core.py", line 3298, in from_array
    token = tokenize(x, chunks, lock, asarray, fancy, getitem, inline_array)
  File "/home/a001673/mambaforge/envs/satpy/lib/python3.10/site-packages/dask/base.py", line 867, in tokenize
    hasher = _md5(str(tuple(map(normalize_token, args))).encode())
  File "/home/a001673/mambaforge/envs/satpy/lib/python3.10/site-packages/dask/utils.py", line 605, in __call__
    return meth(arg, *args, **kwargs)
  File "/home/a001673/mambaforge/envs/satpy/lib/python3.10/site-packages/dask/base.py", line 1116, in normalize_array
    os.path.getmtime(x.filename),
  File "/home/a001673/mambaforge/envs/satpy/lib/python3.10/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp2l4w85up'

```

The log before that:
```
/home/a001673/usr/src/satpy/satpy/_config.py:125: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
  for entry_point in entry_points().get(name, []):
[DEBUG: 2022-08-19 08:57:20 : satpy.readers.yaml_reader] Reading ('/home/a001673/usr/src/satpy/satpy/etc/readers/seviri_l1b_hrit.yaml',)
/home/a001673/usr/src/satpy/satpy/readers/seviri_base.py:453: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  ('GsicsCalMode', np.bool),
/home/a001673/usr/src/satpy/satpy/readers/seviri_base.py:454: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  ('GsicsCalValidity', np.bool),
[DEBUG: 2022-08-19 08:57:20 : satpy.readers.yaml_reader] Assigning to seviri_l1b_hrit: ['/home/a001673/usr/src/shared-docker-files/trollflow2_full_image/input/H-000-MSG4__-MSG4________-VIS006___-000008___-201802281500-__.bz2', '/home/a001673/usr/src/shared-docker-files/trollflow2_full_image/input/H-000-MSG4__-MSG4________-_________-PRO______-201802281500-__', '/home/a001673/usr/src/shared-docker-files/trollflow2_full_image/input/H-000-MSG4__-MSG4________-_________-EPI______-201802281500-__']
[INFO: 2022-08-19 08:57:20 : hrit_msg] No IMPF configuration field found in prologue.
[DEBUG: 2022-08-19 08:57:20 : satpy.composites.config_loader] Looking for composites config file seviri.yaml
[INFO: 2022-08-19 08:57:20 : satpy.readers.utils] Using temp file for BZ2 decompression: /tmp/tmp2l4w85up
```

**Environment Info:**
 - OS: linux
 - Satpy Version: main

**Comment by mraspaud** [comment]
@pdebuyl @simonrp84 Have you seen anything like this?

**Comment by pdebuyl** [comment]
Yes, I have a similar issue, even using a test program from I developed the feature...

Going to commit `34c360e9a2c33c4998b0e6847d7b8286d7ec41fd` solves it.

**Comment by pdebuyl** [comment]
`f4613e8de2cee4c78800d389c20d1e6dc5dcdb44` breaks the feature

**Comment by pdebuyl** [comment]
You can't put the `data = da.from_array(data, chunks=shape[0])` outside of the `unzip_context` context.

The issue is that it would leave all unzipped files laying around. At the time, we found no way to keep a "deletion marker" for such files. There can't be lazy reading of bz2 files with the current code.

**Comment by mraspaud** [comment]
@pdebuyl thanks for the confirmation. I'm working on a PR to solve the issue, by making the reading eager, but inside a delayed dask task, see #2185

**Comment by pdebuyl** [comment]
I am not familiar with dask but I can test the code when the PR is ready if you wish.

**Comment by mraspaud** [comment]
Thanks! the PR is not ready, but the changes included now should already fix the problem if you want to give it a spin.
