### ISSUE TITLE
hy2_scat_l2b_h5 reader does not work any more due to space in `valid range` attribute

### ISSUE THREAD

**Issue by TAlonglong** [pytroll/satpy#2208]
**Describe the bug**

**To Reproduce**

```python
# Your code here
#!/usr/bin/env python

import sys
from satpy import Scene
from satpy.utils import debug_on
debug_on()

files = [sys.argv[1]]
data = Scene(filenames=files, reader = 'hy2_scat_l2b_h5')
data.load(['wind_speed_selection'])

```

**Expected behavior**
The wind_speed_selection should be read without any error messages.

**Actual results**
```
(pytroll) trygveas@pc5564:~/pytroll/satpy$ python ~/Git/ppi-remotesensing-satellite-processing/templates/test-hy2.py ~/Git/ppi-remotesensing-satellite-processing/W_XX-EUMETSAT-Darmstadt,SURFACE+SATELLITE,HY2B+SM_C_EUMP_20220611------_18202_o_250_l2b.h5
[DEBUG: 2022-09-28 17:34:17 : satpy.readers.yaml_reader] Reading ('/home/trygveas/pytroll/satpy/satpy/etc/readers/hy2_scat_l2b_h5.yaml',)
[DEBUG: 2022-09-28 17:34:17 : satpy.readers.yaml_reader] Assigning to hy2_scat_l2b_h5: ['/home/trygveas/Git/ppi-remotesensing-satellite-processing/W_XX-EUMETSAT-Darmstadt,SURFACE+SATELLITE,HY2B+SM_C_EUMP_20220611------_18202_o_250_l2b.h5']
[DEBUG: 2022-09-28 17:34:17 : satpy.composites.config_loader] Looking for composites config file scatterometer.yaml
[DEBUG: 2022-09-28 17:34:17 : satpy.composites.config_loader] Looking for composites config file visir.yaml
[WARNING: 2022-09-28 17:34:17 : satpy.readers.yaml_reader] Failed to load DataID(name='wvc_lat', resolution=25000, modifiers=()) from <HY2SCATL2BH5FileHandler: '/home/trygveas/Git/ppi-remotesensing-satellite-processing/W_XX-EUMETSAT-Darmstadt,SURFACE+SATELLITE,HY2B+SM_C_EUMP_20220611------_18202_o_250_l2b.h5'>
Traceback (most recent call last):
  File "/home/trygveas/pytroll/satpy/satpy/readers/yaml_reader.py", line 695, in _load_dataset
    projectable = fh.get_dataset(dsid, ds_info)
  File "/home/trygveas/pytroll/satpy/satpy/readers/hy2_scat_l2b_h5.py", line 110, in get_dataset
    data = self._mask_data(key['name'], data)
  File "/home/trygveas/pytroll/satpy/satpy/readers/hy2_scat_l2b_h5.py", line 129, in _mask_data
    valid_range = self[key_name].attrs['valid_range']
KeyError: 'valid_range'
[ERROR: 2022-09-28 17:34:17 : satpy.readers.yaml_reader] Could not load dataset 'DataID(name='wvc_lat', resolution=25000, modifiers=())': "Could not load DataID(name='wvc_lat', resolution=25000, modifiers=()) from any provided files"
Traceback (most recent call last):
  File "/home/trygveas/pytroll/satpy/satpy/readers/yaml_reader.py", line 847, in _load_dataset_with_area
    ds = self._load_dataset_data(file_handlers, dsid, **kwargs)
  File "/home/trygveas/pytroll/satpy/satpy/readers/yaml_reader.py", line 719, in _load_dataset_data
    proj = self._load_dataset(dsid, ds_info, file_handlers, **kwargs)
  File "/home/trygveas/pytroll/satpy/satpy/readers/yaml_reader.py", line 704, in _load_dataset
    raise KeyError(
KeyError: "Could not load DataID(name='wvc_lat', resolution=25000, modifiers=()) from any provided files"
[WARNING: 2022-09-28 17:34:17 : satpy.readers.yaml_reader] Failed to load DataID(name='wvc_lon', resolution=25000, modifiers=()) from <HY2SCATL2BH5FileHandler: '/home/trygveas/Git/ppi-remotesensing-satellite-processing/W_XX-EUMETSAT-Darmstadt,SURFACE+SATELLITE,HY2B+SM_C_EUMP_20220611------_18202_o_250_l2b.h5'>
Traceback (most recent call last):
  File "/home/trygveas/pytroll/satpy/satpy/readers/yaml_reader.py", line 695, in _load_dataset
    projectable = fh.get_dataset(dsid, ds_info)
  File "/home/trygveas/pytroll/satpy/satpy/readers/hy2_scat_l2b_h5.py", line 110, in get_dataset
    data = self._mask_data(key['name'], data)
  File "/home/trygveas/pytroll/satpy/satpy/readers/hy2_scat_l2b_h5.py", line 129, in _mask_data
    valid_range = self[key_name].attrs['valid_range']
KeyError: 'valid_range'
[ERROR: 2022-09-28 17:34:17 : satpy.readers.yaml_reader] Could not load dataset 'DataID(name='wvc_lon', resolution=25000, modifiers=())': "Could not load DataID(name='wvc_lon', resolution=25000, modifiers=()) from any provided files"
Traceback (most recent call last):
  File "/home/trygveas/pytroll/satpy/satpy/readers/yaml_reader.py", line 847, in _load_dataset_with_area
    ds = self._load_dataset_data(file_handlers, dsid, **kwargs)
  File "/home/trygveas/pytroll/satpy/satpy/readers/yaml_reader.py", line 719, in _load_dataset_data
    proj = self._load_dataset(dsid, ds_info, file_handlers, **kwargs)
  File "/home/trygveas/pytroll/satpy/satpy/readers/yaml_reader.py", line 704, in _load_dataset
    raise KeyError(
...
```

**Environment Info:**
 - OS: Linux
 - Satpy Version: 0.37.2 from main
 - PyResample Version:
 - Readers and writers dependencies (when relevant): [run `from satpy.utils import check_satpy; check_satpy()`]

**Additional context**
So runing a bit debugging, I see `valid range` is replaced by `valid_range` in `data.attrs`. But in `_mask_data` the `valid_range` is used from self. Which is as far as I can see stil having the `valid range` (without underscrore)

I'm a bit pussled about this, since I'm quite sure this worked in the past. But checking in now I get these error messages.

I need to look at the blame to see if something has been changed in the reader

**Comment by TAlonglong** [comment]
https://github.com/pytroll/satpy/commit/beea49b166d2f78ca94dce8c2369794ef539b6ac

Hehe. Look who to blame! 

So the change still made the test pass. So I will need to look into both the reader and the test.

I did not discover this since I was running an old satpy version. Working with updating this today revealed it.

Oh well.

**Comment by TAlonglong** [comment]
I don't get this. The tests works, but real data does not. So there are something in the test which not reflect the case in the real data.

If I print out some debug, for the test I see the `valid range` is changed to `valid_range` in the reader it both data and self. but for real data only the data is changed. Not self. 

Is self protected somehow I donæt understand, but in the tests this is part of a mock or something.

Hm. tricky this was.

**Comment by TAlonglong** [comment]
https://docs.xarray.dev/en/stable/generated/xarray.where.html
