### ISSUE TITLE
satpy_cf_nc reader could be more liberal in filename acceptance

### ISSUE THREAD

**Issue by gerritholl** [pytroll/satpy#2223]
## Feature Request

**Is your feature request related to a problem? Please describe.**

The `satpy_cf_nc` reader is needlessly restrictive in its filename acceptance.  It only accepts filenames with the pattern `'{platform_name}-{sensor}-{start_time:%Y%m%d%H%M%S}-{end_time:%Y%m%d%H%M%S}.nc'` (and `'{platform_name}-{sensor}-{resolution_type}-{start_time:%Y%m%d%H%M%S}-{end_time:%Y%m%d%H%M%S}.nc'`, but this is undocumented).  This restriction should not be necessary and makes a simple round-trip save/load more complicated:

```
from satpy import Scene
from glob import glob
from satpy.utils import debug_on; debug_on()
filenames = glob("/media/nas/x21308/scratch/wcm/in/*C13_G16_*")
sc = Scene(filenames=filenames, reader=["abi_l1b"])
sc.load(["C13"])
ls = sc.resample("wcm40km")
ls.save_datasets(
        writer="cf",
        filename="/tmp/test.nc",
        encoding={
            "C13":
            {"zlib": True,
             "complevel": 9,
             "scale_factor": 0.1,
             "dtype": "int16"}},
        include_lonlats=False)
sc2 = Scene(filenames=["/tmp/test.nc"], reader=["satpy_cf_nc"])
```

which fails with `No supported files found`:

```
/data/gholl/checkouts/satpy/satpy/_config.py:125: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
  for entry_point in entry_points().get(name, []):
[DEBUG: 2022-10-07 11:25:30 : satpy.readers.yaml_reader] Reading ('/data/gholl/checkouts/satpy/satpy/etc/readers/abi_l1b.yaml',)
[DEBUG: 2022-10-07 11:25:30 : satpy.readers.yaml_reader] Assigning to abi_l1b: ['/media/nas/x21308/scratch/wcm/in/OR_ABI-L1b-RadF-M6C13_G16_s20222791200206_e20222791209526_c20222791209590.nc']
[DEBUG: 2022-10-07 11:25:30 : satpy.composites.config_loader] Looking for composites config file abi.yaml
/data/gholl/checkouts/satpy/satpy/_config.py:125: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
  for entry_point in entry_points().get(name, []):
[DEBUG: 2022-10-07 11:25:30 : satpy.composites.config_loader] Looking for composites config file visir.yaml
[DEBUG: 2022-10-07 11:25:30 : satpy.readers.abi_l1b] Reading in get_dataset C13.
[DEBUG: 2022-10-07 11:25:30 : satpy.scene] Resampling DataID(name='C13', wavelength=WavelengthRange(min=10.1, central=10.35, max=10.6, unit='µm'), resolution=2000, calibration=<calibration.brightness_temperature>, modifiers=())
[INFO: 2022-10-07 11:25:31 : satpy.resample] Using default KDTree resampler
[DEBUG: 2022-10-07 11:25:31 : satpy.resample] Computing kd-tree parameters
[DEBUG: 2022-10-07 11:25:31 : satpy.resample] Resampling Rad
[DEBUG: 2022-10-07 11:25:31 : satpy.writers] Reading ['/data/gholl/checkouts/satpy/satpy/etc/writers/cf.yaml']
[INFO: 2022-10-07 11:25:31 : satpy.writers.cf_writer] Saving datasets to NetCDF4/CF.
/data/gholl/checkouts/satpy/satpy/writers/cf_writer.py:571: FutureWarning: The default behaviour of the CF writer will soon change to not compress data by default.
  warnings.warn("The default behaviour of the CF writer will soon change to not compress data by default.",
/data/gholl/checkouts/satpy/satpy/writers/cf_writer.py:197: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(pyproj.__version__) < LooseVersion('2.4.1'):
[WARNING: 2022-10-07 11:25:31 : satpy.writers.cf_writer] No time dimension in datasets, skipping time bounds creation.
/data/gholl/checkouts/satpy/satpy/writers/cf_writer.py:859: SerializationWarning: saving variable C13 with floating point data as an integer dtype without any _FillValue to use for NaNs
  res = dataset.to_netcdf(filename, engine=engine, group=group_name, mode='a', encoding=encoding,
/data/gholl/mambaforge/envs/py310/lib/python3.10/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in cos
  return func(*(_execute_task(a, cache) for a in args))
/data/gholl/mambaforge/envs/py310/lib/python3.10/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in sin
  return func(*(_execute_task(a, cache) for a in args))
/data/gholl/checkouts/satpy/satpy/_config.py:125: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
  for entry_point in entry_points().get(name, []):
[DEBUG: 2022-10-07 11:25:37 : satpy.readers.yaml_reader] Reading ('/data/gholl/checkouts/satpy/satpy/etc/readers/satpy_cf_nc.yaml',)
[WARNING: 2022-10-07 11:25:37 : satpy.readers.yaml_reader] No filenames found for reader: satpy_cf_nc
[WARNING: 2022-10-07 11:25:37 : satpy.readers] Don't know how to open the following files: {'/tmp/test.nc'}
Traceback (most recent call last):
  File "/data/gholl/checkouts/protocode/mwe/test-new-wcm-nc.py", line 18, in <module>
    sc2 = Scene(filenames=["/tmp/test.nc"], reader=["satpy_cf_nc"])
  File "/data/gholl/checkouts/satpy/satpy/scene.py", line 133, in __init__
    self._readers = self._create_reader_instances(filenames=filenames,
  File "/data/gholl/checkouts/satpy/satpy/scene.py", line 154, in _create_reader_instances
    return load_readers(filenames=filenames,
  File "/data/gholl/checkouts/satpy/satpy/readers/__init__.py", line 579, in load_readers
    _check_reader_instances(reader_instances)
  File "/data/gholl/checkouts/satpy/satpy/readers/__init__.py", line 618, in _check_reader_instances
    raise ValueError("No supported files found")
ValueError: No supported files found
```

**Describe the solution you'd like**

I would like that the satpy netcdf reader accepts any `*.nc`, just like how the generic image reader accepts any `*.tif`.

**Describe any changes to existing user workflow**

I don't think there is any.

**Additional context**

I might be missing or forgetting something; I seem to remember there is information that Satpy _needs_ to get from the filename, but I am not sure if that applies in this example.

**Comment by djhoese** [comment]
I think @BENR0 has a PR somewhere that does this. I'm on mobile so can't easily find it.

**Comment by BENR0** [comment]
yes there is: [#1637](https://github.com/pytroll/satpy/pull/1637) but it is still marked as draft

**Comment by gerritholl** [comment]
It doesn't seem that #1637 is actually making the reader more liberal than current main, but rather adapting the default from the writer?

**Comment by BENR0** [comment]
I think it does by adding `'{filename}.nc'` as a file name pattern to the reader yaml.

**Comment by gerritholl** [comment]
> I think it does by adding `'{filename}.nc'` as a file name pattern to the reader yaml.

You're right, I overlooked that!
