### ISSUE TITLE
ahi-hsd raise keyerror when load B08 in dataquery

### ISSUE THREAD

**Issue by ceri540** [pytroll/satpy#2249]
#### Code Sample, a minimal, complete, and verifiable piece of code

```python

from satpy import Scene
from satpy import find_files_and_readers
from satpy.dataset import DataQuery

from datetime import datetime

files_dir = "./01_main_dataset/satpy_datasets/himawari/2021/02/14/03"

files = find_files_and_readers(sensor = "ahi",
                               start_time = datetime(2021, 2, 14, 3, 0),
                               end_time = datetime(2021, 2, 14, 3, 0),
                               base_dir = files_dir,
                               reader = 'ahi_hsd')
scn = Scene(filenames = files)

for index, bandname in enumerate(scn.all_dataset_names()):
    scn.load([DataQuery(name = bandname, modifiers = ('sunz_corrected', 'rayleigh_corrected')), ])**
    new_scn = scn.resample(scn.max_area(), resampler='native')
    new_scn.save_dataset(new_scn.keys()[0], filename='./png/himawari_ahi_rayleigh_{bandname}_{datetime}.png'.format(bandname=bandname, datetime=scn.start_time.strftime('%Y%m%d%H%M')))

```
#### Problem description
hello, i am processing himawari 8 ahi datasets. I want to process reflectance after removing rayleigh, but i have problem when scn.load(['band 7']) using DataQuery.

#### Expected Output
correctly output all bands reflectance after rayleigh corr process

#### Actual Result, Traceback if applicable
Traceback (most recent call last):
  File "/home/yanny/anaconda3/envs/satpy_env/lib/python3.10/site-packages/satpy/scene.py", line 1358, in _update_dependency_tree
    self._dependency_tree.populate_with_keys(needed_datasets, query)
  File "/home/yanny/anaconda3/envs/satpy_env/lib/python3.10/site-packages/satpy/dependency_tree.py", line 262, in populate_with_keys
    raise MissingDependencies(unknown_datasets, "Unknown datasets:")
satpy.node.MissingDependencies: Unknown datasets: {DataQuery(name='B03', modifiers=('sunz_corrected',), calibration='brightness_temperature'): {DataQuery(name='B03', modifiers=(), calibration='brightness_temperature')}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanny/anaconda3/envs/satpy_env/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/yanny/anaconda3/envs/satpy_env/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/chensiyu/.vscode-server/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/chensiyu/.vscode-server/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/chensiyu/.vscode-server/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/chensiyu/.vscode-server/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/chensiyu/.vscode-server/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/chensiyu/.vscode-server/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/chensiyu/00_develop_program/03_pytroll/rayleigh_satpy.py", line 34, in <module>
    scn.load([DataQuery(name = bandname, modifiers = ('sunz_corrected', 'rayleigh_corrected')), ])
  File "/home/yanny/anaconda3/envs/satpy_env/lib/python3.10/site-packages/satpy/scene.py", line 1346, in load
    self._update_dependency_tree(needed_datasets, query)
  File "/home/yanny/anaconda3/envs/satpy_env/lib/python3.10/site-packages/satpy/scene.py", line 1360, in _update_dependency_tree
    raise KeyError(str(err))
KeyError: "Unknown datasets: {DataQuery(name='B03', modifiers=('sunz_corrected',), calibration='brightness_temperature'): {DataQuery(name='B03', modifiers=(), calibration='brightness_temperature')}}"

#### Versions of Python, package at hand and relevant dependencies
satpy 0.37.1
python 3.10.6

**Comment by simonrp84** [comment]
Band 7 onwards are thermal bands, they cannot have Rayleigh correction applied - that only works (and is only nedessart for) visible wavelengths.

**Comment by ceri540** [comment]
thanks for answer, will it work by pyspectral?

**Comment by ceri540** [comment]
Ok, I have found the answer from another issue, thank you very much
