### ISSUE TITLE
Issue Reading MSG4

### ISSUE THREAD

**Issue by WxmanJ** [pytroll/satpy#227]
I seem to be having difficulty reading the segments of Meteosat-11.

The traceback I receive is:
```python
[root@satpy ~]# python test_msg.py 
[DEBUG: 2018-03-15 12:51:30 : satpy.scene] Setting 'PPP_CONFIG_DIR' to '/usr/lib/python2.7/site-packages/satpy/etc'
[DEBUG: 2018-03-15 12:51:30 : satpy.readers] Reading ['/usr/lib/python2.7/site-packages/satpy/etc/readers/hrit_msg.yaml', '/usr/lib/python2.7/site-packages/satpy/etc/readers/hrit_msg.yaml', '/usr/lib/python2.7/site-packages/satpy/etc/readers/hrit_msg.yaml']
[DEBUG: 2018-03-15 12:51:30 : satpy.readers.yaml_reader] Assigning to hrit_msg:
['/root/msg_data/H-000-MSG4__-MSG4________-VIS006___-000006___-201803031200-__',
'/root/msg_data/H-000-MSG4__-MSG4________-VIS006___-000001___-201803031200-__', 
'/root/msg_data/H-000-MSG4__-MSG4________-VIS006___-000005___-201803031200-__', 
'/root/msg_data/H-000-MSG4__-MSG4________-VIS006___-000007___-201803031200-__', 
'/root/msg_data/H-000-MSG4__-MSG4________-VIS006___-000002___-201803031200-__', 
'/root/msg_data/H-000-MSG4__-MSG4________-VIS006___-000004___-201803031200-__', 
'/root/msg_data/H-000-MSG4__-MSG4________-VIS006___-000008___-201803031200-__', 
'/root/msg_data/H-000-MSG4__-MSG4________-VIS006___-000003___-201803031200-__', 
'/root/msg_data/H-000-MSG4__-MSG4________-_________-PRO______-201803031200-__', 
'/root/msg_data/H-000-MSG4__-MSG4________-_________-EPI______-201803031200-__']
[INFO: 2018-03-15 12:51:30 : hrit_msg] No IMPF configuration field found in prologue.
[DEBUG: 2018-03-15 12:51:30 : satpy.composites] Looking for composites config file seviri.yaml
[DEBUG: 2018-03-15 12:51:30 : satpy.composites] Looking for composites config file visir.yaml
[WARNING: 2018-03-15 12:51:30 : satpy.readers.yaml_reader] Required file type 'HRIT_HRV' not found or loaded for 'HRV'
[WARNING: 2018-03-15 12:51:30 : satpy.scene] The following datasets were not created: DatasetID(name='HRV', wavelength=(0.5, 0.7, 0.9), resolution=1000.134348869, polarization=None, calibration='reflectance', modifiers=())
Traceback (most recent call last):
  File "test_msg.py", line 18, in <module>
    print(global_scene[0.6])
  File "/usr/lib/python2.7/site-packages/satpy/scene.py", line 341, in __getitem__
    return self.datasets[key]
  File "/usr/lib/python2.7/site-packages/satpy/readers/__init__.py", line 183, in __getitem__
    raise KeyError("No dataset matching '{}' found".format(str(item)))
KeyError: "No dataset matching '0.6' found"
```

Below is my python script.

```python
from satpy.scene import Scene
from datetime import datetime, timedelta
from netCDF4 import Dataset
from glob import glob
import numpy as np
from pyproj import Proj
from satpy.writers import Writer, DecisionTree, scmi
from pyresample.geometry import AreaDefinition

from satpy.utils import debug_on
debug_on()

FILES = glob("/root/msg_data/H-000*")

global_scene = Scene(reader='hrit_msg',filenames=FILES)

global_scene.load([0.6])
print(global_scene[0.6])
print(global_scene[0.6].info)

global_scene.save_datasets(writer='scmi', sector_id="Europe", source_name="AWIPS", filename='AWIPS_AII_MET11_SEVIRI_VIS006_GEOS_01.nc')
```

**Comment by WxmanJ** [comment]
This issue has been resolved. It was a syntax issue regarding the reader.

**Comment by davidh-ssec** [comment]
A syntax error *in* the reader? Or a syntax error in the way you were calling something?

**Comment by WxmanJ** [comment]
The way I was calling a feature.
