### ISSUE TITLE
Native resampler fails for (some) GEO readers due to reduce_data=True

### ISSUE THREAD

**Issue by ameraner** [pytroll/satpy#2476]
**Describe the bug**
The `native` resampler fails when trying to resampler GEO data onto grids (with the same projection).
This is solved by deactivateding the data reduction (`scn_r = scn.resample('mtg_fci_fdss_1km', resampler='native', reduce_data=False)`).
A plausible theory when looking at the code is that the `reduce_data` crops the deep space pixels around the disk, ending up with the slightly smaller array shape that then doesn't match anymore. The slices returned from get_area_slices here https://github.com/pytroll/satpy/blob/2ec18f69a9f19b0cc14fa2429f6707a6fab6dc3a/satpy/scene.py#L914-L915  are `(slice(158, 10998, None), slice(157, 10983, None))`

**To Reproduce**

```python
scn = Scene(filenames=files, reader='fci_l1c_nc')
scn.load(['vis_04'])
scn_resampled = scn.resample('mtg_fci_fdss_1km', resampler='native')
```
Similar failures have been reported by @simonrp84 using AHI data.

**Expected behavior**
Correct resampling.

**Actual results**
```bash
[DEBUG: 2023-05-10 19:25:24 : satpy.scene] Resampling DataID(name='vis_04', wavelength=WavelengthRange(min=0.384, central=0.444, max=0.504, unit='µm'), resolution=1000, calibration=<calibration.reflectance>, modifiers=())
Traceback (most recent call last):
  File "/tcenas/home/andream/PycharmProjects/dev_src/dev_src/local_readers_dev/fci_native_fail_test.py", line 121, in <module>
    scn_r = scn.resample('mtg_fci_fdss_1km', resampler='native')
  File "/tcenas/home/andream/code/satpy_latest/satpy/satpy/scene.py", line 954, in resample
    self._resampled_scene(new_scn, destination, resampler=resampler,
  File "/tcenas/home/andream/code/satpy_latest/satpy/satpy/scene.py", line 870, in _resampled_scene
    res = resample_dataset(dataset, destination_area, **kwargs)
  File "/tcenas/home/andream/code/satpy_latest/satpy/satpy/resample.py", line 1433, in resample_dataset
    new_data = resample(source_area, dataset, destination_area, fill_value=fill_value, **kwargs)
  File "/tcenas/home/andream/code/satpy_latest/satpy/satpy/resample.py", line 1396, in resample
    res = resampler_instance.resample(data, **kwargs)
  File "/tcenas/home/andream/code/satpy_latest/satpy/satpy/resample.py", line 991, in resample
    return super(NativeResampler, self).resample(data,
  File "/tcenas/home/andream/code/satpy_latest/satpy/satpy/resample.py", line 449, in resample
    return self.compute(data, cache_id=cache_id, **kwargs)
  File "/tcenas/home/andream/code/satpy_latest/satpy/satpy/resample.py", line 1042, in compute
    d_arr = self._expand_reduce(data.data, repeats)
  File "/tcenas/home/andream/code/satpy_latest/satpy/satpy/resample.py", line 1004, in _expand_reduce
    return _replicate(d_arr, repeats)
  File "/tcenas/home/andream/code/satpy_latest/satpy/satpy/resample.py", line 1086, in _replicate
    repeated_chunks = _get_replicated_chunk_sizes(d_arr, repeats)
  File "/tcenas/home/andream/code/satpy_latest/satpy/satpy/resample.py", line 1099, in _get_replicated_chunk_sizes
    raise ValueError("Expand factor must be a whole number")
ValueError: Expand factor must be a whole number
```

**Additional context**
```
scn["vis_04"].attrs["area"].crs == get_area_def("mtg_fci_fdss_1km").crs
Out[2]: False
get_area_def("mtg_fci_fdss_1km").crs
Out[3]: 
<Derived Projected CRS: PROJCRS["unknown",BASEGEOGCRS["unknown",DATUM["Unk ...>
Name: unknown
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- undefined
Coordinate Operation:
- name: unknown
- method: Geostationary Satellite (Sweep Y)
Datum: Unknown based on WGS84 ellipsoid
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

scn["vis_04"].attrs["area"].crs
Out[4]: 
<Derived Projected CRS: PROJCRS["unknown",BASEGEOGCRS["unknown",DATUM["unk ...>
Name: unknown
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- undefined
Coordinate Operation:
- name: unknown
- method: Geostationary Satellite (Sweep Y)
Datum: unknown
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich
```

This was reported and discussed with @djhoese around here on Slack https://pytroll.slack.com/archives/C0LNH7LMB/p1682076158103019?thread_ts=1681293614.646929&cid=C0LNH7LMB .

**Comment by djhoese** [comment]
I've had trouble reproducing this, but my biggest confusion is that the AreaDefinition area slices logic should be checking if the two CRSes (of the source area and the target area) are the same:

https://github.com/pytroll/pyresample/blob/0bc1a0b47220bf9225b8448121ec0c7e930476bf/pyresample/geometry.py#L2576-L2579

And then doing pretty simple math after that. The fancy geostationary logic only happens if the CRSes are not the same. So we need a case where this is broken and see how/why the CRSes aren't equal.

Can someone get me AHI or FCI or some other data that fails this reduce_data=True default case? I don't think I was able to reproduce it on my machine. Has anyone noticed something specific to an operating system for this?

**Comment by ameraner** [comment]
https://sftp.eumetsat.int/public/folder/UsCVknVOOkSyCdgpMimJNQ/User-Materials/Test-Data/MTG/MTG_FCI_L1C_SpectrallyRepresentative_TD-360_May2022/UNCOMPRESSED/RCRC0072.zip you can download a FCI test data full-disk from here.

**Comment by djhoese** [comment]
So loading the area from the YAML and loading the area for the vis04 band in your example code shows that the datums for the CRSes are not equal. It is possible they used to be, but PROJ seems to want to take the `a` and the `rf` from the PROJ.4 dict in the reader and say "this is some unknown WGS84 definition". 

```
In [9]: scn['vis_04'].attrs['area'].crs.datum
Out[9]: 
DATUM["unknown",
    ELLIPSOID["WGS 84",6378137,298.257223563,
        LENGTHUNIT["metre",1,
            ID["EPSG",9001]]]]
```

But for the YAML area it either says it is 

```
In [20]: area_def.crs.datum
Out[20]: 
DATUM["Unknown based on WGS84 ellipsoid",
    ELLIPSOID["WGS 84",6378137,298.257223563,
        LENGTHUNIT["metre",1],
        ID["EPSG",7030]]]
```

Or if I add `datum: 'WGS84'` to the YAML I get:

```
In [8]: area_def.crs.datum
Out[8]: 
DATUM["World Geodetic System 1984",
    ELLIPSOID["WGS 84",6378137,298.257223563,
        LENGTHUNIT["metre",1]],
    ID["EPSG",6326]]
```

I'll have to ask pyproj for help.

**Comment by djhoese** [comment]
https://github.com/pyproj4/pyproj/discussions/1284

**Comment by djhoese** [comment]
The way you ran your code @gerritholl makes me think you have different amounts of data between the various bands. That is, padding being off and resampling taking the finest resolution area, I would assume some areas aren't equal and that's causing the problems. Can you print out the areas after `sc.load`?

**Comment by simonrp84** [comment]
I've also seen this with FCI, even when I have all segments. Perhaps some rounding error in the area defs for the different resolutions? I vaguely recall that Himawari used to have a similar issue that was solved with some rounding logic or somehting like that...

**Comment by gerritholl** [comment]
Also happens to LEO, in this case Landsat:

```
from satpy import Scene
from glob import glob
from sattools.io import plotdir
from satpy.utils import debug_on; debug_on()
import os
fns = glob("/home/gholl/Arbeit/misc/landsat/*")
sc = Scene(filenames=fns, reader="oli_tirs_l1_tif")
sc.load(["B11", "dwd_IR_108", "true_color", "cimss_cloud_type"])
ls = sc.resample(resampler="native")
ls.save_datasets(
        filename=os.fspath(plotdir() /
                            "{platform_name}-{sensor}-{area.area_id}-{name}-{start_time:%Y%m%d%H%M%S}-{end_time:%Y%m%d%H%M%S}.tif"))
```

**Comment by gerritholl** [comment]
Areas:

```
In [9]: sc["ir_105"].attrs["area"]
Out[9]:
Area ID: mtg_fci_fdss_1km
Description: MTG FCI Full Disk Scanning Service area definition with 1 km resolution
Projection: {'ellps': 'WGS84', 'h': '35786400', 'lon_0': '0', 'no_defs': 'None', 'proj': 'geos', 'type': 'crs', 'units': 'm', 'x_0': '0', 'y_0': '0'}
Number of columns: 11136
Number of rows: 557
Area extent: (np.float64(-5567999.9986), np.float64(4731999.9988), np.float64(5567999.9986), np.float64(5288999.9986))

[DEBUG: 2024-12-18 10:36:00 : asyncio] Using selector: EpollSelector
In [10]: sc["ir_123"].attrs["area"]
Out[10]:
Area ID: mtg_fci_fdss_2km
Description: MTG FCI Full Disk Scanning Service area definition with 2 km resolution
Projection: {'ellps': 'WGS84', 'h': '35786400', 'lon_0': '0', 'no_defs': 'None', 'proj': 'geos', 'type': 'crs', 'units': 'm', 'x_0': '0', 'y_0': '0'}
Number of columns: 5568
Number of rows: 278
Area extent: (np.float64(-5567999.9942), np.float64(4731999.9951), np.float64(5567999.9942), np.float64(5287999.9945))

[DEBUG: 2024-12-18 10:36:12 : asyncio] Using selector: EpollSelector
In [11]: sc["ir_38"].attrs["area"]
Out[11]:
Area ID: mtg_fci_fdss_1km
Description: MTG FCI Full Disk Scanning Service area definition with 1 km resolution
Projection: {'ellps': 'WGS84', 'h': '35786400', 'lon_0': '0', 'no_defs': 'None', 'proj': 'geos', 'type': 'crs', 'units': 'm', 'x_0': '0', 'y_0': '0'}
Number of columns: 11136
Number of rows: 557
Area extent: (np.float64(-5567999.9986), np.float64(4731999.9988), np.float64(5567999.9986), np.float64(5288999.9986))
```

**Comment by djhoese** [comment]
Where's the extra row coming from on the 1km? 278 * 2 => 556, not 557.

**Comment by gerritholl** [comment]
From the data:

```
$ ncdump -h W_XX-EUMETSAT-Darmstadt,IMG+SAT,MTI1+FCI-1C-RRAD-FDHSI-FD--CHK-BODY--DIS-NC4E_C_EUMT_20241210024051_IDPFI_OPE_20241210023849_20241210023919_N_JLS_O_0016_0038.nc | grep -A3 'group: ir_123'
  group: ir_123 {
    dimensions:
        x = 5568 ;
        y = UNLIMITED ; // (139 currently)
$ ncdump -h W_XX-EUMETSAT-Darmstadt,IMG+SAT,MTI1+FCI-1C-RRAD-HRFI-FD--CHK-BODY--DIS-NC4E_C_EUMT_20241210024051_IDPFI_OPE_20241210023849_20241210023919_N_JLS_O_0016_0038.nc | grep -A3 'group: ir_105'
  group: ir_105_hr {
    dimensions:
        x = 11136 ;
        y = UNLIMITED ; // (279 currently)
```

**Comment by simonrp84** [comment]
Is this a single segment of FCI data? I'm trying to work out why the size is 557...that's not a factor of 5568 or 11136. Do some segments have a size of 556 and others of 557 perhaps, and in this specific case it happens that the size difference is not consistent between bands?

**Comment by gerritholl** [comment]
Yes, this is a single segment.  The case I posted yesterday consisted of two segments.

**Comment by djhoese** [comment]
How are the pixels aligned between resolutions? For example, on ABI it is meant to be 4 250m pixels perfectly aligned with 1 500m, and similarly 4 500m make up 1 1000m pixel. At least that's how we're "allowed" to think about it. How does this work for this FCI data?

**Comment by djhoese** [comment]
> And also for FCI, pixels of different resolutions are fully overlapping, same as Dave is describing for ABI.

@ameraner But how can this be true if there are a different number of rows (unaligned) between resolutions for each segment?

@gerritholl So I guess the main question as far as this issue is concerned is do you get this failure when you have all segments and no padding is used? @simonrp84 You mentioned you've seen it, but how long ago was that and what version of PROJ was installed in your environment? And were you padding or not?

**Comment by ameraner** [comment]
It is always true when all segments are merged together and you get the complete full-disc, as then the single segment sizes don't matter anymore (they will always sum up to the full-disc grid size). 
When having only partial segments this might not work indeed, but in that case you also have different area extents for your partial area between resolutions...

**Comment by gerritholl** [comment]
> So I guess the main question as far as this issue is concerned is do you get this failure when you have all segments and no padding is used?

No.  Only if I have a subset of segments and I avoid using padding.

@ameraner Are the last ten segments (= Q4) guaranteed to be aligned between FDHSI and HRFI even without padding?  That will be relevant in particular for MTG-I2 / RSS data.

**Comment by ameraner** [comment]
Good question, I will check.

**Comment by simonrp84** [comment]
> @simonrp84 You mentioned you've seen it, but how long ago was that and what version of PROJ was installed in your environment? And were you padding or not?

It was a good while ago, maybe last year or even earlier, and I vaguely recall that you made a fix for it. Could be wrong though.
No idea what version of PROJ I had. Wasn't padding as I always have that switched off.

**Comment by ameraner** [comment]
> @ameraner Are the last ten segments (= Q4) guaranteed to be aligned between FDHSI and HRFI even without padding? That will be relevant in particular for MTG-I2 / RSS data.

I got some recent FCI RSS reprocessing data to check, and it turns out the 500m channels are 2 pixel rows too small, which is very painful. I've raised an internal anomaly on this and will try to get it fixed.

**Comment by gerritholl** [comment]
> I got some recent FCI RSS reprocessing data to check, and it turns out the 500m channels are 2 pixel rows too small, which is very painful. I've raised an internal anomaly on this and will try to get it fixed.

Is this always the case or only sometimes?  I tried to load `true_color` from the RSS test data while `pad_data=False`, and native resampling worked:

```
fci_files = glob("/media/nas/x21308/MTG_test_data/RSS/20230723_20230724/20230723/FDHSI/*BODY*20230723*T_0291_*.nc")
sc = Scene(filenames={"fci_l1c_nc": fci_files})
sc.load(["true_color"], pad_data=False)
ls = sc.resample(sc.finest_area(), resampler="native")
ls["true_color"]
```

**Comment by ameraner** [comment]
Looking at your filepath, could it be that you were passing only FDHSI files to the Scene? If you add HRFI, with True Color using the 500m `vis_06`, you should see the issue.

**Comment by gerritholl** [comment]
> Looking at your filepath, could it be that you were passing only FDHSI files to the Scene?

Oops, yes, this is true.

> If you add HRFI, with True Color using the 500m `vis_06`, you should see the issue.

Right:

```python
import hdf5plugin
import os
from satpy import Scene
from satpy.utils import debug_on; debug_on()
from glob import glob
fci_files = glob("/media/nas/x21308/MTG_test_data/RSS/20230723_20230724/20230723/*/*BODY*20230723*T_0291_*.nc")
sc = Scene(filenames={"fci_l1c_nc": fci_files})
sc.load(["true_color"], pad_data=False)
ls = sc.resample(sc.coarsest_area(), resampler="native")
ls.save_datasets()
```

fails.

With `sc.finest_area()` it succeeds.

(I do get an `OSError`, because the data are pretending to be MTG-I2: `OSError: pyspectral RSR file does not exist! Filename = /home/gholl/.local/share/pyspectral/rsr_fci_MTG-I2.h5` — but satpy continues anyway).

**Comment by simon-sat** [comment]
@ameraner Any idea when the SRFs will be made public for MTG-I2?

**Comment by ameraner** [comment]
> @ameraner Any idea when the SRFs will be made public for MTG-I2?

We are waiting for the final SRF delivery this month, then we'll proceed to release it - so soon-ish :)
