### ISSUE TITLE
containment checking on DataQuery fails with KeyError

### ISSUE THREAD

**Issue by gerritholl** [pytroll/satpy#2496]
**Describe the bug**

Checking for containment in a DataQuery fails with KeyError.

**To Reproduce**

```python
from satpy import DataQuery
dq = DataQuery(name="pytroll")
"name" in dq
```

**Expected behavior**

I expect either a TypeError (in case containment checking is not supported) or the answer (True/False).

**Actual results**

```
Traceback (most recent call last):
  File "/data/gholl/checkouts/protocode/mwe/dq-keyerror.py", line 3, in <module>
    "name" in dq
  File "/data/gholl/checkouts/satpy/satpy/dataset/dataid.py", line 512, in __getitem__
    return self._dict[key]
           ~~~~~~~~~~^^^^^
KeyError: 0
```

I don't understand where the `0` is coming from.

**Environment Info:**
 - Satpy Version: main

**Additional context**

I want to test if a `DataQuery` contains a time parameter in my attempt of implementing temporal composites at https://github.com/pytroll/satpy/pull/2495.

Workaround:

```python
"name" in dq.to_dict()
```

**Comment by djhoese** [comment]
Yeah I guess it would make sense to have this functionality available and treat it as a "frozen dict".
