### ISSUE TITLE
Can we disable/delete all the 'modifiers' in viirs_sdr reader?

### ISSUE THREAD

**Issue by yukaribbba** [pytroll/satpy#2541]
**Describe the bug**
Those "sunz_corrected" and "sunz_corrected_iband" in visible bands cause problems when I tried to rename them in my own composite config file. After disable those lines I got things running again. I think they should only appear in composites not readers.

```
[DEBUG: 2023-08-10 18:01:22 : satpy.readers.yaml_reader] Reading ('C:\\Users\\45107\\miniforge3\\Lib\\site-packages\\satpy\\etc\\readers\\viirs_sdr.yaml',)
[DEBUG: 2023-08-10 18:01:22 : h5py._conv] Creating converter from 7 to 5
[DEBUG: 2023-08-10 18:01:22 : h5py._conv] Creating converter from 5 to 7
[DEBUG: 2023-08-10 18:01:22 : h5py._conv] Creating converter from 7 to 5
[DEBUG: 2023-08-10 18:01:22 : h5py._conv] Creating converter from 5 to 7
C:\Users\45107\miniforge3\Lib\site-packages\satpy\utils.py:610: UserWarning: The PYTROLL_CHUNK_SIZE environment variable is pending deprecation. You can use the dask config setting `array.chunk-size` (or the DASK_ARRAY__CHUNK_SIZE environment variable) and set it to the square of the PYTROLL_CHUNK_SIZE instead.
  chunk_size = _get_pytroll_chunk_size()
[DEBUG: 2023-08-10 18:01:22 : satpy.readers.yaml_reader] Reading ('C:\\Users\\45107\\miniforge3\\Lib\\site-packages\\satpy\\etc\\readers\\viirs_sdr.yaml',)
[DEBUG: 2023-08-10 18:01:22 : satpy.readers.yaml_reader] Assigning to viirs_sdr: ['C:/Users/45107/Downloads/Sat/Polar\\SVI02_j02_d20230801_t0426135_e0427382_b03744_c20230808071024903530_oebc_ops.h5', 'C:/Users/45107/Downloads/Sat/Polar\\SVM13_j02_d20230801_t0426135_e0427382_b03744_c20230808071304853942_oebc_ops.h5', 'C:/Users/45107/Downloads/Sat/Polar\\SVM12_j02_d20230801_t0426135_e0427382_b03744_c20230808071244505222_oebc_ops.h5', 'C:/Users/45107/Downloads/Sat/Polar\\SVM10_j02_d20230801_t0426135_e0427382_b03744_c20230808071237747157_oebc_ops.h5', 'C:/Users/45107/Downloads/Sat/Polar\\GMTCO_j02_d20230801_t0426135_e0427382_b03744_c20230808071026645756_oebc_ops.h5', 'C:/Users/45107/Downloads/Sat/Polar\\SVM03_j02_d20230801_t0426135_e0427382_b03744_c20230808071247185963_oebc_ops.h5', 'C:/Users/45107/Downloads/Sat/Polar\\SVM07_j02_d20230801_t0426135_e0427382_b03744_c20230808071305747916_oebc_ops.h5', 'C:/Users/45107/Downloads/Sat/Polar\\SVM15_j02_d20230801_t0426135_e0427382_b03744_c20230808071250769114_oebc_ops.h5', 'C:/Users/45107/Downloads/Sat/Polar\\SVM16_j02_d20230801_t0426135_e0427382_b03744_c20230808071257877351_oebc_ops.h5', 'C:/Users/45107/Downloads/Sat/Polar\\SVM05_j02_d20230801_t0426135_e0427382_b03744_c20230808071240609433_oebc_ops.h5', 'C:/Users/45107/Downloads/Sat/Polar\\SVM01_j02_d20230801_t0426135_e0427382_b03744_c20230808071238982453_oebc_ops.h5', 'C:/Users/45107/Downloads/Sat/Polar\\SVM04_j02_d20230801_t0426135_e0427382_b03744_c20230808071307478620_oebc_ops.h5', 'C:/Users/45107/Downloads/Sat/Polar\\SVM14_j02_d20230801_t0426135_e0427382_b03744_c20230808071253179009_oebc_ops.h5', 'C:/Users/45107/Downloads/Sat/Polar\\GITCO_j02_d20230801_t0426135_e0427382_b03744_c20230808071009877532_oebc_ops.h5', 'C:/Users/45107/Downloads/Sat/Polar\\SVM09_j02_d20230801_t0426135_e0427382_b03744_c20230808071244500745_oebc_ops.h5', 'C:/Users/45107/Downloads/Sat/Polar\\SVI05_j02_d20230801_t0426135_e0427382_b03744_c20230808071023313183_oebc_ops.h5', 'C:/Users/45107/Downloads/Sat/Polar\\SVI04_j02_d20230801_t0426135_e0427382_b03744_c20230808071304511400_oebc_ops.h5', 'C:/Users/45107/Downloads/Sat/Polar\\SVM06_j02_d20230801_t0426135_e0427382_b03744_c20230808071303315677_oebc_ops.h5', 'C:/Users/45107/Downloads/Sat/Polar\\SVI01_j02_d20230801_t0426135_e0427382_b03744_c20230808071026512090_oebc_ops.h5', 'C:/Users/45107/Downloads/Sat/Polar\\SVM08_j02_d20230801_t0426135_e0427382_b03744_c20230808071302707857_oebc_ops.h5', 'C:/Users/45107/Downloads/Sat/Polar\\SVI03_j02_d20230801_t0426135_e0427382_b03744_c20230808071010052587_oebc_ops.h5', 'C:/Users/45107/Downloads/Sat/Polar\\SVM02_j02_d20230801_t0426135_e0427382_b03744_c20230808071306387281_oebc_ops.h5', 'C:/Users/45107/Downloads/Sat/Polar\\SVM11_j02_d20230801_t0426135_e0427382_b03744_c20230808071307982108_oebc_ops.h5']
[DEBUG: 2023-08-10 18:01:22 : satpy.composites.config_loader] Looking for composites config file viirs.yaml
[DEBUG: 2023-08-10 18:01:22 : pyorbital.tlefile] Path to the Pyorbital configuration (where e.g. platforms.txt is found): C:\Users\45107\miniforge3\Lib\site-packages\pyorbital\etc
C:\Users\45107\miniforge3\Lib\site-packages\pyspectral\__init__.py:22: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import DistributionNotFound, get_distribution
[DEBUG: 2023-08-10 18:01:22 : satpy.composites.config_loader] Looking for composites config file visir.yaml
[DEBUG: 2023-08-10 18:01:22 : satpy.composites.config_loader] No composite config found called visir.yaml
Traceback (most recent call last):
  File "C:\Users\45107\miniforge3\Lib\site-packages\satpy\scene.py", line 1451, in _update_dependency_tree
    self._dependency_tree.populate_with_keys(needed_datasets, query)
  File "C:\Users\45107\miniforge3\Lib\site-packages\satpy\dependency_tree.py", line 262, in populate_with_keys
    raise MissingDependencies(unknown_datasets, "Unknown datasets:")
satpy.node.MissingDependencies: Unknown datasets: {DataQuery(name='M05', modifiers=('sunz_corrected_750', 'rayleigh_corrected_crefl_750')): {DataQuery(name='M05', modifiers=())}, DataQuery(name='M04', modifiers=('sunz_corrected_750', 'rayleigh_corrected_crefl_750')): {DataQuery(name='M04', modifiers=())}, DataQuery(name='M03', modifiers=('sunz_corrected_750', 'rayleigh_corrected_crefl_750')): {DataQuery(name='M03', modifiers=())}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\45107\PycharmProjects\Satellite\ddddddd.py", line 19, in <module>
    scn.load(["true_color_375"])
  File "C:\Users\45107\miniforge3\Lib\site-packages\satpy\scene.py", line 1439, in load
    self._update_dependency_tree(needed_datasets, query)
  File "C:\Users\45107\miniforge3\Lib\site-packages\satpy\scene.py", line 1453, in _update_dependency_tree
    raise KeyError(str(err))
KeyError: "Unknown datasets: {DataQuery(name='M05', modifiers=('sunz_corrected_750', 'rayleigh_corrected_crefl_750')): {DataQuery(name='M05', modifiers=())}, DataQuery(name='M04', modifiers=('sunz_corrected_750', 'rayleigh_corrected_crefl_750')): {DataQuery(name='M04', modifiers=())}, DataQuery(name='M03', modifiers=('sunz_corrected_750', 'rayleigh_corrected_crefl_750')): {DataQuery(name='M03', modifiers=())}}"
```

**Comment by pnuu** [comment]
If you take a copy of `satpy/etc/readers/viirs_sdr.yaml` and put it in a custom directory, lets say `C:\\Users\\45107\\satpy_config_path\\etc\\readers\\` and set `os.environ['SATPY_CONFIG_PATH'] = 'C:\\Users\\45107\\satpy_config_path'` before importing Satpy in your script, you can then remove the modifiers from the config and it will override the built-in reader config and you'll be able to read the channels unmodified.

I'm not entirely sure why the modifiers are set in the reader config, though.

**Comment by yukaribbba** [comment]
I see. I use `satpy.config` to set my own config so that's why it's not overrided. Thanks!

**Comment by djhoese** [comment]
We can keep commenting on different ways you could accomplish what you're trying to accomplish, but the answer to the initial request of this issue of removing the modifiers from the reader is: no.

**Comment by yukaribbba** [comment]
Got it. Thanks for this detailed explanation! :}
