### ISSUE TITLE
Binaries gone from PyPI and source is not building with pip

### ISSUE THREAD

**Issue by marty-sullivan** [pytroll/satpy#2576]
**Describe the bug**
Between yesterday and today, it seems like there are no longer any prebuilt wheels available for satpy & pyspectral on PyPI. 

In addition, it seems the source is unable to build. It seems the error stems from latest versions of `setuptools_scm>=8` not supporting functionality used by satpy/pyspectral build process

**To Reproduce**

```shell
pip install satpy
pip install pyspectral
```

**Expected behavior**
1. To have prebuilt binaries available for supported platforms
2. To have the satpy & pyspectral packages build from source via `pip install` without error

**Actual results**
Text output of actual results or error messages including full tracebacks if applicable.

```shell
$ pip install satpy
Collecting satpy
  Using cached satpy-0.43.0.tar.gz (1.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [58 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-hcld8jiy/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 396, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-hcld8jiy/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 131, in <module>
        File "/tmp/pip-build-env-hcld8jiy/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-hcld8jiy/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
                                       ^^^^^^^^^^^^
        File "/tmp/pip-build-env-hcld8jiy/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 303, in __init__
          _Distribution.__init__(self, dist_attrs)
        File "/tmp/pip-build-env-hcld8jiy/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
          self.finalize_options()
        File "/tmp/pip-build-env-hcld8jiy/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 680, in finalize_options
          ep(self)
        File "/tmp/pip-build-env-hcld8jiy/overlay/lib/python3.11/site-packages/setuptools_scm/_integration/setuptools.py", line 125, in infer_version
          _assign_version(dist, config)
        File "/tmp/pip-build-env-hcld8jiy/overlay/lib/python3.11/site-packages/setuptools_scm/_integration/setuptools.py", line 54, in _assign_version
          maybe_version = _get_version(config, force_write_version_files=True)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-hcld8jiy/overlay/lib/python3.11/site-packages/setuptools_scm/_get_version_impl.py", line 89, in _get_version
          parsed_version = parse_version(config)
                           ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-hcld8jiy/overlay/lib/python3.11/site-packages/setuptools_scm/_get_version_impl.py", line 52, in parse_version
          or parse_scm_version(config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-hcld8jiy/overlay/lib/python3.11/site-packages/setuptools_scm/_get_version_impl.py", line 37, in parse_scm_version
          return _entrypoints.version_from_entrypoint(config, entrypoint, root)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-hcld8jiy/overlay/lib/python3.11/site-packages/setuptools_scm/_entrypoints.py", line 37, in version_from_entrypoint
          fn: ParseFunction = ep.load()
                              ^^^^^^^^^
        File "/usr/local/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
          module = import_module(match.group('module'))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 940, in exec_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "/tmp/pip-build-env-hcld8jiy/overlay/lib/python3.11/site-packages/setuptools_scm_git_archive/__init__.py", line 6, in <module>
          from setuptools_scm.utils import data_from_mime, trace
      ModuleNotFoundError: No module named 'setuptools_scm.utils'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Environment Info:**
 - OS: MacOS and Linux (Debian Bullseye), build fails in both
 - Satpy Version: 0.43.0

**Comment by djhoese** [comment]
Thanks. Known issue. See:

https://github.com/pytroll/pyspectral/pull/197
https://github.com/pytroll/satpy/pull/2575

Note: there were never wheels. These packages are pure python. I'll have to think about how to fix the PyPI installation.

**Comment by djhoese** [comment]
https://github.com/pypa/setuptools_scm/issues/914

It is that `setuptools_scm_git_archive` is deprecated and some of our packages haven't moved away from it.

**Comment by marty-sullivan** [comment]
@djhoese I went ahead and put in PR https://github.com/pytroll/satpy/pull/2577.

This seems to fix the build via pip for me, at least locally

**Comment by djhoese** [comment]
Thanks but I'm not sure there is a need for that with my PR linked above.

**Comment by marty-sullivan** [comment]
yes, i had missed that you already had a PR addressing this. As it is, my build processes are hosed for satpy & pyspectral using PyPI but I can point pip to my own repos in the meantime

**Comment by djhoese** [comment]
Good idea. My goal is to fix this in the next hour or two. I think I'll steal your commit from your PR and apply it to a new "maintenance" branch so we don't have to be concerned about what PRs are being released in Satpy. First...I need to get pyspectral figured out.
