### ISSUE TITLE
Race condition while caching for resampling

### ISSUE THREAD

**Issue by adybbroe** [pytroll/satpy#2636]
**Describe the bug**
I think there could be an issue with caching for resampling when two similar processes are running in parallel using threading.

**To Reproduce**

```python
# Your code here

```

**Expected behavior**

**Actual results**
Text output of actual results or error messages including full tracebacks if applicable.

```
[2023-11-13 07:30:40,020 ERROR    __main__] Failed in ctth_composite_worker...
Traceback (most recent call last):
  File "/san1/opt/mesan-composite-runner/releases/mesan-composite-runner-0.1.15/lib/python3.11/site-packages/satpy/resample.py", line 589, in load_neighbour_info
    fid = zarr.open(filename, 'r')
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/san1/opt/mesan-composite-runner/releases/mesan-composite-runner-0.1.15/lib/python3.11/site-packages/zarr/convenience.py", line 130, in open
    raise PathNotFoundError(path)
zarr.errors.PathNotFoundError: nothing found at path ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/san1/opt/mesan-composite-runner/releases/mesan-composite-runner-0.1.15/lib/python3.11/site-packages/satpy/resample.py", line 510, in precompute
    self.load_neighbour_info(cache_dir, mask=mask, **kwargs)
  File "/san1/opt/mesan-composite-runner/releases/mesan-composite-runner-0.1.15/lib/python3.11/site-packages/satpy/resample.py", line 595, in load_neighbour_info
    raise IOError
OSError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/san1/opt/mesan-composite-runner/releases/mesan-composite-runner-0.1.15/bin/mesan_composite_runner.py", line 390, in ctth_composite_worker
    result_file = do_ctth_composite(time_of_analysis, delta_t, mesan_area_id, config_options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/san1/opt/mesan-composite-runner/releases/mesan-composite-runner-0.1.15/bin/mesan_composite_runner.py", line 570, in do_ctth_composite
    ctcomp.blend_cloud_products()
  File "/san1/opt/mesan-composite-runner/releases/mesan-composite-runner-0.1.15/lib/python3.11/site-packages/mesan_compositer/make_ct_composite.py", line 336, in blend_cloud_products
    self.blended_scene, group_name = blend_cloud_products(satpy_composite_name,
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/san1/opt/mesan-composite-runner/releases/mesan-composite-runner-0.1.15/lib/python3.11/site-packages/mesan_compositer/load_cloud_products.py", line 207, in blend_cloud_products
    for _i, scene in enumerate(resampled.scenes):
                               ^^^^^^^^^^^^^^^^
  File "/san1/opt/mesan-composite-runner/releases/mesan-composite-runner-0.1.15/lib/python3.11/site-packages/satpy/multiscene/_multiscene.py", line 255, in scenes
    self._scenes = list(self._scenes)
                   ^^^^^^^^^^^^^^^^^^
  File "/san1/opt/mesan-composite-runner/releases/mesan-composite-runner-0.1.15/lib/python3.11/site-packages/satpy/multiscene/_multiscene.py", line 145, in __iter__
    scn = next(self._self_iter)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/san1/opt/mesan-composite-runner/releases/mesan-composite-runner-0.1.15/lib/python3.11/site-packages/satpy/multiscene/_multiscene.py", line 135, in _create_cached_iter
    for scn in self._scene_gen:
  File "/san1/opt/mesan-composite-runner/releases/mesan-composite-runner-0.1.15/lib/python3.11/site-packages/satpy/multiscene/_multiscene.py", line 297, in _call_scene_func
    new_scn = getattr(scn, func_name)(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/san1/opt/mesan-composite-runner/releases/mesan-composite-runner-0.1.15/lib/python3.11/site-packages/satpy/scene.py", line 977, in resample
    self._resampled_scene(new_scn, destination, resampler=resampler,
  File "/san1/opt/mesan-composite-runner/releases/mesan-composite-runner-0.1.15/lib/python3.11/site-packages/satpy/scene.py", line 893, in _resampled_scene
    res = resample_dataset(dataset, destination_area, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/san1/opt/mesan-composite-runner/releases/mesan-composite-runner-0.1.15/lib/python3.11/site-packages/satpy/resample.py", line 1454, in resample_dataset
    new_data = resample(source_area, dataset, destination_area, fill_value=fill_value, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/san1/opt/mesan-composite-runner/releases/mesan-composite-runner-0.1.15/lib/python3.11/site-packages/satpy/resample.py", line 1417, in resample
    res = resampler_instance.resample(data, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/san1/opt/mesan-composite-runner/releases/mesan-composite-runner-0.1.15/lib/python3.11/site-packages/satpy/resample.py", line 441, in resample
      cache_id = self.precompute(cache_dir=cache_dir, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/san1/opt/mesan-composite-runner/releases/mesan-composite-runner-0.1.15/lib/python3.11/site-packages/satpy/resample.py", line 515, in precompute
    self.save_neighbour_info(cache_dir, mask=mask, **kwargs)
  File "/san1/opt/mesan-composite-runner/releases/mesan-composite-runner-0.1.15/lib/python3.11/site-packages/satpy/resample.py", line 619, in save_neighbour_info
    zarr_out.to_zarr(filename)
  File "/san1/opt/mesan-composite-runner/releases/mesan-composite-runner-0.1.15/lib/python3.11/site-packages/xarray/core/dataset.py", line 2490, in to_zarr
    return to_zarr(  # type: ignore[call-overload,misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/san1/opt/mesan-composite-runner/releases/mesan-composite-runner-0.1.15/lib/python3.11/site-packages/xarray/backends/api.py", line 1666, in to_zarr
    zstore = backends.ZarrStore.open_group(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/san1/opt/mesan-composite-runner/releases/mesan-composite-runner-0.1.15/lib/python3.11/site-packages/xarray/backends/zarr.py", line 456, in open_group
    zarr_group = zarr.open_group(store, **open_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/san1/opt/mesan-composite-runner/releases/mesan-composite-runner-0.1.15/lib/python3.11/site-packages/zarr/hierarchy.py", line 1547, in open_group
    raise ContainsGroupError(path)
zarr.errors.ContainsGroupError: path '' contains a group

```
**Screenshots**

**Environment Info:**
 - OS: [e.g. OSX, Windows, Linux]
 - Satpy Version: [e.g. 0.9.0]
 - PyResample Version:
 - Readers and writers dependencies (when relevant): [run `from satpy.utils import check_satpy; check_satpy()`]

**Additional context**

**Comment by djhoese** [comment]
Satpy's Scene object has no intention of being thread or multiprocess safe, but for basic usage like this I would have expected it to work. Maybe if the multi-processing was done with dask that might work, but still I'm not sure. However, the resampling caching is not intended to work for multiple writers. The suggestion has always been to pre-seed the cache by running processing once, then do any parallel processing after that.

Is the `scene` here a MultiScene or a regular Scene?

If a `Scene`, then I'm not sure I understand the benefit of splitting it at this stage in the processing (before resampling). Aren't you using the same resampled output in both cases? Why not resample the Scene and then pass that resampled Scene to the remaining processing?

If a `MultiScene` then I think the better long term solution would be to make Scene iterations done in parallel (with dask, but just for consistency). Basically, move the parallel portions of the code inside the code and not something the user has to worry about.
