### ISSUE TITLE
Weird problem in `pyresample` newer version for the `VIIRS` data

### ISSUE THREAD

**Issue by anikfal** [pytroll/satpy#2649]
I'm using `pyresample` by the same code and on the same files, but in two separate workflows:

**Code:**
```python
from satpy.scene import Scene

main375 = "VJ102IMG_NRT.A2023327.0830.021.nc"
geo375  = "VJ103IMG_NRT.A2023327.0830.021.nc"
main750 = "VJ102MOD_NRT.A2023327.0830.021.nc"
geo750  = "VJ103MOD_NRT.A2023327.0830.021.nc"
scn = Scene(reader='viirs_l1b', filenames=[main375, main750, geo375, geo750])
scn.load(["I01"])
my_area = scn["I01"].attrs['area'].compute_optimal_bb_area({'proj': 'lcc', 'lon_0': 35., 'lat_0': 50., 'lat_1': 50., 'lat_2': 50.})
```

**Workflow 1 (no problem without errors):**
OS: CentOS 7
satpy version: 0.28.0
pyresample version: 1.19.0

**Workflow 2 (with errors):**
OS: CentOS 7
satpy version: 0.43.0.post0
pyresample version: 1.27.1
**Errors for workflow 2**:
```
/home/sebal/miniconda3/envs/mysat/lib/python3.10/site-packages/xarray/core/dataset.py:270: UserWarning: The specified chunks separate the stored chunks along dimension "number_of_pixels" starting at index 4096. This could degrade performance. Instead, consider rechunking after loading.
  warnings.warn(
/home/sebal/miniconda3/envs/mysat/lib/python3.10/site-packages/xarray/core/dataset.py:270: UserWarning: The specified chunks separate the stored chunks along dimension "number_of_pixels" starting at index 4096. This could degrade performance. Instead, consider rechunking after loading.
  warnings.warn(
/home/sebal/miniconda3/envs/mysat/lib/python3.10/site-packages/xarray/core/dataset.py:270: UserWarning: The specified chunks separate the stored chunks along dimension "number_of_pixels" starting at index 4096. This could degrade performance. Instead, consider rechunking after loading.
  warnings.warn(
/home/sebal/miniconda3/envs/mysat/lib/python3.10/site-packages/xarray/core/dataset.py:270: UserWarning: The specified chunks separate the stored chunks along dimension "number_of_LUT_values" starting at index 4096. This could degrade performance. Instead, consider rechunking after loading.
  warnings.warn(
Traceback (most recent call last):
  File "/home/sebal/app/viirs_make/zzz/reserve/band_maker.py", line 9, in <module>
    my_area = scn["I01"].attrs['area'].compute_optimal_bb_area({'proj': 'lcc', 'lon_0': 35., 'lat_0': 50., 'lat_1': 50., 'lat_2': 50.})
  File "/home/sebal/miniconda3/envs/mysat/lib/python3.10/site-packages/pyresample/geometry.py", line 990, in compute_optimal_bb_area
    lons, lats = self.get_edge_lonlats()
  File "/home/sebal/miniconda3/envs/mysat/lib/python3.10/site-packages/pyresample/geometry.py", line 420, in get_edge_lonlats
    lons, lats = self.get_bbox_lonlats(frequency=frequency, force_clockwise=False)
  File "/home/sebal/miniconda3/envs/mysat/lib/python3.10/site-packages/pyresample/geometry.py", line 331, in get_bbox_lonlats
    lons, lats = self._get_bbox_elements(self.get_lonlats, frequency)
  File "/home/sebal/miniconda3/envs/mysat/lib/python3.10/site-packages/pyresample/geometry.py", line 350, in _get_bbox_elements
    clean_dim1, clean_dim2 = self._filter_bbox_nans(dim1, dim2)
  File "/home/sebal/miniconda3/envs/mysat/lib/python3.10/site-packages/pyresample/geometry.py", line 363, in _filter_bbox_nans
    raise ValueError("Can't compute swath bounding coordinates. At least one side is completely invalid.")
ValueError: Can't compute swath bounding coordinates. At least one side is completely invalid.
```
---------
This problem occurs occasionally. Perhaps once per month or even less.
if I apply the code on some other `VIIRS` data, there won't be any errors. For example the files below:
```
VJ102IMG_NRT.A2023327.1012.021.nc
VJ102MOD_NRT.A2023327.1012.021.nc
VJ103IMG_NRT.A2023327.1012.021.nc
VJ103MOD_NRT.A2023327.1012.021.nc
```

**Comment by djhoese** [comment]
Thanks for filing the bug. Obviously a lot has changed between the versions of the libraries you're using (thanks for including that version information in your description).

In the old workflow, could you print out what `scn["I01"].attrs["area"].get_edge_lonlats()` and paste it here? My guess (hope?) is that although it maybe returned something that was used by the `compute_optimal_bb_area` that it was actually producing an inefficient/incorrect/inaccurate result. That would at least justify why the new version errors out and doesn't produce anything: it knows that the result isn't good or accurate.

NaNs in VIIRS or MODIS or other polar-orbiters is very common, especially on the first or last granule of a satellite pass. Unfortunately there usually/currently isn't a good way to deal with them while also having decent performance (not computing/loading every lon/lat and doing a min/max on them). I'll take a look at the methods involved after I have more information from you.

**Comment by anikfal** [comment]
Your right. Thanks. The data seems to be corrupted:
`scn["I01"].attrs["area"].get_edge_lonlats()`
> (masked_array(data=[nan, nan, nan, ..., nan, nan, nan],
>              mask=False,
>        fill_value=1e+20,
>             dtype=float32), masked_array(data=[nan, nan, nan, ..., nan, nan, nan],
>              mask=False,
>        fill_value=1e+20,
>             dtype=float32))

This is the first time I come across to a corrupted `VIIRS` data. However, that was interesting that `pyresample` v1.19.0 could handle or skip it, so the workflow was not terminated.

![pyresample](https://github.com/pytroll/satpy/assets/11738727/d556d3df-24d1-4ab8-b8a0-35813e37291d)

**Comment by djhoese** [comment]
Could you print out `my_area` for me? That is, the result of the omerc operations? Does the final image for that operation look OK?

**Comment by anikfal** [comment]
Sure. I insert the output image displayed by QGIS.
`pyresample` v1.19.0 could at least make a GeoTIFF for the valid pixels (upper rows). The image, if was not corrupted, was supposed to cover eastern regions of Iran.

`my_area = scn["I01"].attrs['area'].compute_optimal_bb_area({'proj': 'lcc', 'lon_0': 35., 'lat_0': 50., 'lat_1': 50., 'lat_2': 50.})`
> /home/sebal/miniconda3/envs/mysat/lib/python3.9/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
>   proj_string = self.to_proj4()
```
new_scn = scn.resample(my_area)
new_scn.save_datasets(writer='geotiff', dtype=np.float32, enhance=False)
```

![pyresample_tiff](https://github.com/pytroll/satpy/assets/11738727/79de70a9-773b-4ade-b9ee-f65ccac8e225)

**Comment by djhoese** [comment]
Sorry, I meant `print(my_area)`.

**Comment by anikfal** [comment]
`print(my_area)`
```
/home/sebal/miniconda3/envs/mysat/lib/python3.9/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
Area ID: lcc_otf
Description: On-the-fly lcc area
Projection: {'ellps': 'WGS84', 'lat_0': '50', 'lat_1': '50', 'lat_2': '50', 'lon_0': '35', 'no_defs': 'None', 'proj': 'lcc', 'type': 'crs', 'units': 'm', 'x_0': '0', 'y_0': '0'}
Number of columns: 16936
Number of rows: 6969
Area extent: (89458.8947, -725329.4873, 3348658.0572, 1987300.0824)
```

**Comment by anikfal** [comment]
Here are the extra information for the corrupted `VIIRS` data, by `pyresample` v1.19.0. Let me know if more details are required.

```python
lons, lats = scn["I01"].attrs["area"].get_edge_lonlats()
print(lons), print(lats)
```
> [nan nan nan ... nan nan nan]
> [nan nan nan ... nan nan nan]

`print( lons.shape ), print( lats.shape )`
> (25472,)
> (25472,)

`np.all( np.isnan(lons) ), np.all( np.isnan(lats) )`
> (False, False)

```python
sum( np.isnan(lons) ), sum( np.isnan(lats) ) #12352 nan-pixels out of 25472 pixels
```
> (12352, 12352)

`np.nanmax(lons), np.nanmin(lons)`
> (84.68566, 36.313953)

-------

```python
my_area = scn["I01"].attrs['area'].compute_optimal_bb_area({'proj': 'lcc', 'lon_0': 35., 'lat_0': 50., 'lat_1': 50., 'lat_2': 50.})
lons_optimal, lats_optimal = my_area.get_lonlats()
print( lons_optimal.shape ), print( lats_optimal.shape )
```
> (6969, 16936)
> (6969, 16936)

```python
np.any( np.isnan(lons_optimal) ), np.any( np.isnan(lats_optimal) ) #No nan-value for any array element
```
> (False, False)

`print( lons_optimal )`
> [[36.98399656 36.9882579  36.99251922 ... 93.44126797 93.4434173
>   93.44556652]
>  [36.9837679  36.98802875 36.99228958 ... 93.43695573 93.43910506
>   93.44125427]
>  [36.98353929 36.98779965 36.99205999 ... 93.43264399 93.43479332
>   93.43694253]
>  ...
>  [36.10037132 36.10273553 36.10509974 ... 72.61398324 72.61579863
>   72.61761398]
>  [36.10030097 36.10266502 36.10502908 ... 72.61196351 72.61377884
>   72.61559412]
>  [36.10023062 36.10259453 36.10495844 ... 72.60994397 72.61175924
>   72.61357446]]

`np.max(lons_optimal) , np.min(lons_optimal)`
> (93.44556651556852, 36.10023062183153)

`np.max(lats_optimal) , np.min(lats_optimal)`
> (67.51536906813563, 35.865271984165695)

**Comment by mraspaud** [comment]
I agree with your analysis @djhoese and would also recommend not using `compute_optimal_bb_area` directly.
For example, you could use an area like this:
```yaml
laea_bb:
  description: Lambert Azimuthal Equal-Area Bounding Box for Polar Overpasses
  projection:
    ellps: WGS84
    proj: laea
  resolution: 300
  optimize_projection: True
```
(note the 300 resolution)

However, whether this will solve your problem or not, I don't know. Having NaNs at the edges is indeed a problem that we need to tackle, but as @djhoese, it's problematic performance-wise. A long term solution I believe would be to use provided metadata from the file (in viirs SDR files for example they to have a "geo ring" attribute that just give the granule edge lon-lats), but that's not on my short-term todo list yet.
