### ISSUE TITLE
Composites delayed in the presence of non-dimensional coordinates

### ISSUE THREAD

**Issue by sfinkens** [pytroll/satpy#795]
**Describe the bug**
Creating composites is delayed if the datasets have non-dimensional coordinates (`acq_time` in this case). The reason is that `xr.concat` in `GenericCompositor._concat_datasets` fails because

a) Channel differences don't have an `acq_time` coordinate
b) The `acq_time` coordinates are not equal across the channels

**To Reproduce**
a)
```python
from satpy import Scene
from satpy.utils import logging_on
import logging
import glob
logging_on(logging.DEBUG)
filenames = glob.glob('tline/data/*201903011200*')
scene = Scene(filenames=filenames, reader='seviri_l1b_hrit')
scene.load(['airmass'])
scene.show('airmass')
```

b)
```python
scene.load(['overview'])
scene.show('overview')
```

**Expected behavior**
The composites to be displayed

**Actual results**
Tracebacks & logging (first line is the error message from `xr.concat`)

a)
<details>

```
[DEBUG: 2019-05-28 15:18:42 : satpy.composites] Original exception for incompatible areas: encountered unexpected variable 'acq_time'
[DEBUG: 2019-05-28 15:18:42 : satpy.scene] Delaying generation of DatasetID(name='airmass', wavelength=None, resolution=None, polarization=None, calibration=None, level=None, modifiers=None) because of incompatible areas
[WARNING: 2019-05-28 15:18:42 : satpy.scene] The following datasets were not created and may require resampling to be generated: DatasetID(name='airmass', wavelength=None, resolution=None, polarization=None, calibration=None, level=None, modifiers=None)
[DEBUG: 2019-05-28 15:18:42 : satpy.scene] Unloading dataset: DatasetID(name='IR_108', wavelength=(9.8, 10.8, 11.8), resolution=3000.403165817, polarization=None, calibration='brightness_temperature', level=None, modifiers=())
[DEBUG: 2019-05-28 15:18:42 : satpy.scene] Unloading dataset: DatasetID(name='WV_073', wavelength=(6.85, 7.35, 7.85), resolution=3000.403165817, polarization=None, calibration='brightness_temperature', level=None, modifiers=())
[DEBUG: 2019-05-28 15:18:42 : satpy.scene] Unloading dataset: DatasetID(name='IR_097', wavelength=(9.38, 9.66, 9.94), resolution=3000.403165817, polarization=None, calibration='brightness_temperature', level=None, modifiers=())
Traceback (most recent call last):
  File "/cmsaf/nfshome/sfinkens/software/devel/satpy/satpy/readers/__init__.py", line 335, in __getitem__
    return super(DatasetDict, self).__getitem__(item)
KeyError: 'airmass'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 11, in <module>
    scene.show('airmass')
  File "/cmsaf/nfshome/sfinkens/software/devel/satpy/satpy/scene.py", line 1148, in show
    img = get_enhanced_image(self[dataset_id].squeeze(), overlay=overlay)
  File "/cmsaf/nfshome/sfinkens/software/devel/satpy/satpy/scene.py", line 680, in __getitem__
    return self.datasets[key]
  File "/cmsaf/nfshome/sfinkens/software/devel/satpy/satpy/readers/__init__.py", line 337, in __getitem__
    key = self.get_key(item)
  File "/cmsaf/nfshome/sfinkens/software/devel/satpy/satpy/readers/__init__.py", line 326, in get_key
    best=best, **dfilter)
  File "/cmsaf/nfshome/sfinkens/software/devel/satpy/satpy/readers/__init__.py", line 277, in get_key
    raise KeyError("No dataset matching '{}' found".format(str(key)))
KeyError: "No dataset matching 'DatasetID(name='airmass', wavelength=None, resolution=None, polarization=None, calibration=None, level=None, modifiers=None)' found"
```

</details>

b)
<details>

```
[DEBUG: 2019-05-28 15:21:49 : satpy.composites] Original exception for incompatible areas: variable acq_time not equal across datasets
[DEBUG: 2019-05-28 15:21:49 : satpy.scene] Delaying generation of DatasetID(name='overview', wavelength=None, resolution=None, polarization=None, calibration=None, level=None, modifiers=None) because of incompatible areas
[WARNING: 2019-05-28 15:21:49 : satpy.scene] The following datasets were not created and may require resampling to be generated: DatasetID(name='overview', wavelength=None, resolution=None, polarization=None, calibration=None, level=None, modifiers=None)
Traceback (most recent call last):
  File "/cmsaf/nfshome/sfinkens/software/devel/satpy/satpy/readers/__init__.py", line 335, in __getitem__
    return super(DatasetDict, self).__getitem__(item)
KeyError: 'overview'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 11, in <module>
    scene.show('overview')
  File "/cmsaf/nfshome/sfinkens/software/devel/satpy/satpy/scene.py", line 1148, in show
    img = get_enhanced_image(self[dataset_id].squeeze(), overlay=overlay)
  File "/cmsaf/nfshome/sfinkens/software/devel/satpy/satpy/scene.py", line 680, in __getitem__
    return self.datasets[key]
  File "/cmsaf/nfshome/sfinkens/software/devel/satpy/satpy/readers/__init__.py", line 337, in __getitem__
    key = self.get_key(item)
  File "/cmsaf/nfshome/sfinkens/software/devel/satpy/satpy/readers/__init__.py", line 326, in get_key
    best=best, **dfilter)
  File "/cmsaf/nfshome/sfinkens/software/devel/satpy/satpy/readers/__init__.py", line 277, in get_key
    raise KeyError("No dataset matching '{}' found".format(str(key)))
KeyError: "No dataset matching 'DatasetID(name='overview', wavelength=None, resolution=None, polarization=None, calibration=None, level=None, modifiers=None)' found"
```

</details>

**Screenshots**

**Environment Info:**
 - OS: Linux
 - Satpy Version: '0.14.2+198.gcd65262b'
 - PyResample Version:

**Comment by djhoese** [comment]
I have a possibly controversial opinion on this. I've had time to investigate this a little and came up with the same solution as @BENR0 (mentioned in #796) which is resampling fixes this. I've also been working on #788 which modifies the base reader and the resamplers to re-set `x`, `y`, and `crs` coordinates. The resamplers will keep any coordinates that aren't on the x or y dimensions (so non-dimensionals and scalars).

This behavior that you are running in to is one of the ways xarray coordinates are supposed to work. If data looks the same but *isn't* then we can't put them together. So my unpopular opinion is that requiring resampling for this to work is an expected evil/annoyance:

```python
scn = Scene(reader='seviri_l1b_hrit', filenames=[...])
scn.load(['overview'])
new_scn = scn.resample(resampler='native')
# 'overview' now exists
```

If this is deemed too annoying then I suggest we do one of the following:

1. Create a satpy global/constant list of coordinates that are "neglible" and remove/ignore them in `check_areas` of the composite generation. These coordinates are understood to be "close-enough" for most operations, but provide a meaningful amount of metadata for some users that they should still exist if possible.
2. Remove `acq_time` from the readers

**Comment by djhoese** [comment]
For option 1, we could make it so any `'time' in coord_name` get excluded automatically. Kind of a "we know that the times are close enough" kind of idea.

**Comment by sfinkens** [comment]
@djhoese That makes sense. In my opinion it is very nice to have the timestamps next to the data, so I prefer option 1. A third option could be to provide the timestamps as separate datasets. Can datasets be 1-D?

**Comment by gerritholl** [comment]
I want to keep the `acq_time` coordinate :/  see https://github.com/pytroll/satpy/pull/3168.

**Comment by gerritholl** [comment]
Isn't `check_times` (introduced by @djhoese in https://github.com/sfinkens/satpy/commit/c1b65cf18b072915f53ba58cd16bcfd613072f68) supposed to take care of this?
