### ISSUE TITLE
eps_l1b reader does not accept more than 1 veadr element

### ISSUE THREAD

**Issue by TAlonglong** [pytroll/satpy#924]
The eps_l1b reader does not accept more than 1 veadr element in the eps l1b file. 

According to documentation:  https://www.eumetsat.int/website/wcm/idc/idcplg?IdcService=GET_FILE&dDocName=PDF_AVHRR_L1B_PRODUCT_GUIDE&RevisionSelectionMethod=LatestReleased&Rendition=Web table 6-6 bottom page 33

`VEADR: Occurs at least once. Re-occurs each time the applicability of the information changes within the product `

The reader works perfectly for 1 VEADR, but not for 2 ( not tested for more than 2)

**To Reproduce**

```
#!/usr/bin/env python3

from satpy import Scene, find_files_and_readers
from satpy.utils import debug_on
debug_on()

files = find_files_and_readers(base_dir='/data/pytroll/testdata/eps-l1b/')

global_scene = Scene(filenames=files)
global_scene.load(['overview'])
```

**Expected behavior**
The reader to handle at least 1 veadr but also more than 1

**Actual results**
```
[DEBUG: 2019-10-08 10:34:09 : satpy.readers.eps_l1b] Reading /data/pytroll/testdata/eps-l1b/avhrr_metop02_20191008055203_20191008062503.eps
[ERROR: 2019-10-08 10:34:13 : satpy.readers.yaml_reader] Could not load dataset 'DatasetID(name='longitude', wavelength=None, resolution=1050, polarization=None, calibration=None, level=None, modifiers=())': Too many ('veadr', 1)
Traceback (most recent call last):
  File "/software/pytroll/lib/python3.5/site-packages/satpy/readers/yaml_reader.py", line 722, in _load_dataset_with_area
    ds = self._load_dataset_data(file_handlers, dsid)
  File "/software/pytroll/lib/python3.5/site-packages/satpy/readers/yaml_reader.py", line 602, in _load_dataset_data
    proj = self._load_dataset(dsid, ds_info, file_handlers)
  File "/software/pytroll/lib/python3.5/site-packages/satpy/readers/yaml_reader.py", line 578, in _load_dataset
    projectable = fh.get_dataset(dsid, ds_info)
  File "/software/pytroll/lib/python3.5/site-packages/satpy/readers/eps_l1b.py", line 309, in get_dataset
    self._read_all(self.filename)
  File "/software/pytroll/lib/python3.5/site-packages/satpy/readers/eps_l1b.py", line 174, in _read_all
    raise ValueError("Too many " + str((rec_class, sub_class)))
ValueError: Too many ('veadr', 1)
[DEBUG: 2019-10-08 10:34:13 : satpy.readers.yaml_reader] No coordinates found for DatasetID(name='latitude', wavelength=None, resolution=1050, polarization=None, calibration=None, level=None, modifiers=())
Traceback (most recent call last):
  File "/software/pytroll/scripts/test-veadr.py", line 10, in <module>
    global_scene.load(['overview'])
  File "/software/pytroll/lib/python3.5/site-packages/satpy/scene.py", line 967, in load
    self.read(**kwargs)
  File "/software/pytroll/lib/python3.5/site-packages/satpy/scene.py", line 875, in read
    return self._read_datasets(nodes, **kwargs)
  File "/software/pytroll/lib/python3.5/site-packages/satpy/scene.py", line 716, in _read_datasets
    new_datasets = reader_instance.load(ds_ids, **kwargs)
  File "/software/pytroll/lib/python3.5/site-packages/satpy/readers/yaml_reader.py", line 794, in load
    ds = self._load_dataset_with_area(dsid, coords)
  File "/software/pytroll/lib/python3.5/site-packages/satpy/readers/yaml_reader.py", line 722, in _load_dataset_with_area
    ds = self._load_dataset_data(file_handlers, dsid)
  File "/software/pytroll/lib/python3.5/site-packages/satpy/readers/yaml_reader.py", line 602, in _load_dataset_data
    proj = self._load_dataset(dsid, ds_info, file_handlers)
  File "/software/pytroll/lib/python3.5/site-packages/satpy/readers/yaml_reader.py", line 578, in _load_dataset
    projectable = fh.get_dataset(dsid, ds_info)
  File "/software/pytroll/lib/python3.5/site-packages/satpy/readers/eps_l1b.py", line 312, in get_dataset
    lons, lats = self.get_full_lonlats()
  File "/software/pytroll/lib/python3.5/site-packages/satpy/readers/eps_l1b.py", line 232, in get_full_lonlats
    shape=(self.scanlines, self.pixels))
  File "/software/pytroll/lib/python3.5/site-packages/dask/array/core.py", line 2406, in from_delayed
    return Array(graph, name, chunks, dtype)
  File "/software/pytroll/lib/python3.5/site-packages/dask/array/core.py", line 880, in __new__
    self._chunks = normalize_chunks(chunks, shape, dtype=self.dtype)
  File "/software/pytroll/lib/python3.5/site-packages/dask/array/core.py", line 1995, in normalize_chunks
    return tuple(tuple(int(x) if not math.isnan(x) else x for x in c) for c in chunks)
  File "/software/pytroll/lib/python3.5/site-packages/dask/array/core.py", line 1995, in <genexpr>
    return tuple(tuple(int(x) if not math.isnan(x) else x for x in c) for c in chunks)
  File "/software/pytroll/lib/python3.5/site-packages/dask/array/core.py", line 1995, in <genexpr>
    return tuple(tuple(int(x) if not math.isnan(x) else x for x in c) for c in chunks)
TypeError: a float is required
```

**Environment Info:**
 - OS: Linux
 - Satpy Version: 0.17.0 but also in 0.16.1

**Additional context**
link to test data: https://drive.google.com/file/d/1C1EDFdLv5w8hqQMGrWDd9Oh1jXjzHN16/view?usp=sharing

**Comment by TAlonglong** [comment]
Possible work around. In the eumetsat kaui tool documentation https://www.eumetsat.int/website/wcm/idc/idcplg?IdcService=GET_FILE&dDocName=PDF_TEN_04014_UG-KAI&RevisionSelectionMethod=LatestReleased&Rendition=Web apendix A the number of veadr's can be changed:

If I do: `kai /data/pytroll/eps-global/avhrr_metop02_20191008055203_20191008062503.eps --remove class=veadr:subclass=1:range=1- -o <outfile>` all but the first veadr is removed from the eps file.

**Comment by mraspaud** [comment]
Thanks for the workaround! However, we should really fix this as it's not following the documentation
